### ISSUE TITLE
Getting an EFCore power tools crash (error) in Add DBContext flow

### ISSUE THREAD

**Issue by arafeeq21** [ErikEJ/EFCorePowerTools#1009]
Describe what is not working as expected.
Unable to generate the model view from Db context.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
I have a simple PartyDbContext::DbContext class built; that resides in a Data project. Click EF Core Power Tools -> Add DbContext Diagram

Encounter the following failure:
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'PartyDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[DocuSign.Adm.Parties.Data.PartyDbContext]' while attempting to activate 'DocuSign.Adm.Parties.Data.PartyDbContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 39
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 57

Parameter name: processResult
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.665.0

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite)
MySql Server

Visual Studio version: (e.g. Visual Studio 2019 16.9)
2019 16.10

**Comment by ErikEJ** [comment]
Please read the wiki https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model and follow the clear error message.

**Comment by ErikEJ** [comment]
Closing, feel free to reopen if the problem persists.
