### ISSUE TITLE
Adding Migration Throws InvalidOperationException: The requested configuration is not stored in the read-optimized model.

### ISSUE THREAD

**Issue by joelmandell** [ErikEJ/EFCorePowerTools#1034]
Running the migration-command throws this Exception:
```
---------------------------
Microsoft Visual Studio
---------------------------
EF Core Power Tools

Error:

System.InvalidOperationException: The requested configuration is not stored in the read-optimized model, please use 'DbContext.GetService&lt;IDesignTimeModel&gt;().Model'.

   at Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.IsTableExcludedFromMigrations(IReadOnlyEntityType entityType)

   at Microsoft.EntityFrameworkCore.Metadata.Internal.Table.get_IsExcludedFromMigrations()

   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<>c.<GetSchemas>b__79_0(ITable t)

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()

   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()

   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()

   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()

   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()

   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)

   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)

   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)

   at Modelling.EfCoreMigrationsBuilder.AddMigration(String name, String outputPath, String startupOutputPath, String projectPath, String nameSpace, DbContext context) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreMigrationsBuilder.cs:line 212

   at Modelling.EfCoreMigrationsBuilder.BuildMigrationResult(String outputPath, String startupOutputPath, String projectPath, String contextName, Boolean addMigration, Boolean scriptMigration, String migrationIdentifier, String nameSpace) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreMigrationsBuilder.cs:line 62

   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 53

```

### Steps to reproduce
Throws when trying to add migration. I am running EF Core 6 Preview5. Actually I get the same exception when trying to use EnsureCreated() ( https://github.com/dotnet/efcore/issues/25154#issuecomment-868574295 )
I do not know what I have done 😂

### Further technical details
EF Core Power Tools version: version 2.5.692

Database engine: SQL Server

Visual Studio version: VS 2022 Preview.

**Comment by joelmandell** [comment]
Seems to be something stupid I did. Have to go through my git commits. Sorry for this. Reopening if else.

**Comment by joelmandell** [comment]
I was using custom implementation IModelCacheKeyFactory and had to make it use the new overload for Design-time:
https://github.com/dotnet/efcore/issues/25154#issuecomment-868804532

After this, it works fine :)

**Comment by ErikEJ** [comment]
Good to hear, and thanks for the additional information.
