### ISSUE TITLE
File not found:'PresentationFramework, Version=5.0.0.0

### ISSUE THREAD

**Issue by hardoverton** [ErikEJ/EFCorePowerTools#1038]
I just installed the extension in VS 2019 (updated to Version 16.10.3)
I am in a solution WPF(.NET Core 5.0) with a EF Core sub project.
When I select Add DB Context Diagram, I get:
System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'PresentationFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Reflection.RuntimeAssembly.get_EntryPoint()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveFactory[T](Assembly assembly, String name)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveWebHostFactory[TWebHost](Assembly assembly)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveServiceProviderFactory(Assembly assembly)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.Create(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at Modelling.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 82
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 33
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 57

Parameter name: processResult
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)

Can some help with where to go from here?

**Comment by ErikEJ** [comment]
Make sure to select the correct startup project in your solution.

**Comment by hardoverton** [comment]
Thank you. I should have said that the selected startup project is the WPF(core) project.

**Comment by ErikEJ** [comment]
If that does not work, please share a repro solution (potentially privately)

**Comment by hardoverton** [comment]
https://github.com/hardoverton/AcctCore

Let me know if you can't get to this

**Comment by ErikEJ** [comment]
I can get to it, but do not see any files.

**Comment by hardoverton** [comment]
Should be there now.

**Comment by ErikEJ** [comment]
I am able to reproduce, but have no idea why this fails.

@bricelam  ?

**Comment by bricelam** [comment]
Hmm, possibly some interference from the magic used by the .NET 5 WPF designer. @OliaG?

**Comment by ErikEJ** [comment]
Setting the project with just the DbContext (AcctCoreData) asthe startup project fixes the issue.
