### ISSUE TITLE
Wrong folder resolution when using Directory.GetCurrentDirectory

### ISSUE THREAD

**Issue by rmeshksar** [ErikEJ/EFCorePowerTools#1054]
Hi,
I apologize if this issue is not related to the  amazing EF Core Power Tools and rather C#, but I will appreciate your help.

I am using the following approach for my solution:
https://github.com/jasontaylordev/NorthwindTraders/blob/master/Src/Persistence/DesignTimeDbContextFactoryBase.cs

As you see on line 17 this code:
` var basePath = Directory.GetCurrentDirectory() + string.Format("{0}..{0}WebUI", Path.DirectorySeparatorChar);`

When I run regular migration command, `Directory.GetCurrentDirectory()` returns the working folder something like **C:\mysolution\myproject** , but when I run any of EF Power Tools options, it returns **C:\mysolution\myproject\bin\Debug\net5.0** and therefore cannot find the appsettings and throws this error:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: C:\mysolution\myproject\bin\Debug\api\
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
   at solution.Infrastructure.Persistence.DesignTimeDbContextFactoryBase`1.Create(String basePath, String environmentName) in C:\mysolution\myproject\Persistence\DesignTimeDbContextFactoryBase.cs:line 28
   at solution.Infrastructure.Persistence.DesignTimeDbContextFactoryBase`1.CreateDbContext(String[] args) in C:\mysolution\myproject\Persistence\DesignTimeDbContextFactoryBase.cs:line 20
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_2.<FindContextTypes>b__9()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 39
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 57

Parameter name: processResult
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)

**Comment by ErikEJ** [comment]
Looks like a potential improvement, are you able to share a repro project?

**Comment by rmeshksar** [comment]
It should be possible to use this:
https://github.com/jasontaylordev/NorthwindTraders

**Comment by rmeshksar** [comment]
The following (thanks to https://github.com/dotnet/EntityFramework.Docs/issues/1490#issuecomment-497082468)  would work but I am not sure it is the best approach:

```
  var workingFolder = Directory.GetParent(AppContext.BaseDirectory);
  do
      workingFolder = workingFolder.Parent;
  while (workingFolder.Name != "bin");
  workingFolder = workingFolder.Parent;
  var basePath = workingFolder.FullName + string.Format("{0}..{0}WebUI", Path.DirectorySeparatorChar);
```

**Comment by ErikEJ** [comment]
Yes, maybe it is better to work around the issue in your code..
