### ISSUE TITLE
Two DbContext in one project

### ISSUE THREAD

**Issue by tnlthanzeel** [ErikEJ/EFCorePowerTools#1101]
Hi @ErikEJ , i have a project where i have 2 different db contexts. Once i run the "Add DbContext Daigram" the project builds but there is no diagram or any out to see.

![image](https://user-images.githubusercontent.com/18216790/133727480-330daf76-b709-4a60-87eb-cf1f52130d8d.png)

How can i view this ? please help

*Identity.EntityFrameworkCore" Version="5.0.2"
*library project is on net5.0
*

**Comment by ErikEJ** [comment]
Have you checked the "Extensions" output window for errors?

Otherwise, please share a repro project

**Comment by tnlthanzeel** [comment]
> Have you checked the "Extensions" output window for errors?
> 
> Otherwise, please share a repro project

System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.get_Signature()
   at System.Reflection.RuntimeMethodInfo.get_ReturnType()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.IsFactory[TReturn](MethodInfo factory)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveFactory[T](Assembly assembly, String name)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveHostBuilderFactory[THostBuilder](Assembly assembly)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveServiceProviderFactory(Assembly assembly)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.Create(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at Modelling.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 82
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 33
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 57

Parameter name: processResult
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)

This is the error in my "Extentions" output windows

**Comment by ErikEJ** [comment]
Have you set the correct Startup project in VS?

**Comment by tnlthanzeel** [comment]
> Have you set the correct Startup project in VS?

This is project structure

![image](https://user-images.githubusercontent.com/18216790/133733922-d58dff02-a37f-4457-8a8a-61781858021a.png)
 
The ICMS.Web is the startup project

**Comment by tnlthanzeel** [comment]
@ErikEJ, when I right clicked on the ICMS.Web project and clicked on "Add DbContext Daigram", i got the dgml for only for one db context. how can i get the dgml diagram for the other db context?

**Comment by tnlthanzeel** [comment]
okay i got it working, once i right clicked on the ICMS.Web project and clicked on "Add DbContext Daigram" i got both diagrams. it works

![image](https://user-images.githubusercontent.com/18216790/133735045-adec2479-1974-44a9-8e8e-34bc1cb7ee19.png)


Thanks a lot @ErikEJ , this tool is great!

**Comment by ErikEJ** [comment]
You are welcome - If you enjoy my free tools, I would be very grateful for a rating or review:

https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details

**Comment by tnlthanzeel** [comment]
> You are welcome - If you enjoy my free tools, I would be very grateful for a rating or review:
> 
> https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details

![image](https://user-images.githubusercontent.com/18216790/133736727-7f5626bc-5b2d-45ab-9d90-9e37a375fbde.png)

Done
