### ISSUE TITLE
EF Core Power Tools reverse engineering error

### ISSUE THREAD

**Issue by caojinqin** [ErikEJ/EFCorePowerTools#115]
EF Core Power Tools reverse engineering error, I hope to see the new version to solve the bug.
### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
I get an error when I am using the last step of reverse engineering

EF(Core2.1)

EF Core Power Tools version: (1.0.664)

Database engine: (SQL Server 2018 / SSMS V17.6 )

Visual Studio version: (Visual Studio 2017 15.8.7)

**Comment by ErikEJ** [comment]
Which error, please - otherwise it is completely impossible to help you!

**Comment by emadyazdan** [comment]
I get the following error:
Ef Core Power Tool Version 1.0.675
Visual Studio Version 4.6.01055
.Net Core 2.1



System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at EFCorePowerTools.Extensions.EvnDTEExtensions.GetDacpacFilesInActiveSolution(DTE dte) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\EvnDTEExtensions.cs:line 29
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 46

**Comment by kachalkov** [comment]
same issue, please fix

**Comment by MissyGH** [comment]
Just FYI, I had this error and it resolved itself when I exited VS, tried EF Power Tools in a new project and then went back to my original project.

**Comment by ErikEJ** [comment]
@MissyGH This issue was fixed long ago, if you still experience this issue with the latest version, please create a new issue

**Comment by VicoMorales** [comment]
**Hi I had this error** 

![error](https://user-images.githubusercontent.com/20495000/79062841-2efa8d00-7c63-11ea-9c14-1581e27fa984.PNG)

**Comment by ErikEJ** [comment]
@VicoMorales  Please dont post new issues on closed ones - have you seen: https://github.com/ErikEJ/EFCorePowerTools/issues/363

**Comment by Matews-Gomes** [comment]
hi how are i getting this output when i try to reverse engineer in VS please help me. Thanks!

System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at IEnumerable<TSource> System.Linq.Enumerable.Where<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)

**Comment by ErikEJ** [comment]
@Matews-Gomes make sure to get the latest version (.961)
