### ISSUE TITLE
InvalidOperationException with View DbContext DDL SQL after upgrade to .Net 6 and latest EFCorePowerTools.

### ISSUE THREAD

**Issue by toddbellamy** [ErikEJ/EFCorePowerTools#1187]
After upgrading to latest VS 2022, .Net 6 and EFCorePowerTools, ViewDbContext DDL SQL now gives this exception:
(we aren't using migrations at all)

System.ArgumentException: Error:
System.InvalidOperationException: The requested configuration is not stored in the read-optimized model, please use 'DbContext.GetService&lt;IDesignTimeModel&gt;().Model'.
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.IsTableExcludedFromMigrations(IReadOnlyEntityType entityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Table.get_IsExcludedFromMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<>c.<GetSchemas>b__79_0(ITable t)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Modelling.EfCoreModelBuilder.GenerateCreateScript(DbContext dbContext) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 58
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 41
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 27

Parameter name: processResult
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)

EF Core version in use: EF Core 6

EF Core Power Tools version: 2.5.832

Database engine: SQL Server

Visual Studio version: Visual Studio 2022 17.0.1

**Comment by ErikEJ** [comment]
Can you share your csproj?

**Comment by ErikEJ** [comment]
Fixed in latest daily build
