### ISSUE TITLE
Cannot create a diagram

### ISSUE THREAD

**Issue by bravo-2007** [ErikEJ/EFCorePowerTools#1203]
On my WebAPI .net 5 framework project, i am trying to use "Add DBContext Diagram" menu to generate a diagram but Getting following error on Extensions output window. Not sure if this is because something not setup right or something missing? i would appreciate some guidance

### Steps to reproduce

- .net core API project with code first DbContext coded. 
- Right click on project and click "Add DBContext Diagram" menu
- Observe error

====ERROR ===
System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.get_Signature()
   at System.Reflection.RuntimeMethodInfo.get_ReturnType()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.IsFactory[TReturn](MethodInfo factory)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveFactory[T](Assembly assembly, String name)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveHostBuilderFactory[THostBuilder](Assembly assembly)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveServiceProviderFactory(Assembly assembly)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.Create(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at Modelling.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 82
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 33
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 57

Parameter name: processResult
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)
System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.get_Signature()
   at System.Reflection.RuntimeMethodInfo.get_ReturnType()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.IsFactory[TReturn](MethodInfo factory)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveFactory[T](Assembly assembly, String name)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveHostBuilderFactory[THostBuilder](Assembly assembly)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveServiceProviderFactory(Assembly assembly)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.Create(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at Modelling.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 82
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 33
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 57

Parameter name: processResult
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)

### Further technical details
EF Core version in use: EF Core 5
EF Core Power Tools version: 2.5.832
Database engine: SQL Server
Visual Studio version: Visual Studio 2019 Version 16.9.4

**Comment by ErikEJ** [comment]
Wrong startup project? There is additional tips and advice here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model#challenges

**Comment by TimesliceTechnologies** [comment]
I have the same issue, however in my case I simply get a popup 
"EF Core Power Tools - Installing EFCore.Design version 6.0.0, please retry the command."

![image](https://user-images.githubusercontent.com/24999534/144517571-35c21afd-5f28-4521-9b6a-06582f660f2d.png)

I have a simple console application as the startup project, VS2022, .Net Core 6, and a second project it references which is the class library containing my DB context etc..  That is the project I am right clicking to invoice EFtoosl / Create DB context diagram.  Erik you that is the same solution I sent in my previous post today regarding naming problems with GUID fields.

**Comment by TimesliceTechnologies** [comment]
Ok.  Have manully added Microsoft.EntityFrameworkCore.Design 6.0 from nuget.
Now I've got the following error on the output windows in VS2022:
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, DbContextOptions contextOptions, DbContext context)

I understand the issue is that a connection string needs to be configured - just not sure where to make that happen.  I would be grateful for any input.  Main application is a simple console applciation.  The DB context is in a separate and reference project in the same solution.

**Comment by ErikEJ** [comment]
I think I need to see your code, for example add a dummy connection string in OnConfiguring.

You can share privately: ejlskov at hotmail dot com

**Comment by ErikEJ** [comment]
The error message should explain what needs to be done
