### ISSUE TITLE
Reverse Engineer no connections available

### ISSUE THREAD

**Issue by tomasfil** [ErikEJ/EFCorePowerTools#1206]
Describe what is not working as expected.

I have SQL normally connected to server explorer
![image](https://user-images.githubusercontent.com/34779382/144558877-580cf9af-0f5c-4e56-be8a-ec5b71488e54.png)

Credentials are ok:
![image](https://user-images.githubusercontent.com/34779382/144559057-0aa2742c-cce8-4867-8b42-8136d4957e29.png)

Press ok and...:
![image](https://user-images.githubusercontent.com/34779382/144559090-d11ecd75-804e-4b40-9a8e-ac6db72fc5a0.png)

I have never used this power tool, but I dont see any issue on my part. I did also try running VS in admin mode, but nothing changes.

### Further technical details

EF Core 5

Visual Studio 2022

![image](https://user-images.githubusercontent.com/34779382/144558752-aa19e8eb-4684-45f6-baa1-8b4650b3a093.png)

![image](https://user-images.githubusercontent.com/34779382/144559284-1f8f0da4-c482-4500-9bb7-11033fafe8a1.png)

![image](https://user-images.githubusercontent.com/34779382/144559318-a612f772-f732-44e4-abed-285062202394.png)

**Comment by ErikEJ** [comment]
The Oracle VS 2022 tools are not available yet..

**Comment by tomasfil** [comment]
Figured that out. Tested on VS 2019 and I get this error:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: An item with the same key has already been added.
   at void System.Collections.Generic.Dictionary<TKey, TValue>.Insert(TKey key, TValue value, bool add)
   at void System.Collections.Generic.Dictionary<TKey, TValue>.Add(TKey key, TValue value)
   at new Microsoft.VisualStudio.Data.Package.DataExplorerConnection(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at object Microsoft.VSDesigner.ServerExplorer.DataConnectionsNode.GetConnectionHierarchy(int connectionIndex)
   at IVsDataExplorerConnection Microsoft.VisualStudio.Data.Package.DataExplorerConnectionManager+Dictionary.get_Item(int index)
   at ICollection<IVsDataExplorerConnection> Microsoft.VisualStudio.Data.Package.DataExplorerConnectionManager+Dictionary.get_Values()
   at Dictionary<string, DatabaseConnectionModel> EFCorePowerTools.Helpers.VsDataHelper.GetDataConnections(EFCorePowerToolsPackage package)

**Comment by ErikEJ** [comment]
Fix your broken connections in Server Explorer.

**Comment by tomasfil** [comment]
Well, that is very counter intuitive error. This might do some kind of message box saying to remove invalid connections in server explorer. 

That fixed reverse engineering.

Sorry for maybe stupid question, but upon diagram generation yet again another error pops...
```
System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'PresentationFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Reflection.RuntimeAssembly.get_EntryPoint()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveFactory[T](Assembly assembly, String name)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveWebHostFactory[TWebHost](Assembly assembly)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveServiceProviderFactory(Assembly assembly)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.Create(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at Modelling.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 82
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 33
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 57

Parameter name: processResult
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)
```

It is not possible to generate Diagram in Class Library?

**Comment by tomasfil** [comment]
Its needed to setup the project as startup. Like with EF core tools.
