### ISSUE TITLE
Add DbContext Diagram fault in Blazor app

### ISSUE THREAD

**Issue by Andy-Corrigan** [ErikEJ/EFCorePowerTools#1216]
Hi,

I'm currently developing a Blazor Server-side app. I've encountered an issue with the tool for adding the DB Context diagram. I can survive without the diagram, but I figured I'd report the issue as anyone with a similar setup would likely face it too. 

Essentially the crux of it is: my solution has two projects - one is the actual web app and the other is my datalibrary. When I attempt to add the DB context diagram, I am met with the following exception: 

Parameter name: processResult
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)
System.ArgumentException: Error:
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'FIS2_DbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[DataLibrary.Models.FIS2_FranklinContext_AutoGenerated]' while attempting to activate 'DataLibrary.Models.FIS2_DbContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_4.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_4.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 39
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 57

Parameter name: processResult
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)

I think this is because FIS2_DbContext is a partial class that adds some bolt-ons to the auto-generated dbContext?

**Comment by ErikEJ** [comment]
Make sure to select the correct startup project in VS, and try creating the diagram when the executable project is active

**Comment by Andy-Corrigan** [comment]
Do you mean try it when debugging? That just asks me if I want to stop debugging.

**Comment by ErikEJ** [comment]
No, I mean when running the tool to create the diagram.

**Comment by Andy-Corrigan** [comment]
So: 

1. Right-click project containing the DbContext
2. Go-to EF Core Power Tools submenu
3. Click "Add Db Context Diagram"
4. See what happens? 

Step 4 is where it fails with the above exception; Reverse Engineer works perfectly, however.

**Comment by ErikEJ** [comment]
As I said: try: right click the Blazor project

**Comment by Andy-Corrigan** [comment]
I'm slightly confused as to how that works, but it worked. I would've thought that the DbContext diagram would go in the project that has the DbContext, not the other one.

**Comment by ErikEJ** [comment]
Magic!
