### ISSUE TITLE
EF core migrations crashes if DbContext cannot be consctructed from migration project.

### ISSUE THREAD

**Issue by Fulgan** [ErikEJ/EFCorePowerTools#1224]
Describe what is not working as expected.

The extension doesn't support project where the migrations are not in the same solution as a creatable dbContext.

### Steps to reproduce

Create a sollution with 2 projects. Put DB code and migration in one project but make sure the DbContext constructor cannot be called directly (i.e. no public parameterless constructor).

Right-click on the DB code and select "EF core power tools" -> "Migration tools (preview)"

Error:

Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'AppDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions' while attempting to activate 'Peppermint.Infrastructure.Data.AppDbContext'.

   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)

   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)

   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)

   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()

   --- End of inner exception stack trace ---

   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()

   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)

   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)

   at Modelling.EfCoreMigrationsBuilder.GetMigrationStatus(String outputPath, String startupOutputPath) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreMigrationsBuilder.cs:line 81

   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 41

In such a scenario, the ef core tools uses the "-s" parameter to specify the path of the project that can be used to obtain an instance of the AppDbContext. No such configuration option is possible with 

### Further technical details

EF Core version in use: (e.g. EF Core 5) EF core 5, EF core 6.

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu) 2.5.832.0

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL) SQL server

Visual Studio version: (e.g. Visual Studio 2019 16.11) VS 2022 17.0.4

**Comment by ErikEJ** [comment]
Make the other project the startup project, and run the tool from it.
