### ISSUE TITLE
Cannot "Add DbContext Diagram" or "View DbContext DDL SQL"

### ISSUE THREAD

**Issue by unruledboy** [ErikEJ/EFCorePowerTools#1281]
When trying to use "Add DbContext Diagram" or "View DbContext DDL SQL", it throws exception:

```
System.InvalidOperationException: Error:
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, DbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 39
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 27
```

### Steps to reproduce

1. Create a new console app using VS 2022 with .NET 6 target
2. Reverse engineer a SQL Server 2019 database with any table selected
3. Models generated correctly
4. Click "Add DbContext Diagram" or "View DbContext DDL SQL"

### Further technical details

EF Core version in use: EF Core 6.0.2

Is Handlebars used: no

EF Core Power Tools version: 2.5.908.0

Database engine: SQL Server 2019

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
have you responded to the error message? and consulted the wiki? https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model

**Comment by unruledboy** [comment]
hi @ErikEJ  just figured it, I need to choose the following option to make it work:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/682883/153590351-f963c55d-73bc-446d-952c-3063a6211d53.png">
