### ISSUE TITLE
Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.

### ISSUE THREAD

**Issue by epuig-ssinergie** [ErikEJ/EFCorePowerTools#133]
After i updated VS this morning, EFPT fails on reverse eng entities (this worked before)

### Steps to reproduce
Reverse egineer, from database or DACPAC file, i only check Pluralize option, and click OK

System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Le fichier spécifié est introuvable.
File name: 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKey(ModelBuilder modelBuilder, DatabaseForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 194

### Further technical details
Windows 10
Visual Studio 15.9.2
.net Framework 4.6.2
.net core 2.1 project
Latest EFPT nightly build or release, same issue

**Comment by ErikEJ** [comment]
I think upgrading to the latest .net version could fix this. Version 4.7.1 or newer

**Comment by ErikEJ** [comment]
See https://github.com/ErikEJ/EFCorePowerTools/issues/94

**Comment by Herdo** [comment]
Calls for `BindingRedirect`. Even though that will hurt over time.
See https://stackoverflow.com/a/40118966/2132796 . I think upgrading the package to 4.7 wouldn't be an option, as there are some constraints, right?

**Comment by epuig-ssinergie** [comment]
Thank you for your quick help.

Actually, I can't upgrade framework with my windows 10 build 1511 - (laptop provided by company) 
https://docs.microsoft.com/fr-fr/dotnet/framework/install/on-windows-10

So i checked and
Assembly System.ValueTuple 4.0.2.0 comes from my system C:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ValueTuple.dll


Finally i added to EFCorePowerTools - AssemblyInfo.cs following code, and seems to work (only tested in debug)

[assembly: ProvideBindingRedirection(AssemblyName = "System.ValueTuple",
      NewVersion = "4.0.3.0", OldVersionLowerBound = "0.0.0.0",
      OldVersionUpperBound = "4.0.2.0")]

**Comment by ErikEJ** [comment]
@epuig-ssinergie Interesting! Could you submit a PR or that change?

**Comment by ErikEJ** [comment]
Closing, as I will update Revese Engineering to use EF Core 2.2 "soon"
