### ISSUE TITLE
Got an exception after last update 2.5.963

### ISSUE THREAD

**Issue by alekoo73** [ErikEJ/EFCorePowerTools#1360]
Got an exception during Reverse Engineer

Unable to get result set shape for FUNCTION 'hr.fPersonalReport'
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 25

As far as I can see it has problems with all (not some) TFV's in SQL Server.

EF Core version in use: EF Core 6

EF Core Power Tools version: 2.5.963

Database engine: SQL Server

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Fixed in latest daily build
