### ISSUE TITLE
Unable to reverse engineer stored procedure using TVP parameter with NVARCHAR(MAX) column

### ISSUE THREAD

**Issue by rkcorpay** [ErikEJ/EFCorePowerTools#1361]
Unable to reverse engineer stored procedure using TVP as parameter because the TVP includes columns with NVARCHAR(MAX). 

Error Output: 
```
Unable to get result set shape for PROCEDURE 'dbo.MyProcedure'
System.Data.DuplicateNameException: A column named 'ColumnName' already belongs to this DataTable.
   at System.Data.DataColumnCollection.RegisterColumnName(String name, DataColumn column)
   at System.Data.DataColumnCollection.BaseAdd(DataColumn column)
   at System.Data.DataColumnCollection.AddAt(Int32 index, DataColumn column)
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetDataTableFromSchema(ModuleParameter parameter, SqlConnection connection) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 155
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetAllResultSets(SqlConnection connection, Routine module, Boolean singleResult) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 83
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetResultElementLists(SqlConnection connection, Routine module, Boolean multipleResults, Boolean useLegacyResultSetDiscovery) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 62
   at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 25
```

I noticed that recent changes to `SqlServerStoredProcedureModelFactory.GetDataTableFromSchema` don't compensate for the sysname datatypes with the same name returned alongside NVARCHAR(MAX). Maybe we filter those out?

EF Core version in use: EF Core 6

Is Handlebars used: no

EF Core Power Tools version: 2.5.963

Database engine: SQL Server, Azure SQL

Visual Studio version: Visual Studio 2022 - Preview 4

**Comment by ErikEJ** [comment]
Thanks for reporting this.

>> I noticed that recent changes to SqlServerStoredProcedureModelFactory.GetDataTableFromSchema don't compensate for the sysname datatypes with the same name returned alongside NVARCHAR(MAX). Maybe we filter those out?

I do not understand what this means, are you able to provider and example / more info?

As a workaround, you could try to use legacy discovery for the procedure: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by rkcorpay** [comment]
Using the SQL from https://github.com/ErikEJ/EFCorePowerTools/blob/a8c0c907b93f662656110f1553a5ac6fddb471d1/src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureModelFactory.cs#L139, run the following:
```sql
CREATE TYPE [dbo].[exampletvp] AS TABLE ([ColumnName] NVARCHAR(MAX))
DECLARE @objectid INT;
SELECT @objectid=type_table_object_id FROM sys.table_types WHERE name = 'exampletvp'
SELECT SC.name, ST.name AS datatype FROM sys.columns SC
INNER JOIN sys.types ST ON ST.system_type_id = SC.system_type_id AND ST.is_user_defined = 0
WHERE SC.object_id = @objectid
```

**Comment by ErikEJ** [comment]
Thanks, I will have a look. Did you try the workaround?

**Comment by rkcorpay** [comment]
Yes, sorry I forgot to mention. The legacy option does complete without an error message.

**Comment by alekoo73** [comment]
Same problem, @ErikEJ 's workaround does not work ,problem exists even when there are no nvarchar(max) columns

Unable to get result set shape for FUNCTION 'dbo.TVF'
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 25

**Comment by ErikEJ** [comment]
@alekoo73 not same issue as you can see from the error message. Ensure you are using latest build .966

**Comment by alekoo73** [comment]
@ErikEJ  Thanks ,now it works

**Comment by ErikEJ** [comment]
Fixed in latest daily, please let me know if it works for you

**Comment by rkcorpay** [comment]
Reverse engineering completed without the error message. Thanks for the temporary workaround and such a fast turnaround on a long-term solution!
