### ISSUE TITLE
Checkout files automatically

### ISSUE THREAD

**Issue by wcrec** [ErikEJ/EFCorePowerTools#137]
Is it possible to automatically check out files when reverse engineering? Every time I want to reverse engineer, I first have to check out the files. If I don't, I get the message below. I am using TFVC(server workspace) through Azure Devops, Visual Studio 2017 15.8.7, and EF Core PT 1.0.664.

> Microsoft.EntityFrameworkCore.Design.OperationException: No files generated in directory xyz. The following file(s) already exist and must be made writeable to continue: abc.cs,def.cs,etc....
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.CheckOutputFiles(ScaffoldedModel scaffoldedModel, String outputDir, Boolean overwriteFiles)
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.Save(ScaffoldedModel scaffoldedModel, String outputDir, Boolean overwriteFiles)
>    at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
>    at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 158

**Comment by ErikEJ** [comment]
VS should take care of this, not an issue when using writeable files (for example Git source control)
