### ISSUE TITLE
Reverse Engeneer -The implicit conversion of the nvarchar data type into binary is not allowed

### ISSUE THREAD

**Issue by werwin81** [ErikEJ/EFCorePowerTools#1380]
I want reverse engeneering a procedure, which has a binary(16) parameter. If I do so, I got the following error: The implicit conversion of the nvarchar data type into binary is not allowed. In the past, there were no problem.

I created this little procedure, which causes the problem too.

CREATE PROCEDURE [dbo].[TestProc] 
	@binaryParam binary(16)
AS
BEGIN
	select 5 as TestParam 
END

### Further technical details

EF Core version in use: 5.0.7
Is Handlebars used: no
EF Core Power Tools version: 2.5.966.0
Database engine: SQL Server 2019
Visual Studio 2022

Unable to get result set shape for PROCEDURE 'dbo.TestProc'
Microsoft.Data.SqlClient.SqlException (0x80131904): Die implizite Konvertierung vom nvarchar-Datentyp in binary ist nicht zulässig. Verwenden Sie die CONVERT-Funktion, um diese Abfrage auszuführen.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetAllResultSets(SqlConnection connection, Routine module, Boolean singleResult) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 90
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetResultElementLists(SqlConnection connection, Routine module, Boolean multipleResults, Boolean useLegacyResultSetDiscovery) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 62
   at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 25

**Comment by ErikEJ** [comment]
Thanks for reporting, I have switched to a new (and better) method for result set discovery. 

I will investagate your repro.

You can switch back to the "old" method as a workaround via Tools/Options in Visual Studio.

**Comment by werwin81** [comment]
Thanks for your quick reply. 
I set the option "Use sp_describe_first_result_set only" to True. 
Now it works again.

**Comment by ErikEJ** [comment]
Fixed in latest daily build, please let me know if that solves the issue (not using any workarounds)
