### ISSUE TITLE
Unexpected error message

### ISSUE THREAD

**Issue by TanguyPa** [ErikEJ/EFCorePowerTools#1386]
I created a new project in .NET 5 in which I generated the model of an existing stored procedure.
At the end of the import with reverse engineering I have an error message that appears (see details below). What is weird is that the generated code is correct and that I already imported this procedure in another project without getting an error message

The error message should not appear since the code is correct

### Steps to reproduce
Example of the skeleton code of the stored procedure (with the same
CREATE PROCEDURE [dbo].[MyStoredProcedure]	
	@id uniqueidentifier,
	@customData	nvarchar(255),
	@customData2	varchar(3),
	@filestream		varbinary(max),
	@stream_id		uniqueidentifier out
	WITH EXECUTE AS OWNER
AS
 --....
END

### Further technical details

Unable to get result set shape for PROCEDURE 'MyStoredProcedure'
Microsoft.Data.SqlClient.SqlException (0x80131904): La conversion implicite du type de données nvarchar en varbinary(max) n'est pas autorisée. Utilisez la fonction CONVERT pour exécuter cette requête.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetAllResultSets(SqlConnection connection, Routine module, Boolean singleResult) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 90
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetResultElementLists(SqlConnection connection, Routine module, Boolean multipleResults, Boolean useLegacyResultSetDiscovery) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 62
   at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 25
ClientConnectionId:2a4cc6f1-a79f-4c17-ade7-676f28e3a4af

C# generated code
```csharp
public virtual async Task<List<MyStoredProcedure>> MyStoredProcedure(Guid? id, string customData, string customData2, byte[] filestream, OutputParameter<Guid?> stream_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
{
	var parameterstream_id = new SqlParameter
	{
		ParameterName = "stream_id",
		Direction = System.Data.ParameterDirection.InputOutput,
		Value = stream_id?._value ?? Convert.DBNull,
		SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
	};
	var parameterreturnValue = new SqlParameter
	{
		ParameterName = "returnValue",
		Direction = System.Data.ParameterDirection.Output,
		SqlDbType = System.Data.SqlDbType.Int,
	};

	var sqlParameters = new []
	{
		new SqlParameter
		{
			ParameterName = "id",
			Value = id ?? Convert.DBNull,
			SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
		},
		new SqlParameter
		{
			ParameterName = "customData",
			Size = 510,
			Value = customData ?? Convert.DBNull,
			SqlDbType = System.Data.SqlDbType.NVarChar,
		},
		new SqlParameter
		{
			ParameterName = "customData2",
			Size = 3,
			Value = customData2 ?? Convert.DBNull,
			SqlDbType = System.Data.SqlDbType.VarChar,
		},
		new SqlParameter
		{
			ParameterName = "filestream",
			Size = -1,
			Value = filestream ?? Convert.DBNull,
			SqlDbType = System.Data.SqlDbType.VarBinary,
		},
		parameterstream_id,
		parameterreturnValue,
	};
	var _ = await _context.SqlQueryAsync<MyStoredProcedure>("EXEC @returnValue = [dbo].[MyStoredProcedure] @id, @customData, @customData2, @filestream, @stream_id OUTPUT", sqlParameters, cancellationToken);

	stream_id.SetValue(parameterstream_id.Value);
	returnValue?.SetValue(parameterreturnValue.Value);

	return _;
}
````

EF Core version in use:  5.0.15

Is Handlebars used:  no

EF Core Power Tools version: 2.5.966

Database engine: SQL Server

Visual Studio version: 2019

**Comment by TanguyPa** [comment]
It works, thanks

**Comment by TanguyPa** [comment]
I modified the efpt.config.json file and added "UseLegacyResultSetDiscovery": true for the stored procedure

**Comment by ErikEJ** [comment]
Great!
