### ISSUE TITLE
Unable to install EFCore Power Tools on Visual Studio Enterprise 2022

### ISSUE THREAD

**Issue by ngamanning** [ErikEJ/EFCorePowerTools#1396]
### Steps to reproduce
1) Open Extension menu in Visual Studio 
2) Search for EF Core Power Tool and click Download 
3) Close Visual Studio 
4) On Visual Studio Installer dialog, click Modify

### Further technical details
Installer Error log as below: 
5/17/2022 9:04:49 AM - The extension with ID 'f4c4712c-ceae-4803-8e52-0e2049d5de9f' is not installed to Microsoft Visual Studio Enterprise 2022.
5/17/2022 9:05:00 AM - Blocking processes:
5/17/2022 9:05:00 AM - InstallProgressPage ChangeType: 'SingleTarget' operationCount: '2' Text: 'Modifying Microsoft Visual Studio Enterprise 2022...'
5/17/2022 9:05:00 AM - The following target products have been selected...
5/17/2022 9:05:00 AM - 	Microsoft Visual Studio Enterprise 2022
5/17/2022 9:05:00 AM - 
5/17/2022 9:05:00 AM - Beginning to install extension to Microsoft Visual Studio Enterprise 2022...
5/17/2022 9:05:02 AM - Install Error : System.IO.InvalidDataException: Found invalid data while decoding.
   at System.IO.Compression.InflaterZlib.Inflate(FlushCode flushCode)
   at System.IO.Compression.InflaterZlib.ReadInflateOutput(Byte[] outputBuffer, Int32 offset, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.InflaterZlib.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at MS.Internal.IO.Packaging.CompressStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Zip.ProgressiveCrcCalculatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineInstaller.WriteFilesToInstallDirectory(InstallableExtensionImpl extension, String installPath, ZipPackage vsixPackage, IDictionary`2 extensionsInstalledSoFar, AsyncOperation asyncOp, IProgress`1 progress) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\ExtensionEngineInstaller.cs:line 127
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.PerformLegacyInstall(InstallableExtensionImpl extension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Boolean isPackComponent, Version targetedVsVersion, IInstalledExtension& newExtension) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:line 360
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:line 1063
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:line 265
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:line 399
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:line 894

Visual Studio version: e.g. Visual Studio Enterprise 2022

**Comment by ErikEJ** [comment]
Sounds like the download is corrupted. Try to download from MarketPlace perhaps?

**Comment by ErikEJ** [comment]
Ping?
