### ISSUE TITLE
Stored procedure return parameter exception in SqlServer 2012 (11)

### ISSUE THREAD

**Issue by Dimigergo** [ErikEJ/EFCorePowerTools#1401]
I have this repo:
[EFCoreSPReturn.zip](https://github.com/ErikEJ/EFCorePowerTools/files/8761585/EFCoreSPReturn.zip)

When I generate the code in SqlServer 2019 (15.0.2000) the stored procedure return class property is ok:
![error1](https://user-images.githubusercontent.com/11498949/170006391-6e4285ea-86cd-4730-802d-96facd7dc762.png)

But if I generate the same code with the same database on SqlServer 2012 (11.0.6251.0) the result class is empty with an exception:
![error2](https://user-images.githubusercontent.com/11498949/170008988-ad007caa-7a81-4398-903e-972293a4daf4.png)

```
Unable to get result set shape for PROCEDURE 'dbo.spInsAlarms'
Microsoft.Data.SqlClient.SqlException (0x80131904): Operand type clash: datetime2 is incompatible with int
The data for table-valued parameter "@alarms" doesn't conform to the table type of the parameter.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetAllResultSets(SqlConnection connection, Routine module, Boolean singleResult) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 95
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetResultElementLists(SqlConnection connection, Routine module, Boolean multipleResults, Boolean useLegacyResultSetDiscovery) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 62
   at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 25
ClientConnectionId:18469abe-cb2f-47e3-bfeb-6408ff8a6d09
Error Number:206,State:2,Class:16
```

In the sql file the type contained the datetime property which is used in the stored procedure, but the procedure works well with EF Net Framework for years.
```
create type TInsAlarms as table(
  AlState int null,
  UgId int null,
  FacId int null,
  DevId int null,
  ChId int null,
  ResId int null,
  ResDateCreate datetime2(7) null,
  ResLat float(53) null,
  ResLon float(53) null
);
```
```
declare @alarmsLocal TInsAlarms;
insert into @alarmsLocal (AlState, UgId, FacId, DevId, ChId, ResId, ResDateCreate, ResLat, ResLon)
select AlState, UgId, FacId, DevId, ChId, ResId, ResDateCreate, ResLat, ResLon from @alarms;
```

**Comment by ErikEJ** [comment]
Have you tried to enable legacy discovery for that particular sproc?

**Comment by Dimigergo** [comment]
Sorry, I don't know what is it, and can't find anything related in google. :( Please help!

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by Dimigergo** [comment]
Thanks, It is perfect, with no error!
