### ISSUE TITLE
EFPT - "Compare DB Context to Database" - throws an error - related to "Connection Strings"

### ISSUE THREAD

**Issue by Snappee** [ErikEJ/EFCorePowerTools#1416]
Describe what is not working as expected.

Just select the menu choice, select the database/DBO and then it hoses with an error at the bottom of  VS 2022

### Provide steps to reproduce

See above

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)

EF Core 6

- Is Handlebars used: no/yes

NO

- Is .dacpac used: no/yes

NO

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

2.5.1000

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

SQL Server, 2019 Express (happens with the Developer's Edition as well)

- Visual Studio version: (e.g. Visual Studio 2022)

2022 Professional - 17.2.3

**Comment by Snappee** [comment]
<img width="360" alt="2022-06-05_15-04-01" src="https://user-images.githubusercontent.com/9368303/172066568-2cab1a87-de50-4e1e-abe4-2820f9f22787.png">

**Comment by ErikEJ** [comment]
Have you tried the latest daily build?

**Comment by Snappee** [comment]
From GIT, the latest is shown as 2.5.1000 - which is what I have (from yesterday I believe).  Did you update it and not update the REV?

**Comment by ErikEJ** [comment]
Go to the Output window and find the extensions pane and share the error message.

**Comment by Snappee** [comment]
Here yah go - have never used that window before!  Thanks:

System.InvalidOperationException: Error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at STAIDBSupport.Database.MarketManagerContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in C:\DEVL\ReoGrid\STAIDatabaseSupport\Database\MarketManagerContext.cs:line 43
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Modelling.EfCoreCompareBuilder.GetCompareResult(String outputPath, String startupOutputPath, String connectionString, String dbContexts) in C:\Code\EFCorePowerTools\src\GUI\efpt50.core\EFCoreCompareBuilder.cs:line 49
   at Modelling.EfCoreCompareBuilder.GenerateSchemaCompareResult(String outputPath, String startupOutputPath, String connectionString, String dbContexts) in C:\Code\EFCorePowerTools\src\GUI\efpt50.core\EFCoreCompareBuilder.cs:line 28
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 33

   at async Task<IEnumerable<CompareLogModel>> EFCorePowerTools.Handlers.Compare.CompareHandler.GetComparisonResultAsync(string outputPath, Project project, DatabaseConnectionModel connection, string[] contextNames)
   at async Task EFCorePowerTools.Handlers.Compare.CompareHandler.HandleComparisonAsync(string outputPath, Project project)

**Comment by ErikEJ** [comment]
Somethin is broken here 8as the error message states) : C:\DEVL\ReoGrid\STAIDatabaseSupport\Database\MarketManagerContext.cs:line 43

**Comment by Snappee** [comment]
Just ran it on a newly created project - where I did a 'Reverse Engineer' on an existing DB.  The context was created by EFPT:

System.InvalidOperationException: Error:
System.ArgumentException: You must provide at least one DbContext instance. (Parameter 'dbContexts')
   at EfSchemaCompare.CompareEfSql.CompareEfWithDb(String configOrConnectionString, DbContext[] dbContexts)
   at Modelling.EfCoreCompareBuilder.GetCompareResult(String outputPath, String startupOutputPath, String connectionString, String dbContexts) in C:\Code\EFCorePowerTools\src\GUI\efpt50.core\EFCoreCompareBuilder.cs:line 59
   at Modelling.EfCoreCompareBuilder.GenerateSchemaCompareResult(String outputPath, String startupOutputPath, String connectionString, String dbContexts) in C:\Code\EFCorePowerTools\src\GUI\efpt50.core\EFCoreCompareBuilder.cs:line 28
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 33

   at async Task<IEnumerable<CompareLogModel>> EFCorePowerTools.Handlers.Compare.CompareHandler.GetComparisonResultAsync(string outputPath, Project project, DatabaseConnectionModel connection, string[] contextNames)
   at async Task EFCorePowerTools.Handlers.Compare.CompareHandler.HandleComparisonAsync(string outputPath, Project project)

**Comment by ErikEJ** [comment]
I need a repro...

**Comment by Snappee** [comment]
Okay - did a bit more sleuthing:    Couple "usage" issues and things to note (maybe add some better error messages or prompts to let the user know the issue?)

1) When running the 'Reverse Engineer' tool, if one doesn't select the "Include connection string in generated code", then the DBContext will not have a function block of "OnConfiguring()" included in the DBContext.  So, when you later try to run the "Compare DB Context to Database" feature in EFPT, your code has no way to connect to the database (no connection string).

2) If one DID use the "Include connection string in generated code" option, but then modified the DBContext (as recommended by MS Core team) - to use a 'ConfigurationManager' - which usually uses a configuration string in a local Config file (or other means), then once again your compare function doesn't know how to connect to the database.   My DB functions are in a separate assembly from my main code, so there is no connection string in the DB assembly anyplace.

Here is how the connection string is resolved in my DBContext:

    optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["FormulaBlasterDatabase"].ConnectionString);

**Comment by ErikEJ** [comment]
Then you should run the Tool from the main project!!

**Comment by Snappee** [comment]
Hey, not trying to aggravate you . . . just trying to help the product and the next guy who uses it!

1) The only reason I originally posted the issue was because the error message thrown was an "ArgumentException" - which tells me your code wasn't seeing something it expected.  I surely didn't know it was a connection string issue until I dug into it further.   An error message that informed me "Cannot connect to the database - Connection String not found" - would have helped us both not waste time on this post. 

2) Also, you can't run this EFPT function from the calling/main project if it does not contain the DBContext - which it does not, that is stored in my DBSupport assembly.  So, if I tried to run the Tool as you suggested, here is what you get back:

System.InvalidOperationException: Error:
System.ArgumentException: No EF Core DbContext types found in the project
   at Modelling.EfCoreCompareBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt50.core\EFCoreCompareBuilder.cs:line 92
   at Modelling.EfCoreCompareBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean listDbContexts) in C:\Code\EFCorePowerTools\src\GUI\efpt50.core\EFCoreCompareBuilder.cs:line 72
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 31

   at async Task<IEnumerable<string>> EFCorePowerTools.Handlers.Compare.CompareHandler.GetDbContextTypesAsync(string outputPath, Project project)
   at async Task EFCorePowerTools.Handlers.Compare.CompareHandler.HandleComparisonAsync(string outputPath, Project project)

**Comment by ErikEJ** [comment]
Thanks, I have a wiki page dedicated to issues running model discovery. Please have a look and let me know if you have any suggestions for improvements.

**Comment by Snappee** [comment]
Will do . . .  after I get some more work done.  ;)
