### ISSUE TITLE
Unable to get result set shape for PROCEDURE - Invalid object name

### ISSUE THREAD

**Issue by smiljanj** [ErikEJ/EFCorePowerTools#1426]
Hi,
in the latest release I get an error on reverse engineering of stored procedure (it worked ok in previous releases).
Unable to get result set shape for PROCEDURE 'dbo.PaleteSaldoIzracun - see the wiki for solutions.'
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name '#prejemniki'.

I'll copy/paste error and stored procedure bellow.

### Provide steps to reproduce

Unable to get result set shape for PROCEDURE 'dbo.PaleteSaldoIzracun - see the wiki for solutions.'
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name '#prejemniki'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetAllResultSets(SqlConnection connection, Routine module, Boolean singleResult) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 95
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetResultElementLists(SqlConnection connection, Routine module, Boolean multipleResults, Boolean useLegacyResultSetDiscovery) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 62
   at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 25
ClientConnectionId:9516b946-37e3-4f51-ba8e-efc5269c9cc0
Error Number:208,State:0,Class:16

### Provide technical details

- EF Core version in use: 3.2

- Is Handlebars used: no/yes

- Is .dacpac used: no/yes

- EF Core Power Tools version: 2.5.1007.0

- Database engine: SQL Server

- Visual Studio version: VS2019

**Comment by smiljanj** [comment]
[StoredProcedure.txt](https://github.com/ErikEJ/EFCorePowerTools/files/8891112/StoredProcedure.txt)

**Comment by ErikEJ** [comment]
Did you follow the help in the error message? Or is it unclear?

    Unable to get result set shape for PROCEDURE 'dbo.PaleteSaldoIzracun - see the wiki for solutions.'

**Comment by ErikEJ** [comment]
Glad you found the wiki!

I am using a new discovery method in the latest release, and you can opt back to the "old" one like that, yes, with 

    "UseLegacyResultSetDiscovery": true 

in efpt.config.json for the procedure that fails.

**Comment by smiljanj** [comment]
Tried now with "UseLegacyResultSetDiscovery": true , but get a diffrent error:

Unable to get result set shape for PROCEDURE 'dbo.PaleteSaldoIzracun - see the wiki for solutions.'
Microsoft.Data.SqlClient.SqlException (0x80131904): The metadata could not be determined because statement 'INSERT INTO #prejemniki (prejemnik) SELECT @prejemnik' in procedure 'PaleteSaldoIzracun' uses a temp table.

**Comment by ErikEJ** [comment]
Have you ever been able to reverse engineer that procedure?

At any rate, if you know the result set shape you can define it in a partial XxxResult class.

**Comment by smiljanj** [comment]
Yes, in previous version I had no problem.

**Comment by ErikEJ** [comment]
That's odd, because using the option you are using the previous discovery method. 

Was the procedure changed?

**Comment by smiljanj** [comment]
No, procedure hasn't been changed in a year or more.
Is it possible  for me to downgrade Power tools?

**Comment by ErikEJ** [comment]
You can try running this, this it was the tool has been using since day 1 (and is using with the option enabled):

     exec dbo.sp_describe_first_result_set N'[{schema}].[{moduleName}]';

**Comment by smiljanj** [comment]
Last question - is there any chance EF Core power tools update utomatically? I'm sure I didn't update them.

**Comment by ErikEJ** [comment]
Yes automatic Update is the default behaviour in Visual Studio.

**Comment by ErikEJ** [comment]
You can also switch back to the old discovery method for all stored procedure result sets via Tools, Options

**Comment by GearTheWorld** [comment]
I have 2 SP shaped exactly the same but EFPT reports the error on one of them only  Why ?

![image](https://user-images.githubusercontent.com/8614008/190675258-1ecff723-6d91-4702-99f8-767ec6f0000d.png)
