### ISSUE TITLE
Aplicacao nao executa mais com Chave composta

### ISSUE THREAD

**Issue by jrsistemasltda** [ErikEJ/EFCorePowerTools#1439]
has multiple properties with the [Key] attribute. Composite primary keys can only be set using 'HasKey' in 'OnModelCreating

Toda vez que cai no create do model DBCOntext acontece..... ja tentei todo tipo de alteracao no dataanotation!

ASP>NET CORE 6

- EF Core version in use: (e.g. EF Core 6)

- Is Handlebars used: no/yes

- Is .dacpac used: no/yes

- EF Core Power Tools version: 2.5.10

- Database engine: (SQL Server)

- Visual Studio version: ( Visual Studio 2022)

**Comment by ErikEJ** [comment]
I think this is a current limitation of the Key attribute - would be helpful with an example

**Comment by jrsistemasltda** [comment]
System.Exception: Ocorreu um erro ao validar usuário! - The entity type 'ECF_SECAO' has multiple properties with the [Key] attribute. Composite primary keys can only be set using 'HasKey' in 'OnModelCreating'.
   at CFManager_Core.Controllers.ContaController.Login(Login login) in C:\Users\Framework\source\repos\CFManager_Core\CFManager_Core\Controllers\ContaController.cs:line 165
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---

**Comment by ErikEJ** [comment]
Please share some code. Cannot see how this runtime error relates to EF Core Power Tools.

**Comment by ErikEJ** [comment]
I still see only runtime errors. What database and EF Core version  is in use? ( as requested when you create a new issue)

**Comment by ErikEJ** [comment]
And I do not understand Portuguese (,??) Sorry

**Comment by ErikEJ** [comment]
I need a repro database schema and some failing code in order to help.

**Comment by ErikEJ** [comment]
You can email.me privately at ejlskov at Hotmail dot com

**Comment by ErikEJ** [comment]
Confirmed.

**Comment by ErikEJ** [comment]
Please also share a project that reproduces the issue

**Comment by ErikEJ** [comment]
Which EF Core version are you using for reverse engineering and in your project?

**Comment by jrsistemasltda** [comment]
> Qual versão do EF Core você está usando para engenharia reversa e em seu projeto?

6.06

**Comment by ErikEJ** [comment]
Closing as unable to repro and no repro project Shared.
