### ISSUE TITLE
Add dbContext model diagram not wroking when dbcontext inherits from IdentityDbContext<T>

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#15]
_From @hafeefshaik on February 7, 2018 4:57_

Getting below error:

System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.AspNetCore.Identity.EntityFrameworkCore'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c.<FindContextTypes>b__12_5(TypeInfo t)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\SqlCeToolbox\src\GUI\ReverseEngineer20\EFCoreModelBuilder.cs:line 72
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\SqlCeToolbox\src\GUI\ReverseEngineer20\EFCoreModelBuilder.cs:line 32
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\SqlCeToolbox\src\GUI\efpt\Program.cs:line 26

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 52

Add DbContext Model Diagram is not working as expect.

### Steps to reproduce
To reproduce the issue, create a empty .net core project. and add a datacontext which is inherit form IdentityDbContext, then run the migrations, then try to generate the dbcontext diagram.

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

_Copied from original issue: ErikEJ/SqlCeToolbox#628_

**Comment by ErikEJ** [comment]
Does the workaround of adding the AsDgml extension method work? (as describd in the wiki article)

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Could potentailly be fixed by improving how dotnet is called: C:\Code\EntityFramework\src\dotnet-ef\RootCommand.cs

**Comment by ErikEJ** [comment]
_From @hafeefshaik on April 17, 2018 12:13_

@ErikEJ sorry for delay, let me give a try by adding AsDgml()  extension method.

**Comment by ErikEJ** [comment]
_From @DrewBrasher on April 27, 2018 15:17_

I was getting this same error in a .net core console app I use to run EF Core Migrations.  I had to add the NuGet Package:  **Microsoft.AspNetCore.Identity.EntityFrameworkCore** Version="2.0.2"

Then I started getting this error:
`"No EF Core DbContext types found in the project at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations)".`
Adding this NuGet Package fixed that: **ErikEJ.EntityFrameworkCore.DgmlBuilder** Version="1.0.7".

Now using the workaround of adding the AsDgml extension method as describd in the wiki article does create the .dgml file but when I try to open it the dgml viewer gets his error: 
 `'<', hexadecimal value 0x3C, is an invalid attribute character. Line 8, position 30.`

The line with the invalid character is:
`<Node Id = "IdentityUserClaim<string>"`

**Comment by ErikEJ** [comment]
Can you share your dgml file (my email is e j l s k o v @ hotmail.com )

**Comment by ErikEJ** [comment]
_From @DrewBrasher on April 27, 2018 16:43_

I sent the dgml file.  Thanks.

**Comment by ErikEJ** [comment]
Thanks, I will have a look!

**Comment by ErikEJ** [comment]
@DrewBrasher  thanks for reporting this - fixed in version 1.0.9 - I would be very grateful if you could provide a DebugView text file, so I can add a test for this!

**Comment by ErikEJ** [comment]
_From @DrewBrasher on April 30, 2018 16:38_

@ErikEJ I sent you the DebugText file.  I also realized that my original project had some more places with the invalid character that the example I sent you didn't have so I sent a new dgml file as well.
The other lines are like these:
`<Node Id = "ApplicationUser.Claims" Label="Claims (*)" Name="Claims" Category="Navigation Collection" Type="ICollection&lt;IdentityUserClaim&lt;string&gt;&gt;"  Field="&lt;Claims&gt;k__BackingField" Dependent="IdentityUserClaim<string>" Principal="" Inverse="" PropertyAccessMode="PropertyAccessMode.Default" />`
and
`<Link Source="IdentityRoleClaim<string>" Target="IdentityRole" From="IdentityRoleClaim<string>.RoleId" To="IdentityRole.Id" Name="IdentityRoleClaim<string> -> IdentityRole" Annotations="" IsUnique="False" Label="1:*" Category="Foreign Key" />`

**Comment by ErikEJ** [comment]
Thanks!

Did you test the latest version of the NuGet package?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ErikEJ** [comment]
I see know that there are still issues! Working on it…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ErikEJ** [comment]
_From @DrewBrasher on April 30, 2018 17:18_

Updated to version 1.0.10.  Works great now thank you!

**Comment by light-traveller** [comment]
I am getting this error in a .Net Core 2.1 **class library** project using the follwoing:
* VS 2017 (15.8.3)
* EF Core 2.1.1
* SQL Server 2016 (13.0.1601.5)

System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.AspNetCore.Identity.EntityFrameworkCore'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c.<FindContextTypes>b__12_5(TypeInfo t)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 73
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 34
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44



Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 49

**Comment by martinspasovski** [comment]
Tried also with AddDgml, 

#177 same as the one I opened.

Tried in separate project - same result.

**Comment by ErikEJ** [comment]
@martinspasovski  Did you actually call the AsDgml method from your code?

**Comment by ErikEJ** [comment]
Probably fixed by #50

**Comment by martinspasovski** [comment]
Sorry for late reply, I did try .AsDgml

**Comment by ErikEJ** [comment]
This should finally be fixed now (latest daily build) Thank you for your patience!
