### ISSUE TITLE
Visual studio error while opening reverse engineering tool

### ISSUE THREAD

**Issue by mbharodia** [ErikEJ/EFCorePowerTools#153]
Upgraded to version 1.0.721 using VS 2017 Extensions and Updates window. I have enterprise version of VS and Windows 10 professional version 1803.

After the upgrade reverse engineering tool failed to launch. The following is a list of errors recorded on Output window of VS.

System.Windows.Markup.XamlParseException: Could not load file or assembly 'System.Windows.Interactivity, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Interactivity, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(BamlAssembly bamlAssembly)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(BamlType bamlType)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetProperty(Int16 propertyId, XamlType parentType)
   at System.Windows.Baml2006.Baml2006Reader.Process_PropertyArrayStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at EFCorePowerTools.Dialogs.PickServerDatabaseDialog.InitializeComponent() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Dialogs\PickServerDatabaseDialog.xaml:line 1
   at EFCorePowerTools.Dialogs.PickServerDatabaseDialog..ctor(ITelemetryAccess telemetryAccess, IPickServerDatabaseViewModel viewModel) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Dialogs\PickServerDatabaseDialog.xaml.cs:line 40
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at EFCorePowerTools.EFCorePowerToolsPackage.GetView[TView]() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\EFCorePowerToolsPackage.cs:line 321
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 50

I appreciate any help to resolve this issue.

Thanks a lot in advance for your help!

**Comment by ErikEJ** [comment]
Which VS version? @Herdo  ??

**Comment by ErikEJ** [comment]
Sounds like a possible approach

**Comment by mbharodia** [comment]
VS version is 2017 Enterprise 15.9.4. I am working on a class library project; I am not sure whether it is a good idea to add NuGet package for XAML/WFP

**Comment by ErikEJ** [comment]
No, we are considering using it in EF Core Powertools, not in your project

**Comment by ErikEJ** [comment]
Would adding the Blend SDK be a temporary workaround, @Herdo ?

**Comment by Herdo** [comment]
@mbharodia Do you have Blend installed?
@ErikEJ I think this _should_ be the permanent solution, as something seems to be messed up with the packaging of that DLL. Could you check if it's included in the latest version of the extension?

**Comment by ErikEJ** [comment]
So System.Windows.Interactivity.dll should be included in the VSIX package?

**Comment by Herdo** [comment]
Yeah, I expected it to be included all the time 😅 
But it looks like it isn't? So the person who installs the package seems to require Blend, not only the person compiling.
With the NuGet package added, it should be fine for the developer and consumer, even without Blend installed (hopefully).

**Comment by ErikEJ** [comment]
I will make sure it gets included!

**Comment by ErikEJ** [comment]
It is included in the latest daily !

**Comment by ErikEJ** [comment]
(You can download and unzip to check)

**Comment by Herdo** [comment]
Looking good.
We probably should open a new issue to replace the reference with the linked article, if including the DLL solves the issue.

**Comment by mbharodia** [comment]
No. I don’t have.

**Comment by ErikEJ** [comment]
Let's keep this open, the best fix seems to be to use the new Nuget package.

**Comment by mbharodia** [comment]
I installed the latest daily build and received the following errors.

System.Windows.Markup.XamlParseException: Could not load file or assembly 'System.Windows.Interactivity, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Interactivity, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(BamlAssembly bamlAssembly)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(BamlType bamlType)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetProperty(Int16 propertyId, XamlType parentType)
   at System.Windows.Baml2006.Baml2006Reader.Process_PropertyArrayStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at EFCorePowerTools.Dialogs.PickServerDatabaseDialog.InitializeComponent() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Dialogs\PickServerDatabaseDialog.xaml:line 1
   at EFCorePowerTools.Dialogs.PickServerDatabaseDialog..ctor(ITelemetryAccess telemetryAccess, IPickServerDatabaseViewModel viewModel) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Dialogs\PickServerDatabaseDialog.xaml.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at EFCorePowerTools.EFCorePowerToolsPackage.GetView[TView]() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\EFCorePowerToolsPackage.cs:line 321
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 50

Thanks.

**Comment by ErikEJ** [comment]
Which .net Framework version for you have installed?

**Comment by mbharodia** [comment]
I have .NET Framework version 4.7.

**Comment by ErikEJ** [comment]
Please try to upgrade to 4.7.1 or newer

**Comment by mbharodia** [comment]
Installed .Net framework 4.7.2 but no luck

System.Windows.Markup.XamlParseException: Could not load file or assembly 'System.Windows.Interactivity, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Interactivity, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(BamlAssembly bamlAssembly)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(BamlType bamlType)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetProperty(Int16 propertyId, XamlType parentType)
   at System.Windows.Baml2006.Baml2006Reader.Process_PropertyArrayStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at EFCorePowerTools.Dialogs.PickServerDatabaseDialog.InitializeComponent() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Dialogs\PickServerDatabaseDialog.xaml:line 1
   at EFCorePowerTools.Dialogs.PickServerDatabaseDialog..ctor(ITelemetryAccess telemetryAccess, IPickServerDatabaseViewModel viewModel) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Dialogs\PickServerDatabaseDialog.xaml.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at EFCorePowerTools.EFCorePowerToolsPackage.GetView[TView]() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\EFCorePowerToolsPackage.cs:line 321
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 50

**Comment by ErikEJ** [comment]
Could you try on another PC?

**Comment by ErikEJ** [comment]
Just made another attempt at a fix

**Comment by mbharodia** [comment]
Installed daily latest build today on two different machines; no luck; I received the same "could not load file" error both times

**Comment by Herdo** [comment]
I'm wondering why it's not working.
Did you switch it out with the NuGet package already?

If not, I can have a look after my vacation.

**Comment by ErikEJ** [comment]
I am not able to reproduce on any of my machines. Are you running non English OS or VS? @Herdo - the issue appears when the new Nuget package gets installed...

**Comment by mbharodia** [comment]
I have English version of Visual Studio 2017

**Comment by Herdo** [comment]
@ErikEJ German OS and VS
So the new package is not working?

**Comment by ErikEJ** [comment]
The "new" WPF package causes the issue to appear.

**Comment by ErikEJ** [comment]
@Herdo Hi, could you look into this breaking issue, that prevents publishing of the updated extension?
I am able to repro using current master on one of my colleagues PC, even with the Blend SDK installed. 

If this does not get resolved, I see no other option than to revert the changes to use MVVM.

**Comment by ErikEJ** [comment]
I will try this: https://stackoverflow.com/questions/29362125/visual-studio-extension-could-not-find-a-required-assembly

**Comment by ErikEJ** [comment]
@mbharodia Fixed!

**Comment by Herdo** [comment]
@ErikEJ So there's nothing left for me todo then? 😄 
Some things.... are just strange.

**Comment by ErikEJ** [comment]
No, the fix seems to work - maybe you can pull the latest daily and verify that it also works on your PC?

**Comment by Herdo** [comment]
> I am not using the new NuGet package! 😄

Wait, what? O_o

Well, go for it. I'll do the other two dialogs with the next release.
Got some other stuff on my plate right now, too 👍

**Comment by javierdlg** [comment]
@ErikEJ  I'm also hitting this issue with a VSIX I'm trying to publish. Was the fix really just adding `typeof(System.Windows.Interactivity.Behavior).ToString();` at the end of your initializeAsync package method?
Did you ever find out why? 

This feels like an issue with xaml resource files or maybe even the GAC but I'm not familiar enough with those to really tell.

**Comment by ErikEJ** [comment]
@javierdlg My fix is just based on the linked S.O. answer.

**Comment by javierdlg** [comment]
Thanks Erik. In case anyone else finds this page with the same issue, I was able to fix the issue by making sure VS was using my public key in my project. Turned out that a microbuild package I was using that signs assemblies in DevOps switched the public key used to sign with it's own, causing VS to fail to load my assembly due to mismatched assemblies.
