### ISSUE TITLE
EF Core Power Tools Add dbContext Diagram Error

### ISSUE THREAD

**Issue by StevenMurphy809** [ErikEJ/EFCorePowerTools#1558]
I am receiving the following error when I attempt to add a dbContext Diagram in EF Core Power Tools

- EF Core version in use: 5.0.17

- EF Core Power Tools version: 2.5.1145.0

- Database engine: SQL Server

- Visual Studio version: (e.g. Visual Studio 2022)

   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)
System.InvalidOperationException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Hosting.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.<get_Signature>g__LazyCreateSignature|24_0()
   at System.Reflection.RuntimeMethodInfo.get_ReturnType()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.IsFactory[TReturn](MethodInfo factory)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveFactory[T](Assembly assembly, String name)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveHostBuilderFactory[THostBuilder](Assembly assembly)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveServiceProviderFactory(Assembly assembly)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.Create(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at Modelling.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 88
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 35
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 56

   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)

**Comment by ErikEJ** [comment]
have you looked at the tips in the [wiki](https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model#challenges) ?

**Comment by ErikEJ** [comment]
Ping?
