### ISSUE TITLE
Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=2.2.0.0

### ISSUE THREAD

**Issue by asarapas** [ErikEJ/EFCorePowerTools#161]
Getting error:
`
System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Hosting.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.AspNetCore.Hosting.Abstractions'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.get_ReturnType()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderFactory.WebHostFactoryResolver.ResolveWebHostBuilderFactory[TWebhost,TWebhostBuilder](Assembly assembly)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderFactory.WebHostFactoryResolver.ResolveWebHostFactory[TWebhost,TWebhostBuilder](Assembly assembly)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromBuildWebHost(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.Create(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 73
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 34
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44
`
### Steps to reproduce
Create new ASP.Net core application
Add constructor with no parameters  to the ApplicationDbContext
Override OnConfiguring and provide connection string
Run ContextMenu->Add DbContext Model Diagram

### Further technical details
EF Core Power Tools version: 2.2.2.0

Database engine: SQL Server

Visual Studio version: 2017 15.9.4

**Comment by ErikEJ** [comment]
Workarounds: Use the DgmlBulder nuget package or move your DbContext to a seperate .NET Core class library

**Comment by BlackFenix2** [comment]
Ditto, i trying installing the dgmlbuilder package and i keep getting Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=2.2.0.0 exception

![image](https://user-images.githubusercontent.com/15244006/51068169-4c682380-15e8-11e9-9928-8d10b7a5dbe7.png)

**Comment by ErikEJ** [comment]
I Will update the dgmlbuilder package for 2.2

**Comment by ErikEJ** [comment]
@BlackFenix2 The DGML Builder is for generation of the DGML diagram, not for getting Migration status. You issue are probably more related to #15 -  suggest you move your DbContext to a seperate .NET Core class library

**Comment by BlackFenix2** [comment]
@ErikEJ I tried moving my DbContext to a different assembly, and not i get this error:

`Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'DataContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728 ---> System.MissingMethodException: No parameterless constructor defined for this object.`

**Comment by ErikEJ** [comment]
Closing as duplicate
