### ISSUE TITLE
Error trying to use Reverse Engineer

### ISSUE THREAD

**Issue by bgraham123** [ErikEJ/EFCorePowerTools#1644]
When we try to run Reverse Engineer, it does not proceed past the initial step of choosing database connection.  We get the following error in the extensions console: 
`System.IO.IOException: The process cannot access the file 'C:\Users\blong\AppData\Local\Temp\efreveng6.2.5.1260\Microsoft.EntityFrameworkCore.SqlServer.dll' because it is being used by another process.
   at void System.IO.__Error.WinIOError(int errorCode, string maybeFullPath)
   at void System.IO.FileStream.Init(string path, FileMode mode, FileAccess access, int rights, bool useRights, FileShare share, int bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, string msgPath, bool bFromProxy, bool useLongPath, bool checkHost)
   at new System.IO.FileStream(string path, FileMode mode, FileAccess access, FileShare share)
   at void System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, string destinationFileName, bool overwrite)
   at void EFCorePowerTools.Extensions.ZipArchiveExtensions.ExtractToDirectory(ZipArchive archive, string destinationDirectoryName, bool overwrite)
   at string EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.DropNetCoreFiles()
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas, bool mergeDacpacs)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)`

If we try to run Reverse Engineer a second time, we see the following error: 

`System.InvalidOperationException: Table list error: 
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'RevEng.Core.60, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'RevEng.Core.60, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at EfReveng.Program.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at EfReveng.Program.Main(String[] args)
   at EfReveng.Program.<Main>(String[] args)
   at List<TableModel> EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(string output)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas, bool mergeDacpacs)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)`

This issue is happening on multiple machines and seems to have started for us sometime between 12/20/22 - 1/3/23.  We have tried updating Visual Studio, reinstalling the extension, and deleting %temp%\efreveng*.* folders to no avail.

- EF Core version in use: EF 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1260

- Database engine: Mssql

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Most likely a virus scanner interfering with the unzip process.

**Comment by ErikEJ** [comment]
The unzip mechanism could have some retries.

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by bgraham123** [comment]
Looks like that worked, thank you

**Comment by ErikEJ** [comment]
Great, thanks for the heads up.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
