### ISSUE TITLE
Error reverse engineering using Handlebars templates

### ISSUE THREAD

**Issue by ppi-gzhou** [ErikEJ/EFCorePowerTools#172]
When trying to reverse engineer using Handlebars templates, the output shows
`System.IO.FileNotFoundException: Could not find file '[project root]\CodeTemplates\CSharpDbContext\Partials\DbConstructor.hbs'.`

### Steps to reproduce
Using Reverse Engineer tool:
- What to generate: EntityTypes & DbContext
- Check "Customize code using Handlebars templates (preview)"

### Further technical details
EF Core Power Tools version: 2.2.4

Database engine: SQL Server

Visual Studio version: 15.9.5

Stack trace:
```
System.IO.FileNotFoundException: Could not find file '[project root]\CodeTemplates\CSharpDbContext\Partials\DbConstructor.hbs'.
File name: [project root]\CodeTemplates\CSharpDbContext\Partials\DbConstructor.hbs'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at EntityFrameworkCore.Scaffolding.Handlebars.Internal.FileSystemFileService.RetrieveFileContents(String directoryName, String fileName)
   at ReverseEngineer20.ReverseEngineer.CustomTemplateFileService.RetrieveTemplateFileContents(String relativeDirectory, String fileName, String altRelativeDirectory)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsDbContextTemplateService.GetPartialTemplates()
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsTemplateService.RegisterPartialTemplates()
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpModelGenerator.GenerateModel(IModel model, String namespace, String contextDir, String contextName, String connectionString, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 193
```

**Comment by ErikEJ** [comment]
Try to rename your CodeTemplates folder

**Comment by ErikEJ** [comment]
Ping?

**Comment by ppi-gzhou** [comment]
It turns out I was completely missing the `DbConstructor.hbs` file in that folder. I found it here:
https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpDbContext/Partials/DbConstructor.hbs

After adding that file to the `CodeTemplates\CSharpDbContext\Partials\` folder it seems to have fixed this issue. I didn't need the file before so I'm not sure what has changed with the latest version of your utility.

**Comment by ErikEJ** [comment]
Did you try a folder rename?

**Comment by ppi-gzhou** [comment]
No, which folder would I rename and to what?

**Comment by ppi-gzhou** [comment]
OK, I tried that and it worked. Does that mean I don't even need the CodeTemplates in my project?

**Comment by ErikEJ** [comment]
Thanks, yes, if you use Handlebars you need the codetemplates

**Comment by ErikEJ** [comment]
(I have confirmed the workaround fixes the issue)
