### ISSUE TITLE
Update to EF Core 2.2.2 in Modelling etc

### ISSUE THREAD

**Issue by vinayvhub** [ErikEJ/EFCorePowerTools#186]
I used the option "Reverse engineer" to build DBContext and models into my .NET Core 2.2 Console application like you have showed in the demo. That part worked. After that I tried to add that colorful DbContext model diagram to my project then I go the below error in my output window.
Below is the error.

> System.ArgumentException: Error:
System.ArgumentException: No EF Core DbContext types found in the project
at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 76
at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 34
at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44
Parameter name: processResult
at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 49

### Steps to reproduce
Created a new .NET Core 2.2 Console application.
Added EF Core SQL Server Package. That will add all the dependencies.
Used "Reverse engineer" option to build DBContext and models into my consoled project. That part worked perfect.
Then used"DBContext model diagram" option. Error.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.2.12.0

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL Server

Visual Studio version: (e.g. Visual Studio 2017 15.7)
15.9.7

**Comment by ErikEJ** [comment]
Please share or show me your csproj file

**Comment by vinayvhub** [comment]
Here is the csproject file code. Its a console application, .NET Core 2.2 project.

> <Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.2" />
  </ItemGroup>

</Project>

**Comment by ErikEJ** [comment]
Fixed in latest daily build
