### ISSUE TITLE
Will Not Display Context Diagram

### ISSUE THREAD

**Issue by hardoverton** [ErikEJ/EFCorePowerTools#1862]
### Provide steps to reproduce
select Add DbContext Diagram.

Please include a **complete** description or project that I can redo/run to reproduce the issue.
Solution is a WPF app (MuiltiDB) to drive testing multiple databases with identical schemas with EFCore
.NET 6.0
depends on several class libraries:
MultiDB.Data
MultiDB.Model
MultiDB.Services

I would have to provide the entire solution for a proper reproduction.  but maybe we won't need it

When I select Add DbContext Diagram, it seems to run but then reports an error. It can't find Presentation Framework.

here is the extensions output:
System.InvalidOperationException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Reflection.RuntimeAssembly.get_EntryPoint()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveFactory[T](Assembly assembly, String name)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveWebHostFactory[TWebHost](Assembly assembly)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveServiceProviderFactory(Assembly assembly, Nullable`1 waitTimeout)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.Create(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at Modelling.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 88
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 35
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 56

   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)

Feels wrong to add the Windows.Desktop.App.WPF to the Multidb.Data library.
There is obviously something not configured correctly.

Any idea?

### Provide technical details

Data is separate project
- EF Core version in use: (e.g. EF Core 6.0.19)

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1514

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by hardoverton** [comment]
Please ignore this and close it. problem is solved by setting the data project as startup

**Comment by ErikEJ** [comment]
Great you got it working!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
