### ISSUE TITLE
Legacy support for VS 2019 and EF Core 3.1?

### ISSUE THREAD

**Issue by mhall1-new2** [ErikEJ/EFCorePowerTools#1948]
I'm trying to get EFPT working with VS 2019 by building the last commit before support was removed (626a7a53b744deb5d6575fb82c4f265ebb9af0e4).

I'm wondering if you can help me out? Here's what I'm doing:

1. Build the project
2. Grab the VSIX from the bin folder
3. Install it on the machine that has VS2019 (and only 2019)

When I try to use it by clicking "Reverse Engineer" in one of my own projects, I get the following error:

`System.ArgumentNullException: Value cannot be null.
Parameter name: provider
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at EFCorePowerTools.EFCorePowerToolsPackage.GetView[TView]() in C:\DEV_GIT\PAI\EFCorePowerTools\src\GUI\EFCorePowerTools\EFCorePowerToolsPackage.cs:line 96
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ChooseDataBaseConnectionAsync>d__11.MoveNext() in C:\DEV_GIT\PAI\EFCorePowerTools\src\GUI\Shared\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 349
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__8.MoveNext() in C:\DEV_GIT\PAI\EFCorePowerTools\src\GUI\Shared\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 201
`

Does this commit work in your environment? Are there any installers or other dependencies I need to install?

**Comment by ErikEJ** [comment]
@mhall1-new2 In the tools folder in the repo you will find an unsupported installer that works with VS 2019.  I do not  support building older commits, you should be using VS 2022 and use the latest build for support.
