### ISSUE TITLE
[Question] Always include all objects with Exclusions

### ISSUE THREAD

**Issue by amura11** [ErikEJ/EFCorePowerTools#1961]
When using the `Always include all objects` option is it possible to exclude specific existing tables?

I tried using essentially this config:

```
{
   "CodeGenerationMode": 2,
   "ContextClassName": "MyContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": "Models",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "My.Project",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": null,
   "Tables": [
   ...other tables...
         {
         "Name": "[abc].[TableToExclude]",
        "ObjectType": 0,
        "Exclude": true
      },
   ...more tables...
   ],
   "UncountableWords": null,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": true,
   "UseDateOnlyTimeOnly": false,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": false,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoDefaultConstructor": false,
   "UseNoObjectFilter": true,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UseSchemaFolders": true,
   "UseSchemaNamespaces": true,
   "UseSpatial": false,
   "UseT4": false
}
```

And this still tried to generate `[abc].[TableToExclude]`. The use case for this I want new objects to be generated but I want to exclude this specific table because it doesn't seem to be compatible with EFCore and excluding it should be fine.

**Comment by ErikEJ** [comment]
No, it is not possible. What does "not compatible " mean? Can you share the CREATE script for that table?

**Comment by amura11** [comment]
I realize I misspoke when I said not compatible. The table generates the following error:
```
System.InvalidOperationException: The key {'OwnerId', 'MyTableId'} cannot be added to keyless type 'MyTable (Dictionary<string, object>)'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.AddKey(IReadOnlyList`1 properties)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKey(ModelBuilder modelBuilder, DatabaseForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelxyzGenerationOptions xyzOptions, Boolean removeNullableBoolDefaults, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in C:\xyz\Github\EFCorePowerTools\src\GUI\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 476
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath) in C:\xyz\Github\EFCorePowerTools\src\GUI\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:\xyz\Github\EFCorePowerTools\src\GUI\RevEng.Core.60\ReverseEngineerRunner.cs:line 78
```

The table is a key-less table with a bunch of foreign keys and a couple indexes. This is a paired down version of the create script:
```
CREATE TABLE [abc].[MyTable] (
    [MyTableId]             BIGINT        CONSTRAINT [DF_MyTable_MyTableId] DEFAULT (NEXT VALUE FOR [abc].[seqMyTableId]) NOT NULL,
    [StatusId]              INT           NOT NULL,
    [OwnerId]               INT           NOT NULL,
    [IsSomething]           BIT           NOT NULL,
    [CreatedOn]             DATETIME2 (0) NOT NULL,
    [ModifiedOn]            DATETIME2 (0) NOT NULL,
    CONSTRAINT [FK_MyTable_OwnerId__OwnerTable_Id] FOREIGN KEY ([OwnerId]) REFERENCES [abc].[OwnerTable] ([Id]),
    CONSTRAINT [FK_MyTable_Status] FOREIGN KEY ([StatusId]) REFERENCES [abc].[Status] ([StatusId]),
) ON [xyz_sch_SomeID] ([OwnerId]);

GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_MyTable__OwnerId_MyTableId_i_StatusId_ModifiedOn]
    ON [abc].[Request]
    (
        [OwnerId] ASC
      , [MyTableId] ASC
    )
    INCLUDE([StatusId], [ModifiedOn])
    ON [xyz_sch_SomeID] ([OwnerId]);
GO

ALTER TABLE [abc].[MyTable] SET (LOCK_ESCALATION = AUTO);

GO
```

**Comment by ErikEJ** [comment]
@amura11 Can you not add a primary key to it?

**Comment by ErikEJ** [comment]
@amura11 Exclusions are not supported by the VS extension

**Comment by ErikEJ** [comment]
@amura11 You can try this workaround: https://github.com/dotnet/efcore/issues/19918#issuecomment-1711775314

**Comment by amura11** [comment]
Thanks for the help and the great library! 

I can't add a key to the table as it's an existing database. 

However, that workaround looks promising but I don't follow where I would put that call. The reverse engineering doesn't result in any code being output. Where would I added that `HasKey`?

**Comment by ErikEJ** [comment]
Ah, I think there is no option other than unchecking the table each time. You could write a test to compare the number of dbsets with the number of objects in your database then.
