### ISSUE TITLE
Upgrade to 2.2.4 EF Core packages for .NET FW

### ISSUE THREAD

**Issue by GitHubAre** [ErikEJ/EFCorePowerTools#202]
Hello,

I have installed Visual Studio 2019 with EF Core and packages that my projects are referencing (latest ones) are 2.2.4 version.

The error I get while trying to generate the diagram is:
```
System.ArgumentException: Error:
System.ArgumentException: No EF Core DbContext types found in the project
   at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 76
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 34
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44
```

I have browsed other issues on GitHub and similar issue was always solved when you upgraded the tooling used in EFCorePowerTools extension.

### Steps to reproduce

1. Set project holding DbContext as startup
1. Choose "Add DbContext Model Diagram"
1. Error is thrown as above

### Further technical details
EF Core Power Tools version: I have used the official marketplace package as well as daily build package which is 2.2.35 (published date 4/12/2019)

Database engine: SQL Server (local db)

Visual Studio 16.0.1

**Comment by ErikEJ** [comment]
In the meantime you can use EF Core 2.2.3

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by GitHubAre** [comment]
Thank you!
I imagine its annoying to keep up with so frequent version releases.

Using `Add DbContext Model Diagram` by right clicking the project doesnt work with this error:
```
System.ArgumentException: Error:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Sws.ConfigurationProvider.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   --- End of inner exception stack trace ---
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParametersNoCopy()
   at System.Reflection.RuntimePropertyInfo.GetIndexParametersNoCopy()
   at System.Reflection.RuntimePropertyInfo.GetIndexParameters()
   at Microsoft.EntityFrameworkCore.Internal.DbSetFinder.<>c.<FindSets>b__2_0(PropertyInfo p)
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.LazyToArray()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbSetInitializer.InitializeSets(DbContext context)
   at Sws.ConfigurationProvider.Persistence.DbContextBase..ctor()
   at Sws.ConfigurationProvider.Persistence.Azure.AzureDbContext..ctor() in D:\tips\toolbox\Common\03_csharp\Sws.ConfigurationProvider\Sws.ConfigurationProvider.Persistence\Azure\AzureDbContext.cs:line 12
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 40
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 49
```

I plan to use two or more DbContexts in the same project and I dont know how would EfCorePowerTools cope with it therefore I have added explicit DbContext diagram method into the test project which works just fine:
```
    public class CreateDbContextDiagram
    {
        [Fact]
        public void AzureDbContextDiagram()
        {
            using (var myContext = new AzureDbContext())
            {
                var path = DotNet.GetExecutingDirectory() + "..\\..\\..";

                System.IO.File.WriteAllText(Path.Combine(path, "AzureDbContextDiagram.dgml"),
                    myContext.AsDgml(),
                    System.Text.Encoding.UTF8);
            }
        }
    }
```

**Comment by ErikEJ** [comment]
Is this a NET Core or NET Framework project? (I have not updated the .NET Framework bits yet)

**Comment by ErikEJ** [comment]
Power Tools cope fine with multiple DBContexts in same project, btw

**Comment by ErikEJ** [comment]
Power Tools cope fine with multiple DBContexts in same project, btw

**Comment by GitHubAre** [comment]
It is .net core library.
This is how .csproj looks like:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ErikEJ.EntityFrameworkCore.DgmlBuilder" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sws.ConfigurationProvider.Adapters\Sws.ConfigurationProvider.Adapters.csproj" />
    <ProjectReference Include="..\Sws.ConfigurationProvider.Common\Sws.ConfigurationProvider.Common.csproj" />
    <ProjectReference Include="..\Sws.ConfigurationProvider.Core\Sws.ConfigurationProvider.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Extensions.Logging.Debug">
      <HintPath>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.logging.debug\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Logging.Debug.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
```

While the error states that the .dll is missing, .dll is actually in the output folder of  **DEBUG** build.

**Comment by ErikEJ** [comment]
Ah, you are most likely hit by #50 - can you provide a repro project/solution - I have an idea for a potential fix.

**Comment by GitHubAre** [comment]
I have put the minimal required projects to reproduce the error into [this repo](https://github.com/GitHubAre/EFCorePowerToolsDllNotFound)
I have hardcoded localdb connection string into `AzureDbContext.OnConfiguring()` (probably its not even used in your extension?).

**Comment by ErikEJ** [comment]
Thanks, you are hit by #50 - until that is fixed, I recommend that you place your DbContext and POCO Classes in a seperate project without other dependencies, doing that will enable diagram creation (I was able to do that with your project)

**Comment by GitHubAre** [comment]
Thanks for very quick analysis. Meantime i will stick with AsDgml() coded approach.

**Comment by ErikEJ** [comment]
I believe this is now fixed in the latest daily build. I will install EfCore.Design in your project to make it work.

**Comment by ErikEJ** [comment]
Ping? Did you try the latest daily build?

**Comment by GitHubAre** [comment]
Hello, unfortunately it doesnt (using the user interface).
I have tried it on both projects (the one that I shared with you through repo and the current implementation which is stored in private repo.
Both ended with same error:
```
System.ArgumentException: Error:
System.ArgumentException: No EF Core DbContext types found in the project
   at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 76
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 34
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 49

```
There is one "real db context" in the project, but I have `public abstract class DbContextBase : DbContext` from which I inherit.

**Comment by ErikEJ** [comment]
Which project are you selecting?

**Comment by ErikEJ** [comment]
Hang on, latest daily is 2.2.55, not 2.2.35

**Comment by GitHubAre** [comment]
Sws.ConfigurationProvider.Persistence
I also use it as startup project (I dont know if it is required to set it as startup, but I tend to do so when working with EF projects)

**Comment by GitHubAre** [comment]
Right, I thought that the version of EfCorePowerTools might not be correct, because it hasnt changed since 12.4.
I used the link from github readme page.

**Comment by ErikEJ** [comment]
Works for me using your supplied .zip file and EF Core Power Tools build 2.2.56 - link: http://vsixgallery.com/extensions/f4c4712c-ceae-4803-8e52-0e2049d5de9f/extension.vsix

**Comment by GitHubAre** [comment]
I have uninstalled and installed extension using your link above and when I look into installed extensions in VS i see version 2.2.35..., If I attempt to install it again it says "this extension is already installed to all applicable products".

**Comment by ErikEJ** [comment]
seems like you are not getting the correct download file then - or attempting to install the wrong file

**Comment by GitHubAre** [comment]
I have tried it on different computer and now I am at this error:
```
System.MissingMethodException: Method not found: 'Microsoft.VisualStudio.ProjectSystem.IConfiguredProjectServices Microsoft.VisualStudio.ProjectSystem.ConfiguredProject.get_Services()'.
   at EFCorePowerTools.Extensions.ProjectExtensions.GetCspProperty(Project project, String propertyName)
   at EFCorePowerTools.Handlers.ProcessLauncher.GetOutput(String outputPath, String projectPath, GenerationType generationType, String contextName, String migrationIdentifier, String nameSpace) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ProcessLauncher.cs:line 95
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 62
```

**Comment by ErikEJ** [comment]
Old VS version?

**Comment by GitHubAre** [comment]
No, VS 2019 version 16.0.2

**Comment by ErikEJ** [comment]
OMG - most likely breaking change in VS 2019.. /CC @bricelam

**Comment by ErikEJ** [comment]
Do you have VS 2017 anywhere (that is what I was using for testing) ?

**Comment by GitHubAre** [comment]
yes, at work (but there I had issues updating the extension with latest daily build).
I will try tomorrow with VS 2017 since I havent tried that one yet.

**Comment by ErikEJ** [comment]
Thanks, I will look into the VS 2019 compat issue.

**Comment by ErikEJ** [comment]
The VS 2019 compatibility issue is fixed in the latest daily build

**Comment by GitHubAre** [comment]
I have tried it and it works.
All good now :)

**Comment by ErikEJ** [comment]
Thank you very much for taking time to validate this major change!

**Comment by GitHubAre** [comment]
Welcome
