### ISSUE TITLE
Connection error on DbContext 

### ISSUE THREAD

**Issue by wsyeager** [ErikEJ/EFCorePowerTools#2023]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug
Erik, below, are the three code blocks I'm trying to use to prevent a connection error when trying to do an update. 

Here is the **common** code right before the 3 different blocks: **Controller** 
`[HttpPut]
[Route("ShippingNotification/bolId")]
public async void Put(string bolId, [FromBody] ShippingNotification_Update shippingNotification)
{
    var siteId = bolId.Substring(0, 3);
    var s = shippingNotification;

    await db.BOL_UpdateAsync(bolId, s.Kit, s.Carrier, s.ShipDate);
}`

**DBContextProcedure.cs**
`public virtual async Task<int> BOL_UpdateAsync(string bol, int? Kit, string Carrier, DateTime? ShipDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
{
    var parameterreturnValue = new SqlParameter
    {
        ParameterName = "returnValue",
        Direction = System.Data.ParameterDirection.Output,
        SqlDbType = System.Data.SqlDbType.Int,
    };

    var sqlParameters = new[]
    {
        new SqlParameter
        {
            ParameterName = "bol",
            Size = 15,
            Value = bol ?? Convert.DBNull,
            SqlDbType = System.Data.SqlDbType.VarChar,
        },
        new SqlParameter
        {
            ParameterName = "Kit",
            Value = Kit ?? Convert.DBNull,
            SqlDbType = System.Data.SqlDbType.Int,
        },
        new SqlParameter
        {
            ParameterName = "Carrier",
            Size = 10,
            Value = Carrier ?? Convert.DBNull,
            SqlDbType = System.Data.SqlDbType.VarChar,
        },
        new SqlParameter
        {
            ParameterName = "ShipDate",
            Value = ShipDate ?? Convert.DBNull,
            SqlDbType = System.Data.SqlDbType.DateTime,
        },
        parameterreturnValue,
    };
`
**Your generated code:**
`****var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [3PL].[BOL_Update] @bol, @Kit, @Carrier, @ShipDate", sqlParameters, cancellationToken);
returnValue?.SetValue(parameterreturnValue.Value);
return _;****`

**Error**:
System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=A task was canceled.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenInternalAsync>d__70.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenInternalAsync>d__70.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__66.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteNonQueryAsync>d__14.MoveNext()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.<ExecuteSqlRawAsync>d__17.MoveNext()
   at SpiritWMSApiCore2.Models.SIRISContextProcedures.<BOL_UpdateAsync>d__6.MoveNext() in C:\Users\WYeager\source\repos\SpiritWMSApiCore2\Models\SIRISContextProcedures.cs:line 237
   at SpiritWMSApiCore.Controllers.ShippingNotificationController.<Put>d__5.MoveNext() in C:\Users\WYeager\source\repos\SpiritWMSApiCore2\Controllers\ShippingNotificationController.cs:line 63
--------------------------------------------------------------------------------------------------------------------------------------------------

**Code I tried:**
` try
    {
        if (_context.Database.CanConnect() == false)
        {
            _context.Database.OpenConnection();
        }

        **var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [3PL].[BOL_Update] @bol, @Kit, @Carrier, @ShipDate", sqlParameters, cancellationToken);**

        returnValue?.SetValue(parameterreturnValue.Value);

        return _;
    }
    catch (Exception ex)
    {
        throw ex;
    }
}`

**Error:**
System.InvalidOperationException
  HResult=0x80131509
  Message=Invalid operation. The connection is closed.
  Source=SpiritWMSApiCore2
  StackTrace:
   at SpiritWMSApiCore2.Models.SIRISContextProcedures.<BOL_UpdateAsync>d__6.MoveNext() in C:\Users\WYeager\source\repos\SpiritWMSApiCore2\Models\SIRISContextProcedures.cs:line 252
   at SpiritWMSApiCore.Controllers.ShippingNotificationController.<Put>d__5.MoveNext() in C:\Users\WYeager\source\repos\SpiritWMSApiCore2\Controllers\ShippingNotificationController.cs:line 63
----------------------------------------------------------------------------------------------------------------------------------------------

**Code I tried:**
` try
 {
     if (_context.Database.CanConnect() == false)
     {
         _context.Database.OpenConnection();
     }

     **var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [3PL].[BOL_Update] @bol, @Kit, @Carrier, @ShipDate", sqlParameters, cancellationToken);**

     returnValue?.SetValue(parameterreturnValue.Value);

     return _;
 }
 catch (Exception ex)
 {
     throw ex;
 }
 finally
 {
     if (_context.Database.CanConnect() == true)
     {
         _context.Database.CloseConnection();
     }
 }
`
**Error**:
System.ObjectDisposedException
  HResult=0x80131622
  Message=Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'SIRISContext'.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_Database()
   at SpiritWMSApiCore2.Models.SIRISContextProcedures.<BOL_UpdateAsync>d__6.MoveNext() in C:\Users\WYeager\source\repos\SpiritWMSApiCore2\Models\SIRISContextProcedures.cs:line 256
   at SpiritWMSApiCore.Controllers.ShippingNotificationController.<Put>d__5.MoveNext() in C:\Users\WYeager\source\repos\SpiritWMSApiCore2\Controllers\ShippingNotificationController.cs:line 63
----------------------------------------------------------------------------------------------------------------------------------------------

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
- 2.5.1694

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
- 4.8.09037

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
- SQL Server

- EF Core version in use: (e.g. EF Core 7)
- EF Core 8

- Is Handlebars templates used: **no**/yes

- Is T4 templates used: **no**/yes

- Is a SQL Server .dacpac used: **no**/yes

**Comment by wsyeager** [comment]
This sproc is very simple... Here it is:
`UPDATE [3pl].Outbound_Order 
	SET Kit = @kit, scac = @Carrier, ShipDate = @ShipDate
	WHERE bol = @bol AND deleted = 0`

**Comment by ErikEJ** [comment]
You need to provide a simple console app that demonstrates the issue,  I cannot do anything with Random code fragments.

**Comment by wsyeager** [comment]
Erik, attached is the solution at the bottom...

Here is the script for creating the table & data:
[script.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13504579/script.zip)

You just need to execute the "Put" method in the "ShippingNotificationController" within the Controllers folder called "ShippingNotification_Update".
Just select the input variables from the only record I included in the DB table.

This will execute the below method inside the SIRISContextProcedures.cs file:
<img width="1174" alt="image" src="https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/b2d8fd7a-0e3f-4352-b847-81f85696829f">

[SpiritWMSApiCore2.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13503989/SpiritWMSApiCore2.zip)

**Comment by wsyeager** [comment]
Use the data inside the only record in the DB table for input going into the DB. It's failing where the breakpoint is above with the following error:

var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [3PL].[BOL_Update] @bol, @Kit, @Carrier, @ShipDate", sqlParameters, cancellationToken);
returnValue?.SetValue(parameterreturnValue.Value);
return _;

System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=A task was canceled.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenInternalAsync>d__70.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenInternalAsync>d__70.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__66.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteNonQueryAsync>d__14.MoveNext()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.<ExecuteSqlRawAsync>d__17.MoveNext()
   at SpiritWMSApiCore2.Models.SIRISContextProcedures.<BOL_UpdateAsync>d__6.MoveNext() in C:\Users\WYeager\source\repos\SpiritWMSApiCore2\Models\SIRISContextProcedures.cs:line 237
   at SpiritWMSApiCore.Controllers.ShippingNotificationController.<Put>d__5.MoveNext() in C:\Users\WYeager\source\repos\SpiritWMSApiCore2\Controllers\ShippingNotificationController.cs:line 63

**Comment by wsyeager** [comment]
> You need to provide a simple console app that demonstrates the issue, I cannot do anything with Random code fragments.

Erik, please take a look at the last 2 posts as I have provided the necessary items for debugging the issue.

Thx.
