### ISSUE TITLE
Reverse Engineer from SSDT errors when computed column is principal key in a relationship

### ISSUE THREAD

**Issue by cbrianball** [ErikEJ/EFCorePowerTools#210]
Continuation of #208, but I wanted to open a new issue since the fix you provided for that issue did fix the problem I reported on it.

My unique computed column is also the principal key that other tables have a FK to it.

````
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at ReverseEngineer20.SqlServerDacpacDatabaseModelFactory.GetForeignKeys(TSqlTable table, DatabaseModel dbModel)
   at ReverseEngineer20.SqlServerDacpacDatabaseModelFactory.Create(String dacpacPath, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 214
````

Here's the SQL

````
CREATE TABLE [dbo].[Foo]
(	
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[AlternateKey] INT NULL,
	[UniqueId] AS ISNULL(ISNULL(AlternateKey, Id), 0) PERSISTED,
	CONSTRAINT [My_Constraint] UNIQUE(UniqueId),
)

CREATE TABLE [dbo].[Bar]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[FooUniqueId] INT REFERENCES [dbo].[Foo](UniqueId)
)
````

I've updated my prior example project to show this issue.
[EFPowerToolsIssue208.zip](https://github.com/ErikEJ/EFCorePowerTools/files/3114716/EFPowerToolsIssue208.zip)

**Comment by cbrianball** [comment]
I've verified that the latest changes has resolved the issue. Thanks!
