### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object error when customizing file names

### ISSUE THREAD

**Issue by TomBruns** [ErikEJ/EFCorePowerTools#2110]
Thanks for the great tool.

I am trying the generate the POCO cs files and classes with a suffix of DBE (for Data Base Entity)

### Provide steps to reproduce a bug

![Snap4](https://github.com/ErikEJ/EFCorePowerTools/assets/13077238/060c75b9-54eb-4644-87e4-f0ef38d2aa78)

I added this line to the top of: **EntityType.t4**
```  <#@ output extension="DBE.cs" #> ```

I am using these modified T4 templates:
[EFCore.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14003035/EFCore.zip)

Note: If I remove that 1 line then the generation is successful.

### Provide technical details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RevEng.Core.ReverseEngineerScaffolder.AppendSchemaNamespaceToDbcontext(String code, HashSet`1 codeFileNamespaces) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 370
   at RevEng.Core.ReverseEngineerScaffolder.AppendSchemaFoldersAndNamespace(IModel databaseModel, ScaffoldedModel scaffoldedModel, Boolean useSchemaFolders, Boolean useSchemaNamespaces, IEnumerable`1 schemas) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 345
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 506
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
[EFCore.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14003032/EFCore.zip)

   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerRunner.cs:line 86
```

### Context
Using the same templates with this command is successful
```dotnet ef dbcontext scaffold "Data Source=localhost;Initial Catalog=AdventureWorks2022;Integrated Security=True;Trust Server Certificate=True" Microsoft.EntityFrameworkCore.SqlServer --context-dir Contexts --output-dir Models```

### Additional Info

- EF Core Power Tools version: **2.6.78**

- Exact Visual Studio version: **Visual Studio 2022 17.8.4**

- Database engine: **SQL Server**

- EF Core version in use: **EF Core 8**

- Is Handlebars templates used: **no**

- Is T4 templates used: **yes**

- Is a SQL Server .dacpac used: **no**

**Comment by ErikEJ** [comment]
@TomBruns Looks like a bug in the experimental "schema namespaces" feature

**Comment by ErikEJ** [comment]
@TomBruns Try using the renaming feature for the suffix rather than your current approach

**Comment by TomBruns** [comment]
@ErikEJ 
- I am using the standard **OLTP AdventureWorks DB** from here [AdventureWorks sample databases](https://learn.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver16&tabs=ssms)
- With this [efpt.config.json](https://github.com/ErikEJ/EFCorePowerTools/files/14008259/efpt.config.json)

I can push a C# project to github if that would help, but there is not much there at this point.

**Comment by ErikEJ** [comment]
@TomBruns Thanks, that's fine for me in order to investigate

**Comment by ErikEJ** [comment]
As mentioned above, you must use the renaming feature to rename your entities if you also want to use the schema folder experimental features, doing it via the T4 template will not work.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
