### ISSUE TITLE
Login error while opening reverse engineering tool

### ISSUE THREAD

**Issue by sguti** [ErikEJ/EFCorePowerTools#212]
###Description
Login error while using EFCorePowerTool.  Same connection string is working in SSMS.  Also another existing connection string is working in EFCorePowerTool.

Not able to delete existing connection string. 

Error:

System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'xxxx'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at ErikEJ.SqlCeScripting.ServerDBRepository..ctor(String connectionString, Boolean keepSchemaName)
   at ErikEJ.SqlCeToolbox.Helpers.RepositoryHelper.CreateRepository(DatabaseInfo databaseInfo) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Helpers\RepositoryHelper.cs:line 23
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTablesFromRepository(DatabaseInfo dbInfo) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 287
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 111
ClientConnectionId:0b2df8cf-06df-45ba-a93e-52a89707928a
Error Number:18456,State:1,Class:14

### Steps to reproduce
Go to Reverse Engineering tool and select existing connection string and click ok.

### Further technical details
EF Core Power Tools version: 2.2.12.0
Database: Azure SQL PaaS

Visual Studio version: 
Visual Studio 2019 Community

**Comment by ErikEJ** [comment]
Open "Server Explorer" and delete the existing connection. Then recreate one with correct credentials.

**Comment by sguti** [comment]
Thanks a lot. This solved my issue. 👍  I think my issue was very silly. I didn't know I could see those connections in server explorer.
