### ISSUE TITLE
VS2017 (V15.0) installation error "requires a version of the .NET Framework that is not installed."

### ISSUE THREAD

**Issue by rohitnayakmsft** [ErikEJ/EFCorePowerTools#214]
Installation on Win Server 2016 running VS2017 fails with 
4/30/2019 5:02:59 PM - Beginning to install extension to Microsoft Visual Studio Community 2017...
4/30/2019 5:02:59 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'EF Core Power Tools' requires a version of the .NET Framework that is not installed.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.ExtensionRequiresAdditionalOperationForInstall(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, InstallFlags flags, Boolean& performExtensionUpdate)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

### Further technical details
Dot net Versions on the machine
dir /b %windir%\Microsoft.NET\Framework\v*
v1.0.3705
v1.1.4322
v2.0.50727
v3.0
v3.5
v4.0.30319

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres) N/A - never got past install

Visual Studio version: (e.g. Visual Studio 2017 15.7)
Microsoft.VisualStudio.Community
Version : [15.0.27130.0,17.0)
[EFCorePowerTools_InstallLog.txt](https://github.com/ErikEJ/EFCorePowerTools/files/3133544/EFCorePowerTools_InstallLog.txt)

**Comment by jespersh** [comment]
Could you try this: http://www.asoft.be/prod_netver.html
Windows Server 2016 ships with dotnet 4.6.2 and you need (at least) 4.7.1

**Comment by rohitnayakmsft** [comment]
Installing latest .Net (4.8) runtime solved the issue and installation worked fine for VS 2017. I would suggest calling this out in the pre-requisites

**Comment by ErikEJ** [comment]
Thanks, I have updated the readme file: https://github.com/ErikEJ/EFCorePowerTools
