### ISSUE TITLE
Reverse Engineering off .dacpac File Removes Stored Procedure Result Type

### ISSUE THREAD

**Issue by phil000** [ErikEJ/EFCorePowerTools#2156]
We're reverse engineering an EF model from the project .dacpac file.

We have 1 stored procedure that we have renamed from "spGetTrackableAssetsWithLastState" to "GetTrackableAssetsWithLastState" in  efpt.renaming.json.

When generating the model the result file that currently exists from many previous generations - "GetTrackableAssetsWithLastStateResult.cs" is deleted. 

If I remove the renaming the new result file "spGetTrackableAssetsWithLastStateResult.cs" is not actually created, and the solution will not build - The type or namespace 'spGetTrackableAssetsWithLastStateResult' could not be found.

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
**2.6.72**

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
**17.8.6**

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
**SQL Server**

- EF Core version in use: (e.g. EF Core 7)
**EF Core 8**

- Is Handlebars templates used: no/yes
**Yes**

- Is T4 templates used: no/yes
**No**

- Is a SQL Server .dacpac used: no/yes
**Yes**

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/9067236/2d65e522-1f0a-4f90-b6d1-9654eaf059d0)

**Comment by phil000** [comment]
Existing stored procedure result file generated previously under EF7 is deleted....

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/9067236/a153c582-6459-487a-b4ea-8456d18d8306)

**Comment by ErikEJ** [comment]
Have you tried the latest daily build, there   have been some .dacpac related Bug fixes

**Comment by phil000** [comment]
I just downloaded and installed **2.6.138**

It didn't work well and the extension won't load.

```
SetSite failed for package [EFCorePowerToolsPackage]Source: 'EFCorePowerTools' Description: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.17.0.146, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.17.0.146, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.ApplicationInsights, Version=2.17.0.146, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at EFCorePowerTools.Helpers.Telemetry.TrackException(Exception ex)
   at EFCorePowerTools.EFCorePowerToolsPackage.<>c__DisplayClass10_0.<<LogError>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run(Func`1 asyncMethod)
   at EFCorePowerTools.EFCorePowerToolsPackage.LogError(List`1 statusMessages, Exception exception)
   at EFCorePowerTools.EFCorePowerToolsPackage.<InitializeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by ErikEJ** [comment]
Wonderful. Maybe reinstall.

I need a complete repro in order to investigate.

**Comment by phil000** [comment]
I did a few uninstall \ reinstall \ restart VS loops, but no luck.

OK, I just copied a version of 'Microsoft.ApplicationInsights.dll' into the extension directory and the extension will run now.

However, it does delete the existing stored procedure results file again.

I will pare down our solution to the minimum viable and upload it here tomorrow. (It's 8pm right now)

**Comment by ErikEJ** [comment]
Thanks - Which Microsoft.ApplicationInsights.dll version did you use?

**Comment by phil000** [comment]
[assembly: AssemblyFileVersion("2.17.0.00146")]
[assembly: AssemblyInformationalVersion("2.17.0+c9d95e701e2474b7eb3b46ae7953b6c7570356ab")]
[assembly: AssemblyProduct("Microsoft.ApplicationInsights")]
[assembly: AssemblyTitle("Microsoft.ApplicationInsights")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/Microsoft/ApplicationInsights-dotnet")]
[assembly: AssemblyVersion("2.17.0.146")]

**Comment by phil000** [comment]
This minimal solution will produce the issue...

There is a copy of the file included in the solution called "GetTrackableAssetsWithLastStateResult - GETS DELETED.zzz" so it can be reinstated after it's deleted.

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/9067236/094d05a5-05a1-4b04-a155-fa24e22ba0ec)

[Solution.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14257494/Solution.zip)

**Comment by ErikEJ** [comment]
OK, I was able to repro, see this error in the Extensions output window - do you also see that?

```
Unable to get result set shape for dbo.spGetTrackableAssetsWithLastState
System.InvalidOperationException: Could not find column within BodyDependencies: TAS.TrackableAssetStateId
   at SqlSharpener.Model.SelectColumn..ctor(SelectScalarExpression selectScalarExpression, IDictionary`2 bodyColumnTypes, IDictionary`2 tableAliases, IEnumerable`1 outerJoinedTables) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\SqlSharpener\Model\SelectColumn.cs:line 50
   at SqlSharpener.Model.Select.<>c__DisplayClass1_0.<.ctor>b__0(SelectScalarExpression x) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\SqlSharpener\Model\Select.cs:line 52
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at SqlSharpener.Model.Select..ctor(QuerySpecification querySpecification, IDictionary`2 bodyColumnTypes) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\SqlSharpener\Model\Select.cs:line 52
   at SqlSharpener.Model.Procedure.<>c__DisplayClass0_0.<.ctor>b__7(QuerySpecification s) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\SqlSharpener\Model\Procedure.cs:line 55
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at SqlSharpener.Model.Procedure..ctor(TSqlObject tSqlObject) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\SqlSharpener\Model\Procedure.cs:line 55
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerDacpacStoredProcedureModelFactory.GetStoredProcedureResultElements(TSqlProcedure proc) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\Scaffolding\SqlServerDacpacStoredProcedureModelFactory.cs:line 159
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerDacpacStoredProcedureModelFactory.GetStoredProcedures(String dacpacPath, ModuleModelFactoryOptions options, Boolean mergeDacpacs) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\Scaffolding\SqlServerDacpacStoredProcedureModelFactory.cs:line 81

```

**Comment by ErikEJ** [comment]
Parsing the result set failed, as the parser could not discover the table alias.

Do not use aliases, or modify as follows and the result set is generated:

```sql
FROM
	[dbo].[Trackable] AS T
	CROSS APPLY
	(
		SELECT TOP (1) [TrackableAssetStateId], [Latitude], [Longitude], [LocationDateTimeUtc], [Speed], [Heading], [Version]
		FROM [dbo].[TrackableAssetState] AS TAS
		WHERE TrackableId = T.TrackableId
		AND T.TenantId = @TenantId
		ORDER BY [LocationDateTimeUtc] DESC
	) AS TAS

```

I was ab

**Comment by ErikEJ** [comment]
Yeah, determining the result shape of a stored procedure is not simple! But great to hear you got it working.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
