### ISSUE TITLE
Unable to use migration tool when database and application is split into muliple assemblies

### ISSUE THREAD

**Issue by Tdue21** [ErikEJ/EFCorePowerTools#2242]
### Provide steps to reproduce a bug

I have two projects in my solution: 
1. A Class library containing DbContext and entities. 
2. A Web API project containing Program (top-level statements) etc. 

There are of course many more projects in the solution, but these are the two important ones. 
The problem is, I get the below exception when I try to run the Migration tool on the database project: 

```
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create a 'DbContext' of type 'DemoDbContext'. The exception 'Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.DemoDbContext]' while attempting to activate 'Database.DemoDbContext'.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.DemoDbContext]' while attempting to activate 'Database.DemoDbContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass20_5.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)

   --- End of inner exception stack trace ---

   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Modelling.EfCoreMigrationsBuilder.GetMigrationStatus(String outputPath, String startupOutputPath) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\EFCoreMigrationsBuilder.cs:line 80
   at Modelling.EfCoreMigrationsBuilder.GenerateMigrationStatusList(String outputPath, String startupOutputPath) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\EFCoreMigrationsBuilder.cs:line 24
   at Modelling.Program.Main(String[] args) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\Program.cs:line 41
``` 

And when I try to run the tool on the application project: 
```
Microsoft.EntityFrameworkCore.Design.OperationException: Your target project 'ApiApplication' doesn't match your migrations assembly 'Database'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("ApiApplication")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
   at Modelling.EfCoreMigrationsBuilder.EnsureMigrationsAssembly(IServiceProvider services, Assembly assembly) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\EFCoreMigrationsBuilder.cs:line 276
   at Modelling.EfCoreMigrationsBuilder.AddMigration(String name, String outputPath, String startupOutputPath, String projectPath, String nameSpace, DbContext context) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\EFCoreMigrationsBuilder.cs:line 187
   at Modelling.EfCoreMigrationsBuilder.AddMigration(DbContext context, String outputPath, String startupOutputPath, String projectPath, String name, String nameSpace) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\EFCoreMigrationsBuilder.cs:line 163
   at Modelling.EfCoreMigrationsBuilder.BuildMigrationResult(String outputPath, String startupOutputPath, String projectPath, String contextName, Boolean addMigration, Boolean scriptMigration, String migrationIdentifier, String nameSpace) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\EFCoreMigrationsBuilder.cs:line 60
   at Modelling.EfCoreMigrationsBuilder.AddMigration(String outputPath, String startupOutputPath, String projectPath, String contextName, String migrationIdentifier, String nameSpace) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\EFCoreMigrationsBuilder.cs:line 34
   at Modelling.Program.Main(String[] args) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\Program.cs:line 53
```

In my real-world project I get another error with the application, caused by the tool failing to connect to the Azure KeyVault where my connection string is stored.

But basically, it appears that the migration tool does not have the ability to properly set startup and database project. 

I have attached a very simple demo solution. 

### Provide technical details

- EF Core Power Tools version: 2.6.72

- Exact Visual Studio version: Visual Studio 2022 17.9.0

- Database engine: SQL Server

- EF Core version in use: EF Core 8.0.3

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

[EfCorePowerToolsMigrationBug.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14696456/EfCorePowerToolsMigrationBug.zip)

**Comment by ErikEJ** [comment]
Setting the ApiApplication project a Startup project and modifying the connection string to point to an existing database, I had no issues launching the tool and loisting the DbContext
