### ISSUE TITLE
Exception on database context Editing and Refreshing in Visual Studio

### ISSUE THREAD

**Issue by Vasilii-KV** [ErikEJ/EFCorePowerTools#2243]
#### Refresh
- right-button click the `efpt.config.json`
- select `EF Power Tools - Refresh`
- Visual Studio shows message:
![20240322-vs-message](https://github.com/ErikEJ/EFCorePowerTools/assets/97528460/d6a75d21-135d-4868-b4d9-cd32193e3718)
- Extension output:
```
Microsoft.SqlServer.Dac.DacServicesException: Could not load schema model from package.
 ---> Microsoft.Data.Tools.Schema.SchemaModel.ModelSerializationException: The Element or Annotation class SqlIndex does not contain the Property class Online.
   at Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModel.ModelStoreDeserializerState.ReadProperty(IModelPropertyContainer propertyContainer, ModelPropertyContainerClass propertyContainerClass, String propertyContainerClassName)
   at Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModel.ElementState.ProcessStartElement()
   at Microsoft.Data.Tools.Schema.SchemaModel.XmlDeserializerEngine.ReadData(DeserializerState initialState, Boolean keepCurrentReaderPosition)
   at Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModel.DeserializeXml(TextReader input, ErrorManager errors, String source, Action`3 constructorParametersSetter)
   at Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModel.DeserializePackage(SqlPackage package, ErrorManager errors, Action`3 constructorParametersSetter)
   at Microsoft.SqlServer.Dac.DacPackage.DeserializePackage(SqlPackage package, DacSchemaModelStorageType modelStorageType, ErrorManager errorManager, DataSchemaModelHeader& header)
   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelLoader.LoadModel(IPackageSource packageSource, ErrorManager errorManager, DataSchemaModelHeader& modelHeader)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelLoader.LoadModel(IPackageSource packageSource, ErrorManager errorManager, DataSchemaModelHeader& modelHeader)
   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelLoader.LoadFromDacpac(IPackageSource packageSource, String fileNameIfPresent)
   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelLoader..ctor(String fileName, DacSchemaModelStorageType modelStorageType)
   at Microsoft.SqlServer.Dac.Model.TSqlModel..ctor(String fileName, ModelLoadOptions options, CancellationToken cancelToken)
   at Microsoft.SqlServer.Dac.Model.TSqlModel..ctor(String fileName, DacSchemaModelStorageType modelStorageType)
   at Microsoft.SqlServer.Dac.Model.TSqlModel..ctor(String fileName)
   at Microsoft.SqlServer.Dac.Extensions.Prototype.TSqlTypedModel..ctor(String filename) in C:\Code\Github\EFCorePowerTools\src\GUI\DacFxStrongTypedCore\TSqlTypedModel.cs:line 46
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerDacpacDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\Scaffolding\SqlServerDacpacDatabaseModelFactory.cs:line 73
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 460
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerRunner.cs:line 86
```

#### Edit
- right-button click the `efpt.config.json`
- select `EF Power Tools - Edit`
- select the database project (.dacpac source) and click `OK`
- Visual Studio shows message:
![20240322-vs-error](https://github.com/ErikEJ/EFCorePowerTools/assets/97528460/289e3fb4-0f92-40c3-997a-55fd8152ec71)

### Technical details

- EF Core Power Tools version:
2.6.140

- Exact Visual Studio version:
17.9.4

- Database engine:
SQL Server

- EF Core version in use:
EF Core 8

- Is Handlebars templates used:
no

- Is T4 templates used:
yes

- Is a SQL Server .dacpac used: no/yes
yes

#### Additional technical details
- Target platform for the database project:
SQL Server 2017 (140)

- Version of the `sqlpackage` in `C:\Program Files\Microsoft SQL Server\160\DAC\bin`
162.2.111.2

- Version of the Visual Studio `sqlpackage` in `C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\DAC`
162.2.111.2

- I've also tried the following `dotnet` update with no success
command: `dotnet tool update Microsoft.Sqlpackage -g`
output: `Tool 'microsoft.sqlpackage' was reinstalled with the stable version (version '162.2.111').`

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by Vasilii-KV** [comment]
> I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

Works as expected, thanks a lot! 👍
