### ISSUE TITLE
Unable to get result set shape for dbo.SP_* 

### ISSUE THREAD

**Issue by Indrasen-007** [ErikEJ/EFCorePowerTools#2263]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

I am trying to scaffold stored procedure from the db project, and I am getting the below error. However the same thing works when I am using a database to connect.
Please let me know if you need more information.

Unable to get result set shape for dbo.SP_ScenariosBreakupByFrequency
System.InvalidOperationException: Could not find column within BodyDependencies: Label
   at SqlSharpener.Model.SelectColumn..ctor(SelectScalarExpression selectScalarExpression, IDictionary`2 bodyColumnTypes, IDictionary`2 tableAliases, IEnumerable`1 outerJoinedTables) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\SqlSharpener\Model\SelectColumn.cs:line 50
   at SqlSharpener.Model.Select.<>c__DisplayClass1_0.<.ctor>b__0(SelectScalarExpression x) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\SqlSharpener\Model\Select.cs:line 52
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at SqlSharpener.Model.Select..ctor(QuerySpecification querySpecification, IDictionary`2 bodyColumnTypes) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\SqlSharpener\Model\Select.cs:line 52
   at SqlSharpener.Model.Procedure.<>c__DisplayClass0_0.<.ctor>b__7(QuerySpecification s) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\SqlSharpener\Model\Procedure.cs:line 54
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at SqlSharpener.Model.Procedure..ctor(TSqlObject tSqlObject) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\SqlSharpener\Model\Procedure.cs:line 54
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerDacpacStoredProcedureModelFactory.GetStoredProcedureResultElements(TSqlProcedure proc) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\Scaffolding\SqlServerDacpacStoredProcedureModelFactory.cs:line 160
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerDacpacStoredProcedureModelFactory.GetStoredProcedures(String dacpacPath, ModuleModelFactoryOptions options, Boolean mergeDacpacs) in C:\Code\Github\EFCorePowerTools\src\Nupkg\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\Scaffolding\SqlServerDacpacStoredProcedureModelFactory.cs:line 81

### Provide technical details

- EF Core Power Tools version: 2.6.200

- Exact Visual Studio version: Visual Studio 2022 17.9.5

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: yes

**Comment by ErikEJ** [comment]
I need a sample CREATE table statement or your database project in order to investigate.

Have you tried from a live database?

**Comment by ErikEJ** [comment]
Closing as no repro provided, if you provide a repro we can re-open

**Comment by Kolejarz** [comment]
[abc.zip](https://github.com/user-attachments/files/22494704/abc.zip)

@ErikEJ I stumbled upon similar issue with `efcpt.9 9.1.924+b580c4506b90fd3d2fb0c5bb4ace081115522b80`
Attached is minimal repro project. By running
```
dotnet build
efcpt .\bin\Debug\abc.dacpac mssql
```

I get
```
warning: Unable to get result set shape for dbo.USP_Error
System.InvalidOperationException: Could not find column within BodyDependencies: TestColumn
   at SqlSharpener.Model.SelectColumn..ctor(SelectScalarExpression selectScalarExpression, IDictionary`2 bodyColumnTypes, IDictionary`2 tableAliases, IEnumerable`1 outerJoinedTables) in /_/src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/SqlSharpener/Model/SelectColumn.cs:line 50
   at SqlSharpener.Model.Select.<>c__DisplayClass1_0.<.ctor>b__0(SelectScalarExpression x) in /_/src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/SqlSharpener/Model/Select.cs:line 52
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at SqlSharpener.Model.Select..ctor(QuerySpecification querySpecification, IDictionary`2 bodyColumnTypes) in /_/src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/SqlSharpener/Model/Select.cs:line 52
   at SqlSharpener.Model.Procedure.<>c__DisplayClass0_0.<.ctor>b__7(QuerySpecification s) in /_/src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/SqlSharpener/Model/Procedure.cs:line 57
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at SqlSharpener.Model.Procedure..ctor(TSqlObject tSqlObject) in /_/src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/SqlSharpener/Model/Procedure.cs:line 57
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerDacpacStoredProcedureModelFactory.GetStoredProcedureResultElements(TSqlProcedure proc) in /_/src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/Scaffolding/SqlServerDacpacStoredProcedureModelFactory.cs:line 171
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerDacpacStoredProcedureModelFactory.GetStoredProcedures(String dacpacPath, ModuleModelFactoryOptions options, Boolean mergeDacpacs) in /_/src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/Scaffolding/SqlServerDacpacStoredProcedureModelFactory.cs:line 83
```

**Comment by Kolejarz** [comment]
@ErikEJ do you have a more detailed instruction on running the `efrevengXX` projects locally?
I wanted to replicate this, but I cannot get it to working state - even when providing `dacpactest.txt` as presented in README

**Comment by ErikEJ** [comment]
@Kolejarz It is very easy to run the CLI locally, I suggest you do that instead.

1. Set the efcpt.8 project as startup project
2. In the debug profile, set the path to your dacpac
3. Set a breakpoint at the start of src\Nupkg\ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac\SqlSharpener\Model\SelectColumn.cs
4. Press F5 to launch and attach the debugger
5. You can modify the config file after first run in the /bin/debug/net8.0 folder

Please let me know if this is not working for you.

<img width="984" height="288" alt="Image" src="https://github.com/user-attachments/assets/476e09f0-9dff-40c2-b6aa-2caddb457df6" />

**Comment by ErikEJ** [comment]
@Kolejarz Did you get any further?

**Comment by Kolejarz** [comment]
I was able to run the solution locally and patch together some initial fix, but it's not working reliably on initial stored procedure - still planning to work on it a bit more

**Comment by ErikEJ** [comment]
@Kolejarz Any news?

**Comment by Kolejarz** [comment]
> [@Kolejarz](https://github.com/Kolejarz) Any news?


@ErikEJ 
I'm working on it, but cannot find any clever solution 🫤 this is the (simplified) stored procedure I have (there are a lot of them - unsupported, sitting in DB for ages)

```
CREATE PROC [dbo].[GetSampleData]
(
    -- Kept only parameters required for the minimal logic
    @EntityId INT
)
AS BEGIN

    WITH TempResult AS
    (
        SELECT 
            ROW_NUMBER() OVER(ORDER BY T1.[ForeignKeyB] ASC ) as RowNum,
            T2.[ForeignKeyC] as thisIsAlias,
            (CASE
                WHEN EP.[RoleType]  = 1 then 0
                When EP.[RoleType] = 2 then 1
                else 0 END) AS [ReadOnly]
            
            -- ... other columns removed for brevity ...
            
        FROM [dbo].[Table1] T1
        JOIN [dbo].[Table2] T2 on T1.[ForeignKeyB] = T2.[Id]
        JOIN [dbo].[Table3] C ON T2.[ForeignKeyC] = C.Id
        JOIN [dbo].[Entity] E ON E.[CompanyId] = T1.[CompanyId]
        INNER JOIN [dbo].[EntityPrivileges] EP on E.[Id] = EP.[EntityId]
            and EP.[RangeMax] >= CONVERT(NVARCHAR(max), C.[CodeValue]) 
            and EP.[RangeMin] <= CONVERT(NVARCHAR(max), C.[CodeValue])
        WHERE 
            E.[Id] = @EntityId
    )
    
    -- Simplified outer SELECT to show the CTE is consumed
    SELECT 
        RowNum,
        thisIsAlias,
        [ReadOnly]
    FROM TempResult;

END
```

I started working on aliased (`thisIsAlias`) column first by implementing new `TSqlFragmentVisitor` that goes over entire stored procedure and gets aliases for columns, adding them to `bodyDependencies` in `Procedure.cs` from `SqlSharpener` project - works on my sample data, but I feel it's very fragile solution

Now the CASE statement that is a part of CTE - `tSqlObject.GetReferenced(Dac.Procedure.BodyDependencies)` does not return this column, so I guess the best course of action would be to parse the TSql and try to guess the type from `THEN` statements? Or simply introduce a fallback mechanism that will scaffold this as generic `object`? I don't have that much experience with SPs and SQL in general, so I don't want to break existing logic for anyone - any suggestions which way should it go?

**Comment by ErikEJ** [comment]
@Kolejarz Thanks for the effort, I think I will fix this by preventing the blocking error from being thrown, based on the minimal repro you shared.

When no error is thrown, you will get an empty result set class, where you can add the properties.

**Comment by ErikEJ** [comment]
Actually, the error is just displayed for info, processing continues
