### ISSUE TITLE
Issues Viewing Model Diagram

### ISSUE THREAD

**Issue by mselley** [ErikEJ/EFCorePowerTools#237]
Hi,

Trying to use the tools with .net core 2.2.
I have a separation of concerns so my Context is in a different project to my Interface MVC Layer.
Migrations and normal running work as expected.
Getting the following error.

System.ArgumentException: Error:
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'SCMContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728 ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 39
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 68

Setup is as follows

    public class SCMContext : DbContext
    {
        public SCMContext(DbContextOptions<SCMContext> options)
            : base(options)
        {
        }
    }

And the following in startup.

            services.AddDbContext<SCMContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("SCMContext"));
            });

I tried making a parameter-less constructor but then get errors about the connection string not being configured.

Let me know if any more information is needed.

Any help greatly appreciated.
Thanks

**Comment by ErikEJ** [comment]
>> No parameterless constructor defined for this object. !!

**Comment by ErikEJ** [comment]
Which Power Tools version?

**Comment by mselley** [comment]
V2.2.63

**Comment by ErikEJ** [comment]
And EF Core version?

**Comment by mselley** [comment]
V2.2.4

**Comment by ErikEJ** [comment]
You need to fix this: >>  No parameterless constructor defined for this object.

**Comment by mselley** [comment]
I can solve that with a hack below to get it to run to produce the diagram, but obviously this breaks everything else.
        public SCMContext()
        {
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            /// dummy string is below to allow EF Core Power Tools
            optionsBuilder.UseSqlServer("ForEFCorePowerTools");
        }

In a .net Core Project what is EFCorePowerTools expecting as it doesnt appear to use the DbContextOptions that are injected into the normal constructor.

Thanks

**Comment by ErikEJ** [comment]
@bricelam are you able to explain??

**Comment by ErikEJ** [comment]
Closing this a by design...

**Comment by mselley** [comment]
Sorry what is by design? 
Can you provide an example of how you would expect a context and startup to be coded to work with ef core tools with Net core?

**Comment by ErikEJ** [comment]
The requirement to have a parameterless constructor

**Comment by mselley** [comment]
Can you provide an example of how you would expect a context and startup to be coded to work with ef core tools with Net core?

**Comment by ErikEJ** [comment]
Please share a repro that is failing for you, and I will have a look

**Comment by bricelam** [comment]
@ErikEJ If you use [DbContextActivator](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.Design/Design/DbContextActivator.cs), all of our design-time logic for instantiating a DbContext is used including getting it from the ASP.NET Core application services and using IDesignTimeDbContextFactory.

**Comment by ErikEJ** [comment]
@bricelam I think I basically do: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efpt/EFCoreMigrationsBuilder.cs#L179

**Comment by abmptit** [comment]
check if Microsoft.EntityFrameworkCore.Design is installed
