### ISSUE TITLE
Remove a column with a foreign key at another column of same table

### ISSUE THREAD

**Issue by MauroVevy** [ErikEJ/EFCorePowerTools#2391]
# Problem

***If in the efpct configuration file I exclude a column that has a foreign key with another column of the same table, I get the following error***

```bash
error: System.ArgumentException: properties
   at Microsoft.EntityFrameworkCore.Utilities.Check.HasNoNulls[T](IReadOnlyList`1 value, String parameterName)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.FindForeignKey(IReadOnlyList`1 properties, IReadOnlyKey principalKey, IReadOnlyEntityType principalEntityType)
```

## Repro

Create a database called `EfcptTest` with this tables

- `Customers`

From this database I **Remove from `Customers` table the column `MasterId`** .

Here are all the steps to reproduce the problem

## Db Creation

```sql
create database EfcptTest
GO

use EfcptTest
GO
```

## Create Customer table

```sql
CREATE TABLE [dbo].[Customers](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Surname] [nvarchar](50) NULL,
	[Address] [nvarchar](50) NULL,
	[MasterId] [int] NULL
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customer_MaterId_Customer] FOREIGN KEY([MasterId])
REFERENCES [dbo].[Customers] ([Id])
GO

ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customer_MaterId_Customer]
GO
```

## Note

**In table `Customers` `MasterId` is foreign key of `Id`**

## Efpct Configuration files

```json
{
    "$schema": "https://raw.githubusercontent.com/ErikEJ/EFCorePowerTools/master/samples/efcpt-schema.json",
    "code-generation": {
        "enable-on-configuring": false,
        "generate-mermaid-diagram": false,
        "merge-dacpacs": false,
        "refresh-object-lists": false,
        "remove-defaultsql-from-bool-properties": false,
        "soft-delete-obsolete-files": true,
        "t4-template-path": null,
        "type": "all",
        "use-alternate-stored-procedure-resultset-discovery": false,
        "use-data-annotations": false,
        "use-database-names": false,
        "use-decimal-data-annotation-for-sproc-results": true,
        "use-inflector": true,
        "use-legacy-inflector": false,
        "use-many-to-many-entity": false,
        "use-nullable-reference-types": true,
        "use-prefix-navigation-naming": false,
        "use-t4": false
    },
    "file-layout": {
        "output-dbcontext-path": null,
        "output-path": "Models",
        "split-dbcontext-preview": true
    },
    "functions": [
        {
            "exclusionWildcard": "*"
        }
    ],
    "names": {
        "dbcontext-name": "EfcptContext",
        "dbcontext-namespace": null,
        "model-namespace": null,
        "root-namespace": "EfpctTest"
    },
    "stored-procedures": [
        {
            "exclusionWildcard": "*"
        }
    ],
    "tables": [
        {
            "exclusionWildcard": "*"
        },
        {
            "name": "[dbo].[Customers]",
            "exclude": false,
            "excludedColumns": [
                "MasterId"
            ]
        }
    ],
    "views": [
        {
            "exclusionWildcard": "*"
        }
    ]
}
```

## Command

```bash
efcpt "Server=[myServer]; Database=EfcptTest; Trusted_Connection=Yes; Integrated Security=true; TrustServerCertificate=true;" mssql 
```

Change `[myServer]` with yours.

## Error

This is the message received after the command

```
error: System.ArgumentException: properties
   at Microsoft.EntityFrameworkCore.Utilities.Check.HasNoNulls[T](IReadOnlyList`1 value, String parameterName)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.FindForeignKey(IReadOnlyList`1 properties, IReadOnlyKey principalKey, IReadOnlyEntityType principalEntityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.FindForeignKey(IReadOnlyList`1 properties,
IReadOnlyKey principalKey, IReadOnlyEntityType principalEntityType)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKey(ModelBuilder modelBuilder, DatabaseForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys)
   at RevEng.Core.ColumnRemovingScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys) in
D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ColumnRemovingScaffoldingModelFactory.cs:line 131
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions,      
ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, 
Boolean useSchemaNamespaces) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 488
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String    
contextNamespace, String projectPath, String outputPath) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in
D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerRunner.cs:line 86
warning: [dbo].[Customers].MasterId is either a Primary Key or Foreign Key of another Table. Removing this column could result in an invalid model.
```

**Comment by ErikEJ** [comment]
OMG - Pandoras box 😄

**Comment by MauroVevy** [comment]
This works too.
Thank you for your support and quick problem resolution

**Comment by ErikEJ** [comment]
@MauroVevy thanks for helping battle hardening this feature. I think I can even start being less restrictive in the UI now
