### ISSUE TITLE
Remove support for EF Core 6 end of 2025

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#2476]
- [x] Remove EF Core 6 projects, but leave .zip files for now
- [x] Create release with last version with support for EF Core 6
- [x] RevEng (look for enum)
- [x] CLI
- [x] Remove old .zip files
- [x] Consider using EF Core 10 binaries for EF Core 9 (pending providers)
- [x] New Power Tools release

**Comment by doggy8088** [comment]
Is there any way to install previous version of EF Core Power Tools extension for Visual Studio 2022?

**Comment by ErikEJ** [comment]
Yes. But EF Core 6 is still available in the current version. And I do not provide any kind of free support for the older builds.

**Comment by doggy8088** [comment]
Can you tell how? I couldn't find a way to install previous version of EF Core Power Tools. I can't even find version history in anywhere.

**Comment by ErikEJ** [comment]
In the tools folder in the archive branch you can find some older builds.

But why do you need it?

**Comment by doggy8088** [comment]
I don't personally need this; it was one of my students who asked this question. He wants to install an older version of EF Core Power Tool to develop his legacy .NET application.

**Comment by FadiMallat** [comment]
Hello, @ErikEJ 
I am trying to install the build [EF_Core_Power_Tools_v2.6.698.vsix](https://github.com/ErikEJ/EFCorePowerTools/blob/archive/tools/EFCore7Support/EF_Core_Power_Tools_v2.6.698.vsix)

but i get always object reference error:

 Signature Details...
12/24/2024 10:42:49 AM - 	Extension is signed with an invalid signature.
12/24/2024 10:42:49 AM - System.NullReferenceException: Object reference not set to an instance of an object.
   at VSIXInstaller.ExtensionService.LogSignatureDetails(IExtension extension)
   at VSIXInstaller.ExtensionService.LogExtensionDetails(IExtension extension)
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by ErikEJ** [comment]
@FadiMallat Please create a new issue with requested details like exact VS version etc. 

And as noted, support for EF Core 7 stopped more than 18 months ago.
