### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'DacFxStrongTypedCore.161

### ISSUE THREAD

**Issue by ilGianfri** [ErikEJ/EFCorePowerTools#2539]
### Provide steps to reproduce a bug

Hello,
I'm trying to run the reverse engineering from a .dacpac but when I right click on "efpt.config.json" > EF Core Power Tools - Refresh, I get the following error:

System.IO.FileNotFoundException: Could not load file or assembly 'DacFxStrongTypedCore.161, Version=2.6.486.0, Culture=neutral, PublicKeyToken=d9645e6262c2eca7'. The system cannot find the file specified.
File name: 'DacFxStrongTypedCore.161, Version=2.6.486.0, Culture=neutral, PublicKeyToken=d9645e6262c2eca7'
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerDacpacDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 460
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerRunner.cs:line 86

I think the extension automatically updated yesterday to the latest version.

Thank you!

### Provide technical details

- EF Core Power Tools version: 2.6.486

- Exact Visual Studio version: Visual Studio Enterprise 2022 17.12.0 Preview 2.0

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: yes

**Comment by ErikEJ** [comment]
@ilGianfri Thanks for reporting, this is probably due to recent build changes, I am having a look

**Comment by ErikEJ** [comment]
@ilGianfri 

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ilGianfri** [comment]
Just tried it out and the error is gone. Thank you!
