### ISSUE TITLE
"Migration tool" causes UnauthorizedAccessException

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [ErikEJ/EFCorePowerTools#291]
```
System.UnauthorizedAccessException: Access to the path 'efpt.dll' is denied.

   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)

   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)

   at EFCorePowerTools.Handlers.ProcessLauncher.DropNetCoreFiles() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ProcessLauncher.cs:line 238

   at EFCorePowerTools.Handlers.ProcessLauncher.GetOutput(String outputPath, String projectPath, GenerationType generationType, String contextName, String migrationIdentifier, String nameSpace) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ProcessLauncher.cs:line 62

   at EFCorePowerTools.Handlers.ProcessLauncher.<>c__DisplayClass3_0.<GetOutputAsync>b__0() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ProcessLauncher.cs:line 35

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at EFCorePowerTools.ViewModels.MigrationOptionsViewModel.<GetMigrationStatus>d__62.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\ViewModels\MigrationOptionsViewModel.cs:line 264
---------------------------
OK   
---------------------------

```

### Steps to reproduce
Right click on a project, _EF Core Power Tools → Migration tool (preview)_

### Further technical details
EF Core Power Tools version: 2.3.74.0

Database engine: Postgres

Visual Studio version: Visual Studio 2019 16.3.5

**Comment by ErikEJ** [comment]
Maybe your virus scanner? Files are located in %temp%\efpt folder.

**Comment by ErikEJ** [comment]
Ping?

**Comment by ZimM-LostPolygon** [comment]
Somehow, it was `dotnet.exe` which was locking the file. Killing the process and restarting VS made that particular issue go away.
