### ISSUE TITLE
EF Core Power Tool for VS 2019 cannot add dbcontext diagram

### ISSUE THREAD

**Issue by alexle1965** [ErikEJ/EFCorePowerTools#341]
The tool threw exceptions when I attempted to add a dbcontext diagram in Visual Studio 2019 16.4.1 for EF Core 2.2.  

Exception message:
`
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateDgml(String processResult, Project project) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 122
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 80

`
### Steps to reproduce

1. In VS 2019, right-click on the project that contains the dbcontext
2. Select EF Core Power Tools
3. Select Add DbContext Model Diagram

### Further technical details
EF Core Power Tools version: 2.3.92.0

Database engine: MS SQL Server

Visual Studio version:  Visual Studio 2019 16.4.1
![EFCorePowerTools-Exceptions](https://user-images.githubusercontent.com/6333188/72914171-e8e8f980-3d03-11ea-9068-e5a976a9fd3e.png)

**Comment by ErikEJ** [comment]
Where does you project reside? On a file share?

**Comment by ErikEJ** [comment]
Can you share your DbContext class? Or what is the name of your DbContext?

**Comment by alexle1965** [comment]
This is my project at work and I am not sure if I am allowed to put it out in the public forum.  The context name that I used is: "BcDbContext.cs".

[EFCorePowerTools-BcDbContext-StackOverflow.txt](https://github.com/ErikEJ/EFCorePowerTools/files/4098802/EFCorePowerTools-BcDbContext-StackOverflow.txt)

**Comment by alexle1965** [comment]
I clone it from our Git Repo to the local directory on my computer in c:\local\dev\repo. 



⁣Alex Le
316-371-8179

**Comment by alexle1965** [comment]
> Where does you project reside? On a file share?

On the local computer in the C:\Local\Dev\Repo directory.

**Comment by stefankip** [comment]
I have a (imo) related issue:
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateDgml(String processResult, Project project) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 122
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 80
```

AFAIK there's nothing special about the project's path.

**Comment by ErikEJ** [comment]
@stefankip Thanks for chiming in!
As you can see here: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Handlers/ModelAnalyzerHandler.cs#L122 
it is actually the %temp% path that is involved here.  Can you check that? (Or I have a bug...)

**Comment by stefankip** [comment]
@ErikEJ yes I saw that, but I was thinking `info.Item1` is the suspect.
My `%temp%` variable resolved to `C:\Users\Stefan\AppData\Local\Temp`.

**Comment by ErikEJ** [comment]
Agree, I will try to repro - can you share a repro project, perhaps?

**Comment by stefankip** [comment]
I'm afraid I can't just share a project I'm working on. Is it hard to debug it myself?

**Comment by ErikEJ** [comment]
No too hard, but let me try to repro first.

**Comment by ErikEJ** [comment]
@stefankip What type of project and .NET Core version do you use (show me your .csproj file)

**Comment by stefankip** [comment]
It's a pretty simple .NET Core 3.1 web API project.
I can post the csproj on Monday.

Op vr 24 jan. 2020 19:11 schreef Erik Ejlskov Jensen <
notifications@github.com>:

**Comment by ErikEJ** [comment]
I am unable to repro, will await your csproj

**Comment by ErikEJ** [comment]
@stefankip Would be greate if you could debug, you must have the VS extensibility workload installed on a new VS version, the follow this: https://github.com/ErikEJ/EFCorePowerTools#building-and-debugging

**Comment by stefankip** [comment]
So yeah this is the complete string used for the `Path.Combine` methode:
```
"C:\\Users\\Stefan\\AppData\\Local\\Temp\\dbug: Microsoft.EntityFrameworkCore.Infrastructure[10401]\r\n      An 'IServiceProvider' was created for internal use by Entity Framework.\r\ninfo: Microsoft.EntityFrameworkCore.Infrastructure[10403]\r\n      Entity Framework Core 3.1.1 initialized 'MarketIntelligenceContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None.dgml"
```

I guess that's not going to work at all ;-)

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build

**Comment by stefankip** [comment]
Seems like a legit fix 😉

Op ma 27 jan. 2020 17:18 schreef Erik Ejlskov Jensen <
notifications@github.com>:

**Comment by ErikEJ** [comment]
Did you manage to verify the fix?

**Comment by stefankip** [comment]
No not at work at the moment 😏

Op ma 27 jan. 2020 19:14 schreef Erik Ejlskov Jensen <
notifications@github.com>:

**Comment by stefankip** [comment]
I can verify the fix works, a DGML file is being generated :-)

**Comment by alexle1965** [comment]
Thank you for fixing the problem.  I use your tool now to reverse engineer the existing database.  I still don’t how to generate the Model Diagram so that I can see all the relationship.  I guess it is the limitation of my visual studio 2019 that does not have the dgml interpreter.

Once again, thank you.

Alex Le
316-371-8179 (mobile)
316-722-9906 (home)

**Comment by ErikEJ** [comment]
Yes, you may have to add the dgml viewer via VS Installer.

**Comment by alexle1965** [comment]
Which one do you use?  I prefer to use what you are using to be consistent.  I found a viewer by Chris Lovett “DgmlPowerTools 2019” but I want to hear from you.

Thank you.

**Comment by ErikEJ** [comment]
I use the one built into Visual Studio!

**Comment by alexle1965** [comment]
What an awesome tool. I am new to ef core so the reverse engineering feature is nice. The model diagram too m

⁣Alex Le
316-371-8179

**Comment by ErikEJ** [comment]
Thanks for the kind words.
