### ISSUE TITLE
"*Navigation" fields cause recursive JSON output

### ISSUE THREAD

**Issue by echiabra** [ErikEJ/EFCorePowerTools#351]
### Steps to reproduce
We have two tables on a SQL Server Database:

```
CREATE TABLE [dbo].[General_User](
	[IdUser] [uniqueidentifier] NOT NULL /******* PK *******/,
	[Name] [nvarchar](max) NOT NULL,
	[Surname] [nvarchar](max) NOT NULL,
	[...]
)

CREATE TABLE [dbo].[General_UserCustomer](
	[IdUser] [uniqueidentifier] NOT NULL /******* FOREIGN KEY FROM General_User *******/,
	[Address] [nvarchar](max) NOT NULL,
	[ZipCode] [nvarchar](max) NOT NULL,
	[City] [nvarchar](max) NOT NULL,
	[Province] [nvarchar](max) NULL,
	[Country] [nvarchar](max) NOT NULL,
	[PhoneNumber] [nvarchar](16) NOT NULL
)
```

The execution of:
`ControllerBase.CreatedAtAction([...]);`
returns infinite (or recursive) JSON output:

```
{
	"idUser": "5562486d-c4fa-4f16-88a1-2088afa1fe41",
	"name": "Edoardo",
	"surname": "Chiabra",
	"emailAddress": "usermail@test.com",
	"generalUserCustomer": {
		"idUser": "5562486d-c4fa-4f16-88a1-2088afa1fe41",
		"address": "UserAddress",
		"zipCode": "00100",
		"city": "Rome",
		"province": "RM",
		"country": "Italy",
		"phoneNumber": "+393334455666",
		"idUserNavigation": {
			"idUser": "5562486d-c4fa-4f16-88a1-2088afa1fe41",
			"name": "Edoardo",
			"surname": "Chiabra",
			"emailAddress": "usermail@test.com",
			"generalUserCustomer": {
				"idUser": "5562486d-c4fa-4f16-88a1-2088afa1fe41",
				"address": "UserAddress",
				"zipCode": "00100",
				"city": "Rome",
				"province": "RM",
				"country": "Italy",
				"citizenship": "Italy",
				"phoneNumber": "+393334455666",
				"idUserNavigation": {
					[...]
				}
			}
		}
	}
}
```

This is the method:
```
[HttpPost]
public async Task<ActionResult<GeneralUser>> CreateUserCustomer(UserCreatingCustomer customerUser)
{
    Guid newUserId = Guid.NewGuid();

    GeneralUser userToSubmit = new GeneralUser
    {
        IdUser = newUserId,
        Name = customerUser.Name,
        Surname = customerUser.Surname,
        EmailAddress = customerUser.EmailAddress
    };

    GeneralUserCustomer customerToSubmit = new GeneralUserCustomer
    {
        IdUser = newUserId,
        Address = customerUser.Address,
        ZipCode = customerUser.ZipCode,
        City = customerUser.City,
        Province = customerUser.Province,
        Country = customerUser.Citizenship,
        PhoneNumber = customerUser.PhoneNumber
    };

    _context.GeneralUser.Add(userToSubmit);
    _context.GeneralUserCustomer.Add(customerToSubmit);

    await _context.SaveChangesAsync();

    return CreatedAtAction("Get", new { id = userToSubmit.IdUser }, userToSubmit);
}
```

### Further technical details
EF Core Power Tools version: 2.4.0

Database engine: SQL Server 14.0.3281

Visual Studio version: Professional 2019 16.3.9

Target framework: .NET Core 3.1

**Comment by ErikEJ** [comment]
I generally do not think it is a good idea to expose your POCO tables objects directly. But yes, adding JsonIgnore solves the issue. Are you reporting a bug? Or a feature suggestion?

**Comment by echiabra** [comment]
Adding `[JsonIgnore]` to the model field unfortunately doesn't solve the problem, my mistake.

Outputting JSON throws an exception:
```
System.Text.Json.JsonException: A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerCycleDetected(Int32 maxDepth)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Indeed, adding this snippet to my `Startup.cs` file, solves the problem:
```
services.AddControllerWithViews().AddNewtonsoftJson(options =>
    options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
);
```
Ref: https://stackoverflow.com/questions/59199593/net-core-3-0-possible-object-cycle-was-detected-which-is-not-supported

So I don't think is an issue caused by your extension, my apologize.
