### ISSUE TITLE
Reverse Engineer: Handlebars templates (C#) with Turkish culture does not work (awaiting fix)

### ISSUE THREAD

**Issue by melihsen** [ErikEJ/EFCorePowerTools#366]
When I check the "Customize code using Handlebars Templates C#" option, it gives error on Output window and operation is not completed.

**System:**
Microsoft Visual Studio Community 2019 Version 16.5.2
EF Core Tools v2.4.18.0
**DB Engine :** SQL Server 2014 Express Edition
**Project Type:** ASP.Net Core 3.1 MVC
**DB:** NorthwindSlim

### Error Details in Output Window:

System.Exception: Reverse engineer error: 
HandlebarsDotNet.HandlebarsRuntimeException: Referenced partial name dbimports could not be resolved
   at HandlebarsDotNet.Compiler.PartialBinder.InvokePartialWithFallback(String partialName, BindingContext context, HandlebarsConfiguration configuration)
   at lambda_method(Closure , TextWriter , Object )
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.<>c__DisplayClass7_0.<Compile>b__0(Object context)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsDbContextTemplateService.GenerateDbContext(Object data)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpDbContextGenerator.WriteCode(IModel model, String contextName, String connectionString, String contextNamespace, String modelNamespace, Boolean useDataAnnotations, Boolean suppressConnectionStringWarning)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\efreveng\ReverseEngineer\ReverseEngineerRunner.cs:line 71
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 33

   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildResult(String output)
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput()
   at ReverseEngineer20.EfCoreReverseEngineer.LaunchExternalRunner(ReverseEngineerOptions options)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions, Boolean includeViews)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 235

**Comment by melihsen** [comment]
I have tried again at v2.4.20, The problem continues

**Error Details in Output Window:**

System.Exception: Reverse engineer error: 
HandlebarsDotNet.HandlebarsRuntimeException: Referenced partial name dbimports could not be resolved
   at HandlebarsDotNet.Compiler.PartialBinder.InvokePartialWithFallback(String partialName, BindingContext context, HandlebarsConfiguration configuration)
   at lambda_method(Closure , TextWriter , Object )
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.<>c__DisplayClass7_0.<Compile>b__0(Object context)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsDbContextTemplateService.GenerateDbContext(Object data)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpDbContextGenerator.WriteCode(IModel model, String contextName, String connectionString, String contextNamespace, String modelNamespace, Boolean useDataAnnotations, Boolean suppressConnectionStringWarning)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\efreveng\ReverseEngineer\ReverseEngineerRunner.cs:line 71
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 33

   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildResult(String output)
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput()
   at ReverseEngineer20.EfCoreReverseEngineer.LaunchExternalRunner(ReverseEngineerOptions options)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions, Boolean includeViews)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 235

**Comment by ErikEJ** [comment]
Please share your project - I am unable to repro

**Comment by ErikEJ** [comment]
Actually, try to temporarly rename your CodeTemplates folder!

**Comment by melihsen** [comment]
I prepared new .Net Core 3 Class library project for test and deleted CodeTemplates folder. I tried again. Tool recreated CodeTemplates folder automatically and then tool gave the same error. 

I share this test project:
[HandlebarTest.zip](https://github.com/ErikEJ/EFCorePowerTools/files/4469606/HandlebarTest.zip)

Thank you for all

**Comment by ErikEJ** [comment]
Sorry, unable to repro with 2.4.20 😢 - maybe @tonysneed has some ideas for what to try?

**Comment by melihsen** [comment]
I found the case. When I change windows region settings (datetime format) from Turkish to English (U.S), tool runs without a problem. 

**Region Settings:**
![RegionCompare](https://user-images.githubusercontent.com/25493160/79129761-73467400-7dae-11ea-8561-a4156b5f1b8e.png)

**Comment by ErikEJ** [comment]
Yes, I had already thought of that! It is sadly something that must be fixed in the handlebars library: https://www.logitblog.com/string-tolower-and-the-dotless-i/ - I have created an issue there; https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/104

**Comment by ErikEJ** [comment]
Version 3.7 published now

**Comment by ErikEJ** [comment]
@melihsen Fixed in latest daily build

**Comment by melihsen** [comment]
@ErikEJ 
Thank you for all
