### ISSUE TITLE
Install was not successful for all the selected products

### ISSUE THREAD

**Issue by miloshavlicek** [ErikEJ/EFCorePowerTools#374]
When I download plugin and try to install it, it throws an error.

### Steps to reproduce
- Download plugin from: https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools
- Install

### Further technical details
EF Core Power Tools version: 2.4.34
Visual Studio version: Microsoft Visual Studio Community 2019 16.4.6

![image](https://user-images.githubusercontent.com/2387790/79785760-ace62480-8344-11ea-861b-2c842c00e084.png)

#### Log:
```
4/20/2020 8:13:43 PM - Microsoft VSIX Installer
4/20/2020 8:13:43 PM - -------------------------------------------
4/20/2020 8:13:43 PM - vsixinstaller.exe version:
4/20/2020 8:13:43 PM - 16.5.2047
4/20/2020 8:13:43 PM - -------------------------------------------
4/20/2020 8:13:43 PM - Command line parameters:
4/20/2020 8:13:43 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\milos\Downloads\EFCorePowerTools2.4.34.vsix
4/20/2020 8:13:43 PM - -------------------------------------------
4/20/2020 8:13:43 PM - Microsoft VSIX Installer
4/20/2020 8:13:43 PM - -------------------------------------------
4/20/2020 8:13:44 PM - Found setup instance 5f6eecf4 but not in launchable state.
4/20/2020 8:13:44 PM - Skipping product Microsoft.VisualStudio.Product.BuildTools (b1c5f4a8) since it does not support extensions
4/20/2020 8:13:44 PM - Initializing Install...
4/20/2020 8:13:44 PM - Extension Details...
4/20/2020 8:13:44 PM - 	Identifier         : f4c4712c-ceae-4803-8e52-0e2049d5de9f
4/20/2020 8:13:44 PM - 	Name               : EF Core Power Tools
4/20/2020 8:13:44 PM - 	Author             : ErikEJ
4/20/2020 8:13:44 PM - 	Version            : 2.4.34
4/20/2020 8:13:44 PM - 	Description        : Useful design-time DbContext features, added to the Visual Studio Solution Explorer context menu.

When right-clicking on a C# project, the following context menu functions are available:
Reverse Engineer - Generates POCO classes, derived DbContext and Code First mapping for an existing database.
Migrations Tool - Manage EF Core Migrations in the project: View status, Add Migration, Update Database
Add DbContext Model Diagram - Adds a DGML graph from your DbContext Model.
View DbContext Model SQL DDL - View a SQL DDL script from your DbContext Model.
View Database Schema as Graph - Generates a DGML graph of your database schema, viewable in Visual Studio.
About - Displays version and other diagnostic information about your Visual Studio instance. 
        
4/20/2020 8:13:44 PM - 	Locale             : en-US
4/20/2020 8:13:44 PM - 	MoreInfoURL        : https://github.com/ErikEJ/EFCorePowerTools/wiki/Power-Tools
4/20/2020 8:13:44 PM - 	InstalledByMSI     : False
4/20/2020 8:13:44 PM - 	SupportedFrameworkVersionRange : [4.7.1,)
4/20/2020 8:13:44 PM - 
4/20/2020 8:13:44 PM - 	SignatureState     : Unsigned
4/20/2020 8:13:44 PM - 	Supported Products : 
4/20/2020 8:13:44 PM - 		Microsoft.VisualStudio.Community
4/20/2020 8:13:44 PM - 			Version : [15.0.27130.0,17.0)
4/20/2020 8:13:44 PM - 
4/20/2020 8:13:44 PM - 	References         : 
4/20/2020 8:13:44 PM - 	Prerequisites      : 
4/20/2020 8:13:44 PM - 		-------------------------------------------------------
4/20/2020 8:13:44 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
4/20/2020 8:13:44 PM - 		Name         : Visual Studio core editor
4/20/2020 8:13:44 PM - 		Version      : [15.0,)
4/20/2020 8:13:44 PM - 
4/20/2020 8:13:44 PM - Signature Details...
4/20/2020 8:13:44 PM - 	Extension is not signed.
4/20/2020 8:13:44 PM - 
4/20/2020 8:13:44 PM - Searching for applicable products...
4/20/2020 8:13:44 PM - Found installed product - Global Location
4/20/2020 8:13:44 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by ErikEJ** [comment]
Maybe try reparing your installation? What workloads do you have installed?

**Comment by miloshavlicek** [comment]
I have updated my VS to Version 16.5.4 and it works now. I am not able to reproduce this problem.

This is list of my workloads:
![image](https://user-images.githubusercontent.com/2387790/79845618-9c25c500-83bd-11ea-9cdd-99de17d1d4e1.png)
