### ISSUE TITLE
Update Reverse Engineering for EF Core 5

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#386]

**Comment by MrCalico** [comment]
System.ArgumentException: Error:
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Internal.DebugView`1<Microsoft.EntityFrameworkCore.Metadata.Internal.Model> Microsoft.EntityFrameworkCore.Metadata.Internal.Model.get_DebugView()'.
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl)
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 72

**Comment by ErikEJ** [comment]
@MrCalico Thanks, that is not reverse engineering, but yes, there is a breaking change there!

**Comment by MrCalico** [comment]
Sorry about the wrong post subject.  Should I wait for a while for a fix? Is there a correct message thread somewhere to watch for a fix?  I really wanted to try this after watching one of Lerman's videos.  --Thanks!

**Comment by ErikEJ** [comment]
Modelling with EF Core 5 preview 5 enabled in latest daily build.

**Comment by ErikEJ** [comment]
Fixed for EF Core 5 preview 6 in latest daily, need updates and testing at RTM time.
