### ISSUE TITLE
Cannot create any diagram Error with Ghost Path

### ISSUE THREAD

**Issue by HugoDoyon** [ErikEJ/EFCorePowerTools#422]
Describe what is not working as expected.

Amazing tool but cannot make it work in my .net core 3 project. 

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

right click on the project > EF Core Power Tools > Choose Add dbContext model diagram 

Then I get the following error with a ghost path not available on my computer:

========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at EFCorePowerTools.Extensions.ProjectExtensions.GenerateFiles(Project project, List`1 result, String extension) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\ProjectExtensions.cs:line 178
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 92

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.4.51.0

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
Postgres

Visual Studio version: (e.g. Visual Studio 2017 15.7)
2019 comunity

**Comment by ErikEJ** [comment]
What is a "ghost path" ??

**Comment by HugoDoyon** [comment]
those 2 path do not exist anywhere on my desktop:
C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 92
C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\ProjectExtensions.cs:line 178

**Comment by ErikEJ** [comment]
That is just debug info. 

What is the path to your project?

**Comment by HugoDoyon** [comment]
All my projects are in a totally different path: C:\Users\Hugo\Documents\GitHub\

**Comment by ErikEJ** [comment]
Please share the full path to the failing project and the name of your DbContext.

**Comment by HugoDoyon** [comment]
C:\Users\Hugo\Documents\GitHub\PlayListGenerator

DbContext: PlayListContext

**Comment by ErikEJ** [comment]
What does  Path.GetTempPath() and/or %TEMP% point to on your machine?

**Comment by HugoDoyon** [comment]
%TEMP% = C:\Users\Hugo\AppData\Local\Temp

**Comment by ErikEJ** [comment]
Hmmm... Can you share (privately) a repro project?

**Comment by HugoDoyon** [comment]
Unfortunatly I can'nt for this one, but my guess will be to add more padding before creating the path. 

Some illegal caracters might felt in before the Path.Combine() in ModelAnalyzerHandler.cs. Simply allowing valid char in modelResult could work (A-z0-1) potentially

I get a similar error when calling generate DGML: 

System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateDgml(List`1 modelResult, Project project) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 117
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 80

while generate ddl sql give me : 

System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateDgml(List`1 modelResult, Project project) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 117
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 80

**Comment by ErikEJ** [comment]
I have added better error handling to the latest daily build, please try that and let me know the result.

**Comment by HugoDoyon** [comment]
Update it and tried again: error is the same on my side. 

As per the error stack it seem to crash at path.combine. So I will never reach the new line you added : "if (filePath.IndexOfAny(Path.GetInvalidPathChars()) >= 0)"

**Comment by ErikEJ** [comment]
Sorry, updated! 😄

**Comment by HugoDoyon** [comment]
![Capturea](https://user-images.githubusercontent.com/17368121/87038025-26aae300-c1bb-11ea-9ebd-4088326eafa3.JPG)

I have indeed EnableSensitiveDataLogging(true);

**Comment by ErikEJ** [comment]
Perfect! I have attempted a fix in the latest daily build (build 2.4.112 or later)

**Comment by HugoDoyon** [comment]
Is there a way to make this work with  EnableSensitiveDataLogging(), my guess is there will be a lot of people using EF Power Tool in Dev environment with this setting set to true? Otherwise when I disable this flag I can generate the DGML file

**Comment by ErikEJ** [comment]
yes, try the latest daily build

**Comment by HugoDoyon** [comment]
Fixed Marvelous! Thank you Erik 🥇

**Comment by ErikEJ** [comment]
You are welcome, If you like my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools#review-details

**Comment by HugoDoyon** [comment]
Will do! 

Denmark and Canada are really close, we might meet each other one day in Microsoft Conference ;) We should follow each other on GitHub as well!

**Comment by HugoDoyon** [comment]
rated
