### ISSUE TITLE
ORA-00942 when RevEng

### ISSUE THREAD

**Issue by mariohik** [ErikEJ/EFCorePowerTools#426]
I upgraded to the latest version of ODP.NET (19.3.1.0) and its EFCore Power Tools (2.4.120).
Now I get the following exception:
```
System.Exception: Table list error:
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00942: the table or view does not exist
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution (Int32 & cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException & exceptionForArrayBindDML, BooleanDool, Boolean & StR
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader (String commandText, OracleParameterCollection paramColl, CommandType CommandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl & rdrImpl, longFetchSize Int32, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64 [] scnForExecution, Int64 [] & scnFromExecution, OracleParameterCollection & bindByPositionParamColl, Boolean & bBindParamPresent, Int64 & internalInitialLOBFS, OracleException & exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction & oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader (Boolean requiry, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader (CommandBehavior behavior)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.GetTablesCombined (DbConnection connection, Func`3 tableFilter, DatabaseModel databaseModel, Func`2 schemaFilter, List`1 paramList)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create (DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create (DbConnection connection, DatabaseModelFactoryOptions options)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create (String connectionString, DatabaseModelFactoryOptions options)
   at ReverseEngineer20.TableListBuilder.GetTableDefinitions () in C: \ Code \ EFCorePowerTools \ src \ GUI \ RevEng.Core \ TableListBuilder.cs: line 39
   at efreveng.Program.Main (String [] args) in C: \ Code \ EFCorePowerTools \ src \ GUI \ efreveng \ Program.cs: line 28

   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildTableResult (String output) in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineer \ EfRevEngLauncher.cs: line 156
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal (String arguments) in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineer \ EfRevEngLauncher.cs: line 57
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTables (String connectionString, DatabaseType databaseType) in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineer \ EfRevEngLauncher.cs: line 33
   at ReverseEngineer20.TableListBuilder.GetTableDefinitions (Boolean useEFCore5) in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineer \ TableListBuilder.cs: line 30
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTables (String connectionString, DatabaseType databaseType, Boolean useEFCore5) in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineerHandler.cs: line 335
   at EFCorePowerTools.Handlers.ReverseEngineerHandler. <ReverseEngineerCodeFirst> d__3.MoveNext () in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineerHandler.cs: line 93
```

**Comment by mariohik** [comment]
This bug was introduced by Oracle.EntityFrameworkCore -Version 3.19.0-beta2.
I forked your project and downgraded to Oracle.EntityFrameworkCore -Version 3.19.0-beta1 on the project RevEng.Core and could retrieve the tables.

**Comment by ErikEJ** [comment]
See if you can reproduce with Scaffold-DbContext from Package Manager Console

**Comment by ErikEJ** [comment]
If you can, you should file a bug report with Oracle

**Comment by ErikEJ** [comment]
I am suspecting an Oracle bug, as I am simply getting a list of everything (no filtering)

            var dbModel = dbModelFactory.Create(_connectionString, new DatabaseModelFactoryOptions());

(so the list of tables and schemas is null)

@alexkeh FYI :smile:

**Comment by alexkeh** [comment]
Between Beta 1 and Beta 2, the scaffolding support was modified when table and schema filters were added. In Beta 1, the provider would scaffold only the specific tables in the specific schemas. In Beta 2, the provider would scaffold all the specified tables/views within current schema AND all tables/views in specified schemas. The new behavior is in line with SQL Server's EF Core provider behavior.

**Comment by ErikEJ** [comment]
@alexkeh thanks for the info - but that does not explain why the provider throws an error - imagine if the provider was open source, then the community could assist! 

As you can see, I simple call Create with null lists for tables and schemas.

**Comment by alexkeh** [comment]
One of my dev team members tried to reproduce the error. He first tried
`var dbModel = dbModelFactory.Create(_connectionString, options);`
with various possible combinations of table and schema filters (no filter, only table filter, only schema filter, table and schema filter). None of the scenarios generated this error.

He tried reproducing with the EF Core Power Tools. However, he couldn't get the Oracle connection to show up in the drop down box after selecting the Reverse Engineer option.

@mariohik 
Can you try running the ‘Scaffold-DbContext’ command from package manager console or ‘dotnet ef dbcontext scaffold’ command from the command prompt? If the issue reproduces, can you provide the complete traces. Traces are enabled using the ‘verbose’ option in the above commands.

Also, which Oracle DB are you using?

**Comment by ErikEJ** [comment]
@alexkeh  did he try with just "new Options" ??

**Comment by ErikEJ** [comment]
@alexkeh The Oracle developer tools must be installed, see the wiki.

**Comment by alexkeh** [comment]
@ErikEJ Oracle Developer Tools were installed. I'll ask him about the "New Options" setting.

**Comment by ErikEJ** [comment]
I meant just calling the method with "new DatabaseModelFactoryOptions()"

**Comment by ErikEJ** [comment]
If the developer tools are broken, you know who to call!

**Comment by mariohik** [comment]
@alexkeh I ran the command without success in version 3.19.0-beta2:
```
Scaffold-DbContext "Data Source = xxxx; User Id = xxxx; Password = xxxx;" Oracle.EntityFrameworkCore -Context ApplicationDbContext -ContextDir Context -OutputDir Entities -Force -DataAnnotations -Tables PROCESSO
```

```
2020-07-20 12:48:38.772339 ThreadID:1   (ERROR)   OracleDatabaseModelFactory.GetTablesCombined() :  Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00942: a tabela ou view não existe
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.GetTablesCombined(DbConnection connection, Func`3 tableFilter, DatabaseModel databaseModel, Func`2 schemaFilter, List`1 paramList)
2020-07-20 12:48:38.869663 ThreadID:1   (ERROR)   OracleDatabaseModelFactory.Create() :  Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00942: a tabela ou view não existe
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.GetTablesCombined(DbConnection connection, Func`3 tableFilter, DatabaseModel databaseModel, Func`2 schemaFilter, List`1 paramList)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00942: a tabela ou view não existe
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.GetTablesCombined(DbConnection connection, Func`3 tableFilter, DatabaseModel databaseModel, Func`2 schemaFilter, List`1 paramList)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ORA-00942: a tabela ou view não existe
```

The same command in version 3.19.0-beta1 works normally.

**Comment by ErikEJ** [comment]
@mariohik you should not include the -Tables option - otherwise you are not testing the same issue.

**Comment by mariohik** [comment]
I tried the follow command (without the -Tables option) but the error still occurs
```
Scaffold-DbContext "Data Source=xxxx;User Id=xxxx;Password=xxxx;" Oracle.EntityFrameworkCore -Context ApplicationDbContext -ContextDir Context -OutputDir Entities -Force -DataAnnotations
```

**Comment by ErikEJ** [comment]
Perfect, that certainly points to an issue with the Oracle provider.

**Comment by alexkeh** [comment]
I can reproduce the error now. Thanks for the test case. My team will investigate.

**Comment by alexkeh** [comment]
I filed bug 31645113. After some more investigation, it appears that the error @ErikEJ found and @mariohik found are two different issues. 

I only reproduced an error when creating the model factory when either the Tables or Schemas parameter was an empty string. 

When I ran the Scaffold-DbContext commands, I was able to successfully run both commands with the beta 2. There may be something particular in the schema itself that causes the bug to occur.

@mariohik Can you provide the verbose trace by adding "-v" to end of your Scaffold-DbContext command? If you don't feel comfortable posting the trace on GitHub, you can email it to us dotnet_us(at)oracle.com.

**Comment by alexkeh** [comment]
@mariohik Also, which DB version are you running?

**Comment by mariohik** [comment]
@alexkeh 

Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
"CORE	11.2.0.4.0	Production"
TNS for IBM/AIX RISC System/6000: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production

**Comment by mariohik** [comment]
@alexkeh 
Email sent.

**Comment by alexkeh** [comment]
@mariohik We got your trace. Thanks! We'll review and see what we find.

**Comment by alexkeh** [comment]
@mariohik I've opened bug 31645329 to track your particular issue.

**Comment by mariohik** [comment]
@alexkeh Thank you!

**Comment by alexkeh** [comment]
@ErikEJ My team tested empty string values for the Schemas and Tables parameters using DatabaseModelFactoryOptions against both Oracle DB and SQL Server. In both cases, we see an error. When we run the same test with null values, we don't encounter any errors.

**Comment by ErikEJ** [comment]
@alexkeh my guess is then that the error reported is schema/user database specific.

**Comment by alexkeh** [comment]
@mariohik It appears one or more of the following tables your user queries is not available to access: ‘user_tables’, ‘user_mviews’, ‘user_views’ and ‘user_xml_tables’. Can you log in as the same user, then query each of these tables to verify read privileges?

**Comment by mariohik** [comment]
@alexkeh 
```
select * from user_xml_tables;
```
```
ORA-00942: a tabela ou view não existe
00942. 00000 -  "table or view does not exist"
*Cause:    
*Action:
```

**Comment by ErikEJ** [comment]
@alexkeh maybe your code should be more tolerant to this, and log warnings ?

**Comment by alexkeh** [comment]
@mariohik We understand the root cause now and will fix it for production. Thanks for your responsiveness!

@ErikEJ I've communicated your recommendation to the dev team.

**Comment by alexkeh** [comment]
@ErikEJ Do you have any recommendations for provider vendors, such as Oracle, to test/certify with EF Core Power Tools whenever we release a new version?

**Comment by ErikEJ** [comment]
@alexkeh not really, and support for Oracle in EF Core Power Tools is brand new. In addition, I have no clue about Oracle schema and PL/SQL

**Comment by ErikEJ** [comment]
@alexkeh looking forward to an updated provider
