### ISSUE TITLE
Getting TLS 1.0 error when reverse engineering

### ISSUE THREAD

**Issue by tonnilay** [ErikEJ/EFCorePowerTools#445]
this is the error from VS 2019 

System.Exception: Table list error: Unable to launch external process: Security Warning: The negotiated TLS 1.0 is an insecure protocol and is supported for backward compatibility only. The recommended protocol version is TLS 1.2 and later.
Result:
[

xxx table name / view 
.
.
.
xxx table name
]

at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildTableResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 159
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 57
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 33
   at ReverseEngineer20.TableListBuilder.GetTableDefinitions(Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\TableListBuilder.cs:line 30
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTables(String connectionString, DatabaseType databaseType, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 345
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 92

I am using latest daily build 2.4.141 version.

**Comment by ErikEJ** [comment]
Which SQL Server version?

**Comment by tonnilay** [comment]
2012 i believe

**Comment by ErikEJ** [comment]
OK, this warning from Microsoft.Data.SqlClient causes the parsing of the table list to fail. I will look into making the parsing more robust. 

Maybe you should also consider upgrading to TLS 1.2 on your  SQL instance?

**Comment by ErikEJ** [comment]
Need to fix build issue.

**Comment by krstickr** [comment]
I have exactly same problem.

**Comment by ErikEJ** [comment]
@krstickr thanks for info, working on a fix right now

**Comment by ErikEJ** [comment]
Facing some build issues, you can download an older version of the extension from here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes#24140-august-6-2020

**Comment by ErikEJ** [comment]
Attempted a fix in latest daily build
