### ISSUE TITLE
I need an old version...how do I get it?

### ISSUE THREAD

**Issue by Moorepheus** [ErikEJ/EFCorePowerTools#456]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2017 15.7)

**Comment by ErikEJ** [comment]
May I ask why?

**Comment by Moorepheus** [comment]
Because we are still using EFCore 2.2.6.. The latest release is having issues finding files, that i have never needed before.

**Comment by Moorepheus** [comment]
`File name: 'C:\DEV\NtsSharedLibrary\EFCoreContext\NtsCounty.20.1.7390\Nts.Data.NtsCounty\CodeTemplates\CSharpDbContext\Partials\DbOnConfiguring.hbs'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at EntityFrameworkCore.Scaffolding.Handlebars.Internal.FileSystemFileService.RetrieveFileContents(String directoryName, String fileName)
   at ReverseEngineer20.ReverseEngineer.CustomTemplateFileService.RetrieveTemplateFileContents(String relativeDirectory, String fileName, String altRelativeDirectory) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\CustomTemplateFileService.cs:line 21
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsDbContextTemplateService.GetPartialTemplates(LanguageOptions language)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsTemplateService.RegisterPartialTemplates()
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 89
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 57

   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 135
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 79
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 380
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 224`

**Comment by Moorepheus** [comment]
So, I just added the file, keeping it empty.

Now, it builds but everything, from what I can tell, is looking for EFCORE 3.0 functionality...Like I said, we are still using 2.2.6

**Comment by ErikEJ** [comment]
Have a look at the release notes - assume you are aware that 2.2 is no longer supported?

**Comment by Moorepheus** [comment]
While I understand that 2.2 is no longer supported, we are still using it as we are not ready to support 3.x You made a change that impacts our ability to support our products as necessary changes are needed.   I guess we will have to look for a different product to help us with this until we can move out EFCore 2.2.

Thanks for a great tool.

**Comment by ErikEJ** [comment]
As I said, the release notes has a link to an older version. 

Pleased that you appreciate this free, open source tool.

**Comment by Moorepheus** [comment]
Thanks for the installer…..

Get following:


System.IO.FileNotFoundException: Could not load file or assembly 'EntityFrameworkCore.Scaffolding.Handlebars, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b10b51e7b9be6a2e' or one of its dependencies. The system cannot find the file specified.
File name: 'EntityFrameworkCore.Scaffolding.Handlebars, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b10b51e7b9be6a2e'
   at ReverseEngineer20.ServiceProviderBuilder.Build(ReverseEngineerOptions options)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions, Boolean includeViews)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 242

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

————————————————
Mark Moore
Director of Software Development
[cid:image001.png@01D4767F.BDABBCE0]

NTS Data Services, LLC
2079 Sawyer Rd
Niagara Falls, NY 14304
NTSDATA.COM<ntsdata.com>
800.458.3820 x303

**Comment by ErikEJ** [comment]
Suspecting that the newer version was not properly removed/uninstalled.

**Comment by ErikEJ** [comment]
Check your C:\Users\xxx\AppData\Local\Microsoft\VisualStudio folder

**Comment by Moorepheus** [comment]
I am there, but I am not seeing anything related to EF Power Tools.

Thanks for the help on this..

————————————————
Mark Moore
Director of Software Development
[cid:image001.png@01D4767F.BDABBCE0]

NTS Data Services, LLC
2079 Sawyer Rd
Niagara Falls, NY 14304
NTSDATA.COM<ntsdata.com>
800.458.3820 x303

**Comment by ErikEJ** [comment]
1: Look for EntityFrameworkCore.Scaffolding.Handlebars in the subfolders.

2: Try installing on another PC /VM

**Comment by Moorepheus** [comment]
Uninstalled it again

Did the search, nothing found related to EntityFrameworkCore.Scaffolding.Handlebars

Re-installed

Did the search again

Nothing found….

————————————————
Mark Moore
Director of Software Development
[cid:image001.png@01D4767F.BDABBCE0]

NTS Data Services, LLC
2079 Sawyer Rd
Niagara Falls, NY 14304
NTSDATA.COM<ntsdata.com>
800.458.3820 x303

**Comment by ErikEJ** [comment]
Hmmm... I will give it a try myself.

**Comment by ErikEJ** [comment]
Seems the download was broken - linked to another one - also makes sure to disable auto-update in Extension manager.

**Comment by Moorepheus** [comment]
Ok, downloading new VSIX file..

Thanks



————————————————
Mark Moore
Director of Software Development
[cid:image001.png@01D4767F.BDABBCE0]

NTS Data Services, LLC
2079 Sawyer Rd
Niagara Falls, NY 14304
NTSDATA.COM<ntsdata.com>
800.458.3820 x303

**Comment by Moorepheus** [comment]
Thanks, I really like this tool

Our plan is to move all our products up to latest EFCORE at the beginning of the year, just need this short term solution.

Thanks

————————————————
Mark Moore
Director of Software Development
[cid:image001.png@01D4767F.BDABBCE0]

NTS Data Services, LLC
2079 Sawyer Rd
Niagara Falls, NY 14304
NTSDATA.COM<ntsdata.com>
800.458.3820 x303

**Comment by Moorepheus** [comment]
Everything working again, thank you again




————————————————
Mark Moore
Director of Software Development
[cid:image001.png@01D4767F.BDABBCE0]

NTS Data Services, LLC
2079 Sawyer Rd
Niagara Falls, NY 14304
NTSDATA.COM<ntsdata.com>
800.458.3820 x303

From: Mark Moore
Sent: Tuesday, August 11, 2020 3:25 PM
To: ErikEJ/EFCorePowerTools <reply@reply.github.com>; ErikEJ/EFCorePowerTools <EFCorePowerTools@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [ErikEJ/EFCorePowerTools] I need an old version...how do I get it? (#456)

Ok, downloading new VSIX file..

Thanks



————————————————
Mark Moore
Director of Software Development
[cid:image001.png@01D4767F.BDABBCE0]

NTS Data Services, LLC
2079 Sawyer Rd
Niagara Falls, NY 14304
NTSDATA.COM<ntsdata.com>
800.458.3820 x303

**Comment by Moorepheus** [comment]
I know this is closed...however I need the visual studio installer for version 2.4.51.0   I have two employees that will be taken over for me while I am out for cancer treatment.   I know the version of EFCore that we are using is no longer supported, but at this time, we don't have the time or resources to rebuild our projects to support the latest EFCore.  Once I recover from my treatments, it will be come a priority. I love this tool, it does what we need.   

I know in your release notes, you had a link for a version that support EFCore 2.2.6, but the link doesn't work.   I need Version 2.4.51.0.  It is very important that make sure this works for the employees that will be doing this work before I leave.

Thank You.

**Comment by Moorepheus** [comment]
Okay, just to check again in your release notes, I went to the link and it worked.  Sorry to bother you.  

Have a great day.
