### ISSUE TITLE
Reverse Engineer Fail on Zip Issue

### ISSUE THREAD

**Issue by jonathandotchin** [ErikEJ/EFCorePowerTools#457]
When attempting to reverse engineer, an zip issue is displayed in the output window.

System.IO.InvalidDataException: Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.
   at System.IO.Compression.ZipArchive.ReadCentralDirectory()
   at System.IO.Compression.ZipArchive.get_Entries()
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.DropNetCoreFiles() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 137
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 45
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 35
   at EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitions(Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\TableListBuilder.cs:line 31
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTables(String connectionString, DatabaseType databaseType, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 346
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 93

The issue is preventing the reverse engineer to move forward.

### Steps to reproduce
Checkout entire project
Right Click on Project
Select EF Core Power Tools
Select Reverse Engineer
Select OK (Correct DB Connection)
Notice error message in output window

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.4.155

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL Server

Visual Studio version: (e.g. Visual Studio 2017 15.7)
Visual Studio 2019 16.7.1

**Comment by NewCity499** [comment]
Same error, same steps to reproduce.
Visual Studio 2019 Preview 16.8.0

**Comment by ErikEJ** [comment]
Sorry for the inconvenience, build 156 with a fix has been published to MarketPlace
