### ISSUE TITLE
Reverse engineer - multiple foreign keys to same table

### ISSUE THREAD

**Issue by MichaelKueh** [ErikEJ/EFCorePowerTools#459]
In our database we have some tables which has two foreign keys to the same table.

Here is an example of what I mean: Lets assume we have a table for persons and a table for workspaces. Each person has two correspondig workspaces (primary and secondary). In this case I have two foreign keys from the table person to the table workspace.

EF Core Power Tools version: 2.4.156.0
Database engine: SQL Server
Visual Studio 2017

If i try to reverse such tables with the GUI I get the following error output:

> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 15
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 81
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 381
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 225

To be sure that the problem is related to the foreign keys I executed `efreveng.exe` directly and got the following output:

> Error:
System.InvalidOperationException: The foreign key {'Z'} cannot be added to the entity type 'A' because a foreign key on the same properties already exists on entity type 'A' and also targets the key {'Z'} on 'ZS'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.Validate(IReadOnlyList`1 properties, Key principalKey, EntityType declaringEntityType, EntityType principalEntityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey..ctor(IReadOnlyList`1 dependentProperties, Key principalKey, EntityType dependentEntityType, EntityType principalEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddForeignKey(IReadOnlyList`1 properties, Key principalKey, EntityType principalEntityType, Nullable`1 componentConfigurationSource, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.AddForeignKey(IReadOnlyList`1 properties, IMutableKey principalKey, IMutableEntityType principalEntityType)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKey(ModelBuilder modelBuilder, DatabaseForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 89
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 57

This looks to me that the Entity Framework Core built-in scaffolding is the limiting factor here, as I get the exact same message if I try scaffolding via `dotnet ef dbcontext scaffold`.

Is there a possibility to overcome that limitation?

**Comment by ErikEJ** [comment]
Remove the duplicate foreign key?

**Comment by ErikEJ** [comment]
But is is a bug that I do not show you the actual error message!

**Comment by MichaelKueh** [comment]
Each foreign key has its own meaning, as the source column is different. I also need two different navigation properties.

**Comment by ErikEJ** [comment]
I think you need to share a repro, and potentially file a bug with the EF Core repoistory.

**Comment by ErikEJ** [comment]
I think the issue may be something else than you are expecting, so I need to have a look at your full DB schema to be sure.

**Comment by MichaelKueh** [comment]
I have created an [example repo](https://github.com/MichaelKueh/EFCoreScaffold). In the example the error with EF Core Power Tools occurs either with the Database-Project or the Local-DB as source. The entity framework scaffold tool also throws the error.

**Comment by ErikEJ** [comment]
This is a duplicate foreign key:

    CONSTRAINT [FK_Persons_Workspace_Primary] FOREIGN KEY ([PrimaryWorkspaceId]) REFERENCES [dbo].[Workspaces]([Id]),
	CONSTRAINT [FK_Persons_Workspace_Secondary] FOREIGN KEY ([PrimaryWorkspaceId]) REFERENCES [dbo].[Workspaces]([Id])

Should it not have been:

    CONSTRAINT [FK_Persons_Workspace_Primary] FOREIGN KEY ([PrimaryWorkspaceId]) REFERENCES [dbo].[Workspaces]([Id]),
	CONSTRAINT [FK_Persons_Workspace_Secondary] FOREIGN KEY ([SecondaryWorkspaceId]) REFERENCES [dbo].[Workspaces]([Id])

**Comment by MichaelKueh** [comment]
The funny thing is that the copied source column in the example was unintended. I wanted to use 

> 	CONSTRAINT [FK_Persons_Workspace_Primary]	FOREIGN KEY ([PrimaryWorkspaceId]) REFERENCES [dbo].[Workspaces]([Id]),
	CONSTRAINT [FK_Persons_Workspace_Secondary] FOREIGN KEY ([SecondaryWorkspaceId]) REFERENCES [dbo].[Workspaces]([Id])

After a detailed look at our application I found two duplicate foreign keys. After removing them everything worked! Thank you for your very fast and great support!
