### ISSUE TITLE
Reverse engineer failure

### ISSUE THREAD

**Issue by karenpayneoregon** [ErikEJ/EFCorePowerTools#465]
Using Visual Studio 2017 15.9.18, Entity Framework Core 3.1.5 or 3.1.7 performing a reverse engineer I get

``
System.MissingMethodException: Method not found: 'System.IO.Compression.ZipArchive System.IO.Compression.ZipFile.Open(System.String, System.IO.Compression.ZipArchiveMode)'.
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.DropNetCoreFiles()
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 43
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 33
   at ReverseEngineer20.TableListBuilder.GetTableDefinitions(Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\TableListBuilder.cs:line 30
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTables(String connectionString, DatabaseType databaseType, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 345
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 92
``

Describe what is not working as expected.

### Steps to reproduce
Both ,NET Core and regular class projects this happens on

- First installed EF Core for SQL-Server
- Right click, select reverse engineer
- Select database
- Above error message appears

Also note I've reverse engineered several project found here in the following [GitHub repo](https://github.com/karenpayneoregon/NorthWind-2020) and this is the same solution used above.

### Further technical details
EF Core Power Tools version: 
Version 2.4.140.0

SQLite ADO.NET Provider included: 1.0.99.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine:  SQL Server

Visual Studio 2017 15.9.18

Project type, class project with .NET Framework 4.7.2

**Comment by ErikEJ** [comment]
Seems like a VS binding redirect issue, try to update to latest VS 2017 version, or try VS 2019. https://github.com/dotnet/runtime/issues/24987

**Comment by ErikEJ** [comment]
You should also update EF Core Power Tools to latest release, pls.

**Comment by karenpayneoregon** [comment]
I restarted Visual Studio and now the reverse engineering is working. I have another issue which I will post in a minute.
