### ISSUE TITLE
Scaffolding throws exception when stored procedure has table type parameter

### ISSUE THREAD

**Issue by tjackadams** [ErikEJ/EFCorePowerTools#478]
When a stored procedure has a parameter of a user defined table type, the scaffold fails.

```
System.Exception: Reverse engineer error: 
System.ArgumentException: Requested value 'table type' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at RevEng.Core.SqlServerStoredProcedureExtensions.GetSqlDbType(String storeType) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureExtensions.cs:line 33
   at RevEng.Core.SqlServerStoredProcedureExtensions.GetClrType(String storeType, Boolean isNullable) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureExtensions.cs:line 50
   at RevEng.Core.SqlServerStoredProcedureExtensions.ClrType(ProcedureParameter storedProcedureParameter) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureExtensions.cs:line 13
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.<GenerateProcedure>b__8_2(ProcedureParameter p) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 156
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.JoinCore[T](Char* separator, Int32 separatorLength, IEnumerable`1 values)
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.GenerateProcedure(Procedure procedure) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 169
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.WriteProcedureDbContext(ProcedureScaffolderOptions procedureScaffolderOptions, ProcedureModel model) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 135
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.ScaffoldModel(String connectionString, ProcedureScaffolderOptions procedureScaffolderOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 52
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 81
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 62

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 27
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 86
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 386
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 230
```

If this is already being tracked elsewhere then apologies, but I couldn't find anything in this or the ef core repository in relation to this. I have created a simple demo project to reproduce this issue.

### Steps to reproduce

Reproduction: https://github.com/tjackadams/StoredProcScaffold

1. Publish Database project.
2. Furniture.Shop > EF Core Power Tools > Reverse Engineer
3. select Generate stored procedure mappings (preview)

### Further technical details
Version 2.4.172.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: MSSQL 

Visual Studio version: Visual Studio 2019 16.7.2

**Comment by ErikEJ** [comment]
It is not tracked elsewhere, and thanks for the repro and stack trace.

**Comment by ErikEJ** [comment]
I have attempted a fix for this in the latest daily build, please let me know if it works for you.

**Comment by tjackadams** [comment]
Thanks for the quick reply on this one @ErikEJ 

The stored procedures scaffold ok now, but when you execute the stored procedure an exception is thrown.

```
System.ArgumentException
  HResult=0x80070057
  Message=The table type parameter 'Shipments' must have a valid type name.
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.<InitializeReaderAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToArrayAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DbContextExtensions.<SqlQuery>d__0`1.MoveNext() in C:\Source\Repos\StoredProcScaffold\TableAndChairs\Furniture.Shop\Data\DbContextExtensions.cs:line 14
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Furniture.Shop.Data.FurnitureContextProcedures.<GetShipments>d__2.MoveNext() in C:\Source\Repos\StoredProcScaffold\TableAndChairs\Furniture.Shop\Data\FurnitureContextProcedures.cs:line 29
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Furniture.Shop.Program.<Main>d__0.MoveNext() in C:\Source\Repos\StoredProcScaffold\TableAndChairs\Furniture.Shop\Program.cs:line 26

  This exception was originally thrown at this call stack:
    [External Code]
    DbContextExtensions.SqlQuery<T>(Microsoft.EntityFrameworkCore.DbContext, string, object[]) in DbContextExtensions.cs
    [External Code]
    Furniture.Shop.Data.FurnitureContextProcedures.GetShipments(System.Data.DataTable) in FurnitureContextProcedures.cs
    [External Code]
    Furniture.Shop.Program.Main(string[]) in Program.cs
```

The issue seems to be the TypeName of the TVP is missing when generating the SqlParameter

```csharp
            var parameterShipments = new SqlParameter
            {
                ParameterName = "Shipments",
                SqlDbType = System.Data.SqlDbType.Structured,
                Value = Shipments,
            };
```

I have opened a PR https://github.com/ErikEJ/EFCorePowerTools/pull/485 to attempt a fix.

**Comment by ErikEJ** [comment]
@tjackadams 
 Excellent, if you run BuildCmdlineTool.cmd in the efreveng folder in the solution, you should be able to verify the fix - or have you already verified by doing manual changes?

**Comment by tjackadams** [comment]
@ErikEJ 

I initially verified by manual changes, but I've just done the BuildCmdlineTool.cmd and copied the .zip files over to my extension directory and it seems to be working ok. You'll see in the PR that I didn't quote the TypeName, but I've pushed a fix for that now.

**Comment by ErikEJ** [comment]
Fixed in latest daily build, thanks for the PR!
