### ISSUE TITLE
error when attempt to reverse engineer

### ISSUE THREAD

**Issue by knot22** [ErikEJ/EFCorePowerTools#480]
### Description of what is not working as expected
The following error is displayed in the Output window of Visual Studio when an attempt is made to run Reverse Engineer on a project.  The strange thing is, it used to work fine on this machine.  I haven't had to Reverse Engineer anything for approximately a month and now this error is occurring.

```
System.Exception: Table list error: Unable to launch external process: 

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 50
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 59
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 35
   at EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitions(Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\TableListBuilder.cs:line 31
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTables(String connectionString, DatabaseType databaseType, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 346
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 93
```
I looked for `C:\projects` on my machine but there is no `projects` folder in `C:`.

### Steps to reproduce
1. right click on project in Solution Explorer of Visual Studio, select EF Core Power Tools > Reverse Engineer
2. verify that database connection is the correct one, then click OK
**above error occurs after step 2**

### Further technical details
EF Core Power Tools version: 2.4.157.0

Database engine: MS SQL Server 2014 (SP3-CU-GDR)

Visual Studio version: MS Visual Studio Professional 2019 Version 16.3.8

**Comment by ErikEJ** [comment]
Do you have the .NET Core 3.1 x64 runtime/SDK installed?

**Comment by ErikEJ** [comment]
Can you launch efreveng.exe for the %temp%\efreveng folder?

**Comment by knot22** [comment]
`dotnet --info` gave the following output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```
There is no folder called `efreveng` in C:\Users\knot22\AppData\Local\Temp.

**Comment by ErikEJ** [comment]
You need to install .NET Core 3.1 x64, look at the wiki for a link.

**Comment by knot22** [comment]
Installing .NET Core 3.1 x 64 corrected the issue.  Thank-you for the solution and for your speedy responses.
