### ISSUE TITLE
Reverse engineering failure

### ISSUE THREAD

**Issue by karenpayneoregon** [ErikEJ/EFCorePowerTools#494]
The following seems to happen before but unsure what the resolution was. Below was first done with a .NET Core 2.2 class project then as per below a conventional class project.

Also have tried this in two different VS solutions.

### Steps to reproduce
Create a class project targeting Framework 4.72, add Entity Framework Core 3.1.8, right click on project in Solution Explorer, build project then select reverse engineer, select database, click Okay and get

System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
   at EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder..ctor(String connectionString, DatabaseType databaseType, SchemaInfo[] schemas) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\TableListBuilder.cs:line 19
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTables(String connectionString, DatabaseType databaseType, Boolean useEFCore5, SchemaInfo[] schemas) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 350
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 98

### Further technical details
EF Core Power tools

Version 2.4.182.0

SQLite ADO.NET Provider included: 1.0.99.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQL Server

Visual Studio version: (e.g. Visual Studio 2017 15.7)
Microsoft Visual Studio Enterprise 2017 
Version 15.9.18
VisualStudio.15.Release/15.9.18+28307.960
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

**Comment by ErikEJ** [comment]
I am not able to repro, try to remove the database connection (via Server Explorer) and re-create.

**Comment by karenpayneoregon** [comment]
I deleted the connection, recreated and attempted a reverse engineer, same issue.

**Comment by karenpayneoregon** [comment]
Also, just tried five different databases, all fail to reverse engineer

**Comment by ErikEJ** [comment]
I am unable to repro using VS 2017 15.9.26 with a .NET 4.7.2 class lib - maybe try upgrading your VS 2017 instance?

**Comment by ErikEJ** [comment]
And restart VS?

**Comment by karenpayneoregon** [comment]
Upgrading now

**Comment by karenpayneoregon** [comment]
Still upgrading, we have a major storm which may be affecting my download speed. In the mean time I tried the same operation on another machine and got 

System.Exception: Reverse engineer error: Unable to launch 'dotnet' version 3 or newer. Do you have it installed?
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput()
   at ReverseEngineer20.EfCoreReverseEngineer.LaunchExternalRunner(ReverseEngineerOptions options)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions, Boolean includeViews)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 237

**Comment by ErikEJ** [comment]
Well, as documented here, you must have .NET Core 3.1 x64 runtime installed: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering

**Comment by karenpayneoregon** [comment]
Okay Visual Studio has been upgraded as per the initial issue, this resolved things, now able to reverse engineer. Will install .NET Core on the other machine which is not part of this issue, thanks :-)
