### ISSUE TITLE
Reverse Engineer no longer working after update to EF_Core_Power_Tools_v2.4.212

### ISSUE THREAD

**Issue by johnhenley** [ErikEJ/EFCorePowerTools#509]
Click on reverse engineer and get error in output window:

System.NotImplementedException: Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
   at EnvDTE.Project.get_FullName()
   at EFCorePowerTools.Extensions.EnvDTEExtensions.<>c__DisplayClass0_0.<GetDacpacFilesInActiveSolution>b__2(Project p) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\EnvDTEExtensions.cs:line 29
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at EFCorePowerTools.Extensions.EnvDTEExtensions.GetDacpacFilesInActiveSolution(DTE dte, String[] projectPaths) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\EnvDTEExtensions.cs:line 27
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 48

EF_Core_Power_Tools_v2.4.212 
Visual Studio 2019 16.7.1

**Comment by johnhenley** [comment]
also get this error in a different solution

System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCorePowerTools.Extensions.EnvDTEExtensions.LinkedFilesSearch(ProjectItems projectItems, HashSet`1 files) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\EnvDTEExtensions.cs:line 79
   at EFCorePowerTools.Extensions.EnvDTEExtensions.GetDacpacFilesInActiveSolution(DTE dte, String[] projectPaths) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\EnvDTEExtensions.cs:line 32
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 48
