### ISSUE TITLE
ReverseEngineering - Timeout on TableListBuilder for large DBs

### ISSUE THREAD

**Issue by Fichti1982** [ErikEJ/EFCorePowerTools#510]
Currently i got a timeout exception (after 30 seconds) when trying to retrieve the tables list for reverse-engineering.
Running on SQLExpress on localhost - approx. 550 tables...

Is there a way to increase the timeout? I tested on another database with ~20 tables -> this works fine...

Here is the call-stack of the exception:

System.Exception: Table list error: 
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): Der Wartevorgang wurde abgebrochen.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerFasterDatabaseModelFactory.GetColumns(DbConnection connection, IReadOnlyList`1 tables, String tableFilter, String viewFilter, IReadOnlyDictionary`2 typeAliases) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\SqlServerFasterDatabaseModelFactory.cs:line 629
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerFasterDatabaseModelFactory.GetTables(DbConnection connection, Func`3 tableFilter, IReadOnlyDictionary`2 typeAliases) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\SqlServerFasterDatabaseModelFactory.cs:line 567
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerFasterDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\SqlServerFasterDatabaseModelFactory.cs:line 151
   at ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerFasterDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\SqlServerFasterDatabaseModelFactory.cs:line 107
   at ReverseEngineer20.TableListBuilder.GetTableDefinitions() in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\TableListBuilder.cs:line 40
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 33

### Steps to reproduce
-

### Further technical details
EF Core Power Tools version: 2.4.213

Database engine: SQLServerExpress

Visual Studio version: Visual Studio Community 2019 16.5.4

**Comment by ErikEJ** [comment]
There is no way to set the timeout currently.

Try updating statistics https://github.com/dotnet/efcore/issues/22287#issuecomment-682422195

**Comment by ErikEJ** [comment]
Or temporarly set the compat level below 120

**Comment by ErikEJ** [comment]
Ping?

**Comment by Fichti1982** [comment]
Thanks for your quick feedback. I tried setting down the compat level as well as updating the stats with no success.
Still timeouts after 30 sec...On monday i'll try the same on another environment, another instance of the database...

**Comment by Fichti1982** [comment]
After running "dbcc freeproccache" it works fine for me! Thanks!

**Comment by ErikEJ** [comment]
Interesting, so a bad plan was stuck in the cache ..
