### ISSUE TITLE
View DbContext Model DDM SQL - No database provider has been configured for this DbContext

### ISSUE THREAD

**Issue by phil000** [ErikEJ/EFCorePowerTools#521]
System.ArgumentException: Error:
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 41
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 22

### Steps to reproduce
Click View DbContext Model DDM SQL

### Further technical details
EF Core Power Tools version: 2.4.217.0
Microsoft.EntityFrameworkCore.Design 3.1.8

Database engine: SQL Server

Visual Studio version: VS2019 (16.7.5)

**Comment by ErikEJ** [comment]
Did you read the error message?

**Comment by phil000** [comment]
Yes.

The code is generated by the tool, and the mentioned constructor exists...

"If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions object in its constructor and passes it to the base constructor for DbContext."

*public MessagingContext(DbContextOptions<MessagingContext> options) : base(options)*

**Comment by ErikEJ** [comment]
You need to add UseSqlServer or similar for this provider specific feature to work.

**Comment by phil000** [comment]
In AddDbContext we do this in Startup ConfigureServices:

services.AddDbContext<MessagingContext>(builder =>
			{
				builder.UseSqlServer(connectionString, provider =>

**Comment by ErikEJ** [comment]
Please provide a repro project, and I will have a look

**Comment by ErikEJ** [comment]
Closing as no repro has been provided, please feel free to re-open if you can supply one.
