### ISSUE TITLE
Reverse Engineer of a .dacpac fails with a Cross-Database Reference

### ISSUE THREAD

**Issue by biiiipy** [ErikEJ/EFCorePowerTools#524]
I get an error when reverse engineering project with a Database Reference.
Dacpac project builds fine and can resolve all objects from referenced database, but reverse engineering fails.

### Steps to reproduce

In a dacpac project click `Add Database Reference` and reference a dacpac file. It creates a DB variable, for example, $(DB).

Create a view:
```sql
CREATE VIEW [dbo].[View1]
AS 
Select * From [$(DB)].dbo.TABLE1
```

Reverse Engineer error:
```
System.Exception: Table list error: 
Microsoft.SqlServer.Dac.DacServicesException: Cannot save package to file. The model has build blocking errors:
Error SQL71561: Error validating element [dbo].[View1]: SqlView: [dbo].[View1] has an unresolved reference to object [$(DB)].[dbo].[TABLE1].

   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.ValidateAndThrowOnErrors(Boolean treatWarningsAsErrors, IEnumerable`1 ignoreValidationErrors)
   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.BuildPackage(Func`1 streamGetter, PackageMetadata packageMetadata, PackageOptions packageOptions)
   at Microsoft.SqlServer.Dac.Model.TSqlModel.BuildPackage(String packageFilePath, PackageMetadata packageMetadata, PackageOptions packageOptions)
   at Microsoft.SqlServer.Dac.DacPackageExtensions.BuildPackage(String packageFilePath, TSqlModel model, PackageMetadata packageMetadata)
   at ReverseEngineer20.DacpacConsolidate.DacpacMerger.WriteFinalDacpac(TSqlModel model, String preScript, String postScript) in C:\Code\EFCorePowerTools\src\GUI\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\DacpacConsolidate\DacpacMerger.cs:line 86
   at ReverseEngineer20.DacpacConsolidate.DacpacMerger.Merge() in C:\Code\EFCorePowerTools\src\GUI\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\DacpacConsolidate\DacpacMerger.cs:line 78
   at ReverseEngineer20.DacpacConsolidate.DacpacConsolidator.Consolidate(String dacpacPath) in C:\Code\EFCorePowerTools\src\GUI\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\DacpacConsolidate\DacpacConsolidator.cs:line 26
   at ReverseEngineer20.DacpacTableListBuilder.GetTableDefinitions() in C:\Code\EFCorePowerTools\src\GUI\ErikEJ.EntityFrameworkCore.SqlServer.Dacpac\DacPacEngine\DacpacTableListBuilder.cs:line 32
   at efreveng.Program.BuildDacpacList(String dacpacPath) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 94
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 21

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 47
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 64
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetDacpacTables(String dacpacPath) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 30
   at EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitions(Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\TableListBuilder.cs:line 33
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetDacpacTables(String dacpacPath, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 348
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 98
```

### Further technical details
EF Core Power Tools version: 2.4.217

Database engine: SQL Server 2016

Visual Studio version: 16.7.4

**Comment by ErikEJ** [comment]
Have you tried setting ignore errors on your database project?

**Comment by biiiipy** [comment]
Still get the same error... here's a snippet from my project file:
```xml
    <ArtifactReference Include="DBReferences\DB.dacpac">
      <HintPath>DBReferences\DB.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>True</SuppressMissingDependenciesErrors>
      <DatabaseSqlCmdVariable>DB</DatabaseSqlCmdVariable>
    </ArtifactReference>
  </ItemGroup>
  <ItemGroup>
    <SqlCmdVariable Include="DB">
      <DefaultValue>DB</DefaultValue>
      <Value>$(SqlCmdVar__1)</Value>
    </SqlCmdVariable>
  </ItemGroup>
```

Or did you mean a different setting?

**Comment by ErikEJ** [comment]
That's what I meant. In order to debug I need a repro solution.

**Comment by biiiipy** [comment]
Repro solution:
[efcorerepro.zip](https://github.com/ErikEJ/EFCorePowerTools/files/5318269/efcorerepro.zip)

On DBModel project run reverse engineer for DB2

**Comment by ErikEJ** [comment]
This is currently not supported, and appears to be an old issue: https://stackoverflow.com/questions/12161392/using-ssdt-how-do-i-resolve-sql71561-errors-when-i-have-a-view-that-references

**Comment by biiiipy** [comment]
Thanks for the help!
It's weird that my dacpac builds successfully without any errors or warnings (it also grabs the references dacpac into output folder), it's only when I do reverse engineer, that I get the error. Could it be that EF Core Power tools goes through different build steps so it fails?

**Comment by ErikEJ** [comment]
>> Could it be that EF Core Power tools goes through different build steps so it fails?

Absolutely, in order to load and inspect the resulting model of your database, all referenced .dacpacs are consolidated to a single one, and that is the step that fails.

I will try to test without consolidation based on your original .dacpacs.

**Comment by ErikEJ** [comment]
I tried that, but unable to resolve the view columns

**Comment by biiiipy** [comment]
Maybe there's a room at least for a workaround? For example, by providing column information by other means, maybe by using ``union`` to merge definition from a mock table with data from the actual source:
```sql
create view View1 as
select Id, Name from SpecialTableWithColumnInfo
union select Id,Name from DB2.dbo.Table1
```

**Comment by ErikEJ** [comment]
Possibly. Let's see if any others report this - you are the first one..

**Comment by ErikEJ** [comment]
Looks like this is not feasible for multiple reasons, workaround is to scaffold from a publish (even local) database.
