### ISSUE TITLE
Handlebars.dll cannot be found

### ISSUE THREAD

**Issue by yomer** [ErikEJ/EFCorePowerTools#53]
Hi Erick,
 I'm getting a missing Handlebars error and I hope that you can help me fix this.

When I try to Reverse Code Engineer, I get an error one the console the Handlebars.dll cannot be found.

System.IO.FileNotFoundException: Could not load file or assembly 'Handlebars, Version=1.9.4.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The system cannot find the file specified.
File name: 'Handlebars, Version=1.9.4.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661'
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsHelperService.RegisterHelpers()
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpModelGenerator.GenerateModel(IModel model, String namespace, String contextDir, String contextName, String connectionString, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 153

**Steps to reproduce**
Installed the latest daily build
I have a .NET Core 2.1 Class Library project
All needed EntityFrameworkCore dependencies installed
Handlebars.NET nuget package installed.
I'm able to generate Reverse Code without the HandleBars option, but when selecting to use Hndlebars I get the error.

**Further technical details**
EF Core Power Tools version: 1.0.616.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2017 15.7.3

**Comment by ErikEJ** [comment]
Fixed in build .617

**Comment by yomer** [comment]
Thank you, that was fast. I hadn't checked today's build. Great work!
