### ISSUE TITLE
Config file efpt.config.json not created, ArgumentNullException

### ISSUE THREAD

**Issue by NutmegAdam** [ErikEJ/EFCorePowerTools#540]
I have been trying to reverse engineer a database into a class library. I created a separate library project (.NET Standard 2.1, and also tried .NET Core 3.1) for this, and used the Reverse Engineer tool against the database.

The main problem I encountered was that the stored procs don't get generated, and then I noticed that the config file wasn't getting saved either. Looking in the Output window, I see this error:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.SaveOptions(Project project, String optionsPath, ReverseEngineerOptions options) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 351
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 311
```

I'm not sure if the issues are related or not. I don't have issues running against other databases, so I'm guessing something unusual about this one is causing the problem. Perhaps there's a debug log I can get to and provide more helpful info?

I have tried selecting all tables, only relevant tables (in case one was wonky), and selecting only a single table. I have tried it in a .NET Standard 2.1 library and a .NET Core 3.1 library, and have tried both with and without the "Use EF Core 5 (preview)" option.

### Steps to reproduce

1. Right-click the project (.NET Core 3.1, Class Library) -> EF Core Power Tools -> Reverse Engineer
2. Issue happens with "Use EF Core 5 (preview)" or without
3. Issue happens selecting all tables (including some temps), or just one standard table

### Further technical details

EF Core Power Tools version: 2.4.244 (daily build)

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.7.6

**Comment by ErikEJ** [comment]
To generate stored procedures, enable via advanced options.

It looks like the tool is unable to get the path to your project for some reason.

What is the path?

**Comment by NutmegAdam** [comment]
I did check that off in Advanced options - I apologize for neglecting to mention that in the initial post.

There's nothing weird about the path, as far as I can see:

``C:\Users\adamy\source\repos\DataPump\IchDb``

Given this works fine for other databases, I'm not sure why this one is  problematic. Perhaps an error further down is causing this not to get populated, possibly whatever the issue is that prevents the stored procs from getting generated? I'll clone and see if I can test that theory.

**Comment by NutmegAdam** [comment]
I tried creating a completely new, stand-alone solution, in case the problem came from here in ReverseEngineerHandler due to something weird in the solution file:

```
 if (optionsPaths.Count > 1)
                {
                    var pcd = _package.GetView<IPickConfigDialog>();
                    pcd.PublishConfigurations(optionsPaths.Select(m => new ConfigModel
                    {
                        ConfigPath = m,
                    }));

                    var pickConfigResult = pcd.ShowAndAwaitUserResponse(true);
                    if (!pickConfigResult.ClosedByOK)
                        return;

                    optionsPath = pickConfigResult.Payload.ConfigPath;
                }
```

However, even a clean solution has the same result. But, I can reverse engineer other databases, and I don't see how an error deeper down with scaffolding could bubble up and make the options path null. That said, I have no experience with extension development, and am not really sure how to set up an integration test to try reading the project options manually to verify the path exists as expected.

I also noted that reverse engineering does not add the EF Core provider package when selected, either - possibly also due to something being weird with not reading the project correctly?

I also verified that I can reverse engineer a different database into this same project, and it does create the procedures. However, this particular database is known to be wonky, and fails to complete scaffolding for a different reason:

```
System.Exception: Reverse engineer error: 
System.InvalidOperationException: The foreign key {'AssignByRecId'} cannot be added to the entity type 'Meeting' because a foreign key on the same properties already exists on entity type 'Meeting' and also targets the key {'MemberRecId'} on 'Member'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.Validate(IReadOnlyList`1 properties, Key principalKey, EntityType declaringEntityType, EntityType principalEntityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey..ctor(IReadOnlyList`1 dependentProperties, Key principalKey, EntityType dependentEntityType, EntityType principalEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddForeignKey(IReadOnlyList`1 properties, Key principalKey, EntityType principalEntityType, Nullable`1 componentConfigurationSource, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.AddForeignKey(IReadOnlyList`1 properties, IMutableKey principalKey, IMutableEntityType principalEntityType)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKey(ModelBuilder modelBuilder, DatabaseForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 103
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 62

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 27
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 121
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 52
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 259
```

Scaffolding that db doesn't create the config file either, but I believe that's because the above error aborts the process.

I then tried reverse engineering a small localdb running on the local dev machine, and got no errors with scaffolding, yet again the same config file error:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.SaveOptions(Project project, String optionsPath, ReverseEngineerOptions options) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 351
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 311
```

So, now I'm starting to think that it may not be a db oddity causing the config file issue. I know the config file had gotten written a month or two back, but the stored procs didn't generate so I kept re-trying periodically in case any changes/fixes in nightly builds addressed the issue.

Might something about the way paths are retrieved have changed in recent versions of VS 16.7x?

If there's anything you'd like me to check or try, let me know - happy to help out any way I can! Will keep playing around on this end to see if I can figure anything out.

**Comment by ErikEJ** [comment]
I need a repro in order to help.

To fix the wonky db, drop the duplicate foreign key.

**Comment by ErikEJ** [comment]
You can share privately via email

**Comment by ErikEJ** [comment]
Debugging the extension is also quite easy

**Comment by NutmegAdam** [comment]
The wonky db isn't important to me, it was just a convenient one to try connecting to, to verify that it wasn't the project file itself that was weird. So it appears that not creating the config file is consistent on my machine, and is likely *not* related to whatever makes me unable to reverse-engineer the stored procs from the actual db of interest, which is not one I can directly provide access to.

Is there a debug log or something I can enable to get a capture for you? I'm not sure the best way to get you the information needed to figure this out.

**Comment by ErikEJ** [comment]
Either debug the extension or share a repro solution as a zip file. 

Not convinced I can repro locally.

**Comment by ErikEJ** [comment]
I was able to repro, bug fix in the works.

**Comment by ErikEJ** [comment]
Fixed in latest daily build, thanks for reporting (and trying out the daily build)

**Comment by NutmegAdam** [comment]
Awesome, that was fast - thanks! I'll look into how to debug an extension, and see if I can be more helpful figuring out why that one database can't be reverse engineered with stored procs.

Thanks for all your efforts!

**Comment by ErikEJ** [comment]
@NutmegAdam I you still have issues with the stored procedures, send me the database schema, and I will figure out why.
