### ISSUE TITLE
Reverse engineer error: Requested value 'sql_variant' was not found

### ISSUE THREAD

**Issue by NutmegAdam** [ErikEJ/EFCorePowerTools#590]
While trying to reverse engineer a database, this error comes up:

```
System.Exception: Reverse engineer error: 
System.ArgumentException: Requested value 'sql_variant' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at RevEng.Core.SqlServerSqlTypeExtensions.GetSqlDbType(String storeType) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerSqlTypeExtensions.cs:line 50
   at RevEng.Core.SqlServerSqlTypeExtensions.GetClrType(String storeType, Boolean isNullable) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerSqlTypeExtensions.cs:line 56
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.GenerateProperties(Procedure storedProcedure) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 375
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.GenerateClass(Procedure storedProcedure, String name) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 358
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.WriteResultClass(Procedure storedProcedure, String namespace, String name) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 343
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.ScaffoldModel(String connectionString, ProcedureScaffolderOptions procedureScaffolderOptions, ProcedureModelFactoryOptions procedureModelFactoryOptions, List`1& errors) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 65
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 81
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 68

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 27
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 112
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 51
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 272
```

I am not sure which of many stored procedures it's trying to get properties for, and there is a warning at the beginning that "The SQL Server user does not have 'VIEW DEFINITION' rights", and I don't know if that's relevant to this.

The process stops here and doesn't continue on to the next item, and there's no indication which procedure hit the snag.

Looking at the code at ```SqlServerSqlTypeExtensions.GetSqlDbType(String storeType) in SqlServerSqlTypeExtensions.cs:line 50``` as indicated, it seems it's trying to lookup the value 'sql_variant' as an enum of type SqlDbType, where the value "variant" is defined, but not "sql_variant". Might this just mean that SqlTypeAliases needs an additional entry to map sql_variant -> variant?

### Steps to reproduce
* Reverse-engineered a rather large SQL database w/ stored procedures

### Further technical details
EF Core Power Tools version: 2.5.302.0

Database engine: Microsoft SQL Server 2016 (SP2-CU9) (KB4515435) - 13.0.5479.0 (X64) 

Visual Studio version: Visual Studio 2019 16.8.1

**Comment by ErikEJ** [comment]
Thanks for the debugging, I will update the map soon.

**Comment by NutmegAdam** [comment]
No problem, thanks!

**Comment by ErikEJ** [comment]
I attempted a fix in the latest daily build, thanks for reporting and trying out this preview feature 😄

**Comment by NutmegAdam** [comment]
I can confirm this resolved that issue. However, it now progresses to a similar but perhaps more subtly complicated issue on data type "geography" - Would you prefer I create a separate issue for that, or leave it here as a related issue? I will try to make time this week to look into being able to log these errors to the output window but continue on, skipping unresolvable classes.

**Comment by ErikEJ** [comment]
Please create a new issue with the full error message, thanks
