### ISSUE TITLE
Reverse engineer error: Requested value 'geography' was not found

### ISSUE THREAD

**Issue by NutmegAdam** [ErikEJ/EFCorePowerTools#592]
Similar to #590 I believe. While trying to reverse engineer a database, this error comes up:

```
System.Exception: Reverse engineer error: 
System.ArgumentException: Requested value 'geography' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at RevEng.Core.SqlServerSqlTypeExtensions.GetSqlDbType(String storeType) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerSqlTypeExtensions.cs:line 51
   at RevEng.Core.SqlServerSqlTypeExtensions.GetClrType(String storeType, Boolean isNullable) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerSqlTypeExtensions.cs:line 57
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.GenerateProperties(Procedure storedProcedure) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 375
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.GenerateClass(Procedure storedProcedure, String name) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 358
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.WriteResultClass(Procedure storedProcedure, String namespace, String name) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 343
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.ScaffoldModel(String connectionString, ProcedureScaffolderOptions procedureScaffolderOptions, ProcedureModelFactoryOptions procedureModelFactoryOptions, List`1& errors) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 65
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 81
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 68

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 27
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 112
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 51
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 272
```

### Steps to reproduce
* Reverse-engineered a rather large SQL database w/ stored procedures

### Further technical details
EF Core Power Tools version: 2.5.304.0

Database engine: Microsoft SQL Server 2016 (SP2-CU9) (KB4515435) - 13.0.5479.0 (X64)

Visual Studio version: Visual Studio 2019 16.8.1

**Comment by ErikEJ** [comment]
@NutmegAdam  Did this unblock you?

**Comment by NutmegAdam** [comment]
Yes, it did - my apologies, I thought I commended but apparently not. That got me to another error, but one that I believe is genuinely a database issue, and not a Power Tools issue.

Thanks!

**Comment by ErikEJ** [comment]
Feel free to share the "other" error - sounds like an excellent integration test you were running!
