### ISSUE TITLE
Reverse engineering fails

### ISSUE THREAD

**Issue by karenpayneoregon** [ErikEJ/EFCorePowerTools#625]
Describe what is not working as expected.

### Steps to reproduce
First off I've had this issue before, to resolve I would restart VS2017 and reverse engineering worked but not this time.
Attempt to reverse engineer in VS2017, get to the following screen and press OK
![1111](https://user-images.githubusercontent.com/17032797/100612075-3391b580-32c7-11eb-9ee3-48f53b59d299.png)

In the IDE Output window
``
System.MissingMethodException: Method not found: 'System.IO.Compression.ZipArchive System.IO.Compression.ZipFile.Open(System.String, System.IO.Compression.ZipArchiveMode)'.
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.DropNetCoreFiles()
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 84
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType, SchemaInfo[] schemas) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 72
   at EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitions(Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\TableListBuilder.cs:line 39
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTables(String connectionString, DatabaseType databaseType, Boolean useEFCore5, SchemaInfo[] schemas) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 389
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 129
``
Now if I use VS2019 with version 2.4.217.0, zero issues.

### Further technical details
Version 2.5.277.0

SQLite ADO.NET Provider included: 1.0.99.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL Server

Visual Studio version: (e.g. Visual Studio 2017 15.7)
Microsoft Visual Studio Enterprise 2017 
Version 15.9.26
VisualStudio.15.Release/15.9.26+28307.1234
Microsoft .NET Framework
Version 4.8.04084

**Comment by ErikEJ** [comment]
Have you tried VS 2019?

**Comment by karenpayneoregon** [comment]
Well I decided to install you SQLite Simple DDEX provider, restart VS2017 and now reverse engineering is working. And note that VS2019 never had an issue but is one version back. So now all is fine.
