### ISSUE TITLE
Reverse Enginering Exception: Table list error: Unable to launch external process

### ISSUE THREAD

**Issue by atinks** [ErikEJ/EFCorePowerTools#638]
An Exception is thrown when I click on the Ok button of the Choose Database Connection form.

### Steps to reproduce
1. Right click and invoke reverse engineer menu option
2. Add a link to SQL Server database - ensure correct permissions to view tables etc.
3. Tick the Use EF Core 5 box
4. Click Ok - nothing happens.  The Output window displays exception information

Projects build report:
  Status    | Project [Config|platform]
 -----------|---------------------------------------------------------------------------------------------------

Build time 14:25:15.521
Build ended at 07/12/2020 14:25:15

`System.Exception: Table list error: Unable to launch external process: 
   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 50
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 94
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType, SchemaInfo[] schemas) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 72
   at EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitions(Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\TableListBuilder.cs:line 39
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTables(String connectionString, DatabaseType databaseType, Boolean useEFCore5, SchemaInfo[] schemas) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 389
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 129`

### Further technical details
EF Core Power Tools version: 2.5.277.0
Database engine: SQL Server 2019
Visual Studio version: VS 2019 
Project Type: .Net 5 Console App

**Comment by ErikEJ** [comment]
Do you have the .net Core 3.1 runtime installed?

Maybe security software prevents execution?

**Comment by atinks** [comment]
Thanks for the fast reply - I am pretty sure I have .net Core 3.1 runtime installed - will check.

**Comment by atinks** [comment]
All earlier versions of the .Net Core SDK were removed when 5.0 was installed via 16.8 update.  All working now.
