### ISSUE TITLE
Reverse engineer fails to generate stored procedure

### ISSUE THREAD

**Issue by adopilot** [ErikEJ/EFCorePowerTools#703]
When I try to scaffold stored procedure  dbcontex using reverse engineer in output window I get error,
My project is .Net 5 I checked Use .Net core 5. on dialog, Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.Tools is on ver 5.0.1 
(When I try to scaffold only tables I do not get errors, db context and models are generated orderly)
this is how Generate dialog looks like
![image](https://user-images.githubusercontent.com/4448913/103882795-9ce1c100-50dc-11eb-859d-8b01f9e7faa8.png)

My sproc looks like

```
ALTER PROCEDURE [dbo].[kuif_kufovi] 
	     @OdDatuma date
        ,@DoDatuma date
        ,@Parnter varchar(20)
        ,@Temeljnica int
        ,@VkId int
        ,@TipKuifa int
        ,@RjId int
        ,@RobniDocTip varchar(10)
        ,@BezParntera int
AS
BEGIN
	set transaction isolation level read uncommitted;
	SET NOCOUNT ON;

    select
 
	
	 TipDokumenta =max( isnull(KuifTipDokumenta.Sifra,'01'))
	,BrojFakture = max(isnull(FIN_STAVKE.BROJ,SKLADISTE.SIFRA))
	,DatumFakture = max(isnull(FIN_STAVKE.DATUM_RAC,FIN_KR.DATUM))
	,DatumPrijema = max(isnull(FIN_KR.DATUM,FIN_STAVKE.DATUM_PP))
	,NazivDobavljaca	= max(isnulL(par.NAZIV,'UVOZ') )
	,SjedisteDobavljača = max(case 
			when isnulL(MJESTO.KANTON_BR,0)>0 or isnulL(MJESTO.KANTON_FED,0)>0 or isnulL(MJESTO.KANTON_RS,0)>0 then MJESTO.NAZIV
			else isnull(DRZAVE.NAZIV,'')+' '+MJESTO.NAZIV
				end )
	,PDVBroj = max(case when ISNULL(ParTipTvrtke.PdvObveznik,0)=1 THEN PAR.MATBR else '000000000000' end)  --SELECT * FROM ParTipTvrtke
	,JIBDobavljača = max(isnulL(par.MATBR,'0000000000000'))
	,IznosFaktureBezPDV =sum( isnull(fin_kr.OSNOVICA0,0)+isnull(FIN_KR.OSNOVICA22,0)+isnull(FIN_KR.NEOPOREZIVO,0))
	,IznosFakturePDV =max( FIN_STAVKE.DUGUJE+FIN_STAVKE.POTRAZUJE)
	,IznosPauSalnenaknade = 0
	,IznosulaznogPDV =  sum(isnull(FIN_KR.POREZ22,0))
	,UlazniPDVOdbitni = sum(case when KNJIGA_FAKTURA.SIFRA <>'00018' then isnulL(FIN_KR.POREZ22,0) else 0 end)
	,UlazniPDVNeOdbitni = sum(case when KNJIGA_FAKTURA.SIFRA='00018' then isnulL(FIN_KR.POREZ22,0) else 0 end)
	,Polje32 =sum(case when KNJIGA_FAKTURA.SIFRA='00018' then isnulL(FIN_KR.POREZ22,0) else 0 end)
	,Polje33 =0
	,Polje34=0
	,Id=FIN_STAVKE.ID
from FIN_KR
inner join KNJIGA_FAKTURA on FIN_kr.KNJIGA_ID=KNJIGA_FAKTURA.ID
inner join FIN_STAVKE on FIN_KR.STAVKA_ID=FIN_STAVKE.ID
left outer join FIN_DOC on FIN_STAVKE.DOC_ID=FIN_DOC.ID
left outer join FIN_DEF_PD on FIN_STAVKE.PD_ID = FIN_DEF_PD.PD_ID and FIN_STAVKE.EL_ID = FIN_DEF_PD.EL_ID and FIN_STAVKE.TIP = FIN_DEF_PD.DOC_TIP
left outer join FIN_VR_K on FIN_VR_K.ID = isnull(fin_doc.VR_K_ID, FIN_DEF_PD.VK_ID)
left outer join KuifTipoviDokumenataZaVrsteKnjizenja on FIN_VR_K.id=KuifTipoviDokumenataZaVrsteKnjizenja.VkId and KuifTipoviDokumenataZaVrsteKnjizenja.tipui='U'
left outer join KuifTipDokumenta on KuifTipoviDokumenataZaVrsteKnjizenja.TipId=KuifTipDokumenta.Id
left outer join PROTOCOL on FIN_STAVKE.PROTOCOL_ID=PROTOCOL.ID
left outer join SKLADISTE on FIN_STAVKE.RJ_ID=SKLADISTE.ID
left outer join par on FIN_STAVKE.PAR_ID=par.ID
left outer join MJESTO on par.MJE_ID=MJESTO.ID
left outer join DRZAVE on par.DRZ_ID=DRZAVE.ID
left outer join ParTipTvrtke on par.TIP_TVRTKE=ParTipTvrtke.Id
where 
		FIN_KR.DATUM between @OdDatuma and @DoDatuma
	and KNJIGA_FAKTURA.tip='U'
	and (@Parnter='SEX' or ((isnull(par.naziv,'FAK') like '%'+par.naziv+'%' or isnull(par.sifra,'SEX')=@Parnter)))
	and (@Temeljnica=0 or isnulL(FIN_STAVKE.DOC_ID,-1)=@Temeljnica)
	and (@VkId=0 or isnull(FIN_DOC.VR_K_ID,-1)=@VkId)
	and (@RjId=0 or FIN_STAVKE.RJ_ID=@RjId)
	and (@RobniDocTip='SEX' or isnull(PROTOCOL.DOC_TIP,'FAK')=@RobniDocTip)
	and (@BezParntera=0 or (@BezParntera=1 and FIN_STAVKE.PAR_ID is null) or (@BezParntera=2 and FIN_STAVKE.PAR_ID is not null))
group by FIN_STAVKE.id
```

```
System.Exception: Reverse engineer error: 
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'is_nullable'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetStoredProcedureParameters(SqlConnection connection, String schema, String name) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 131
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetStoredProcedures(String connectionString, ProcedureModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 70
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.Create(String connectionString, ProcedureModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 26
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.ScaffoldModel(String connectionString, ProcedureScaffolderOptions procedureScaffolderOptions, ProcedureModelFactoryOptions procedureModelFactoryOptions, List`1& errors) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 60
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 82
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 57
ClientConnectionId:8328076b-1449-457b-839c-146c7fe861cd
Error Number:207,State:1,Class:16

```

### Further technical details
EF Core Power Tools version:  2.5.406.0
Database engine: Microsoft SQL Server 2012 (SP3-GDR) (KB4019092) - 11.0.6251.0 (X64)   Jul  7 2017 07:14:24   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

Visual Studio version:  Visual studio 2019 Version 16.9.0. Preview 2.0

**Comment by ErikEJ** [comment]
What is the database compatibility level?

`select compatibility_level from sys.databases where name ='myDB'`

**Comment by adopilot** [comment]
My compatibility_level   = 110

**Comment by adopilot** [comment]
Does this helps in debuging
![image](https://user-images.githubusercontent.com/4448913/103886033-2d220500-50e1-11eb-96ae-1e8d806f4d73.png)

**Comment by ErikEJ** [comment]
No, it is the query to get parameters, not the result shape.

**Comment by ErikEJ** [comment]
It looks like you are the first person scaffolding stored procedure s from a SQL 2012 database. I will fix the bug.

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build, please let me know if that works for you.

**Comment by adopilot** [comment]
Thanks a lot for fast response,
Now it is working.

**Comment by ErikEJ** [comment]
Great, thanks for confirming!
