### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iremkara** [ErikEJ/EFCorePowerTools#72]
System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.EntityFrameworkCore.Design.ReverseEngineerOptions, System.ValueTuple`2<System.String,System.Action`3<System.IO.TextWriter,System.Object,System.Object[]>>[])'.
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 154

Database engine: (SQL Server)

Visual Studio version: (e.g. Visual Studio 2017 15.7.5)

EF Core Powe Tools version 1.0.604.0

**Comment by ErikEJ** [comment]
Could you please try the latest daily build, that should fix the issue.

**Comment by MortezaSefidiSomarin** [comment]
how to do this?
Could you please try the latest daily build, that should fix the issue.
