### ISSUE TITLE
Reverse Engineer -> Unable to find the requested .Net Framework Data Provider 

### ISSUE THREAD

**Issue by PeaStew** [ErikEJ/EFCorePowerTools#722]
When attempting to reverse engineer, box pops up saying that Oracle driver settings need to be updated for Visual Studio if you do either:

1. Do the update, closing down all VS instances and runnign the update
2. Click no

The following error is thrown:

System.ArgumentException: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
   at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at Microsoft.VisualStudio.Data.HostServices.Data.GetProviderFactory(String providerInvariantName)
   at Microsoft.VisualStudio.Data.Framework.AdoDotNet.AdoDotNetProvider.CreateObject[T](String invariantName)
   at Microsoft.VisualStudio.Data.Framework.AdoDotNet.AdoDotNetConnectionSupport.Initialize(Object providerObj)
   at Oracle.VsDevTools.DDEX2.OracleProviderConnectionSupport.Initialize(Object providerObj)
   at Microsoft.VisualStudio.Data.Package.DataConnectionFactory.CreateConnection(Guid provider, String connectionString, Boolean encryptedString)
   at Microsoft.VisualStudio.Data.Package.DataConnectionManager.GetConnection(Guid provider, String connectionString, Boolean encryptedString, Boolean update)
   at Microsoft.VisualStudio.Data.Package.DataConnectionManager.GetConnection(Guid provider, String connectionString, Boolean encryptedString)
   at Microsoft.VisualStudio.Data.Package.DataExplorerConnection.InitializeConnection()
   at Microsoft.VisualStudio.Data.Package.DataExplorerConnection.get_Connection()
   at EFCorePowerTools.Helpers.VsDataHelper.GetDataConnections(EFCorePowerToolsPackage package) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Helpers\VsDataHelper.cs:line 35
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 68

I'm not even trying to reverese engineer an oracle DB, so it seems it would be better if this was caught later when in service of needing to reverse engineer an oracle DB, rather than on startup.

### Further technical details
Version 2.5.454.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: N/A

Visual Studio version: 
Microsoft Visual Studio Professional 2019
Version 16.8.4

But this error has been around forever.

**Comment by PeaStew** [comment]
Just for reference, Oracle drivers are working just fine in SSIS in the same VS instance, so my guess is that the detection mechanism is broken.

**Comment by ErikEJ** [comment]
I think it may not be the same drivers, I will handle this error gracefully (ignore)

**Comment by PeaStew** [comment]
https://github.com/ErikEJ/EFCorePowerTools/blob/5ac5727d7e260175966c89583a22605863cd8955/src/GUI/EFCorePowerTools/Helpers/VsDataHelper.cs#L74 I am guessing it would be helpful to actually catch the error and do something with it other than crash.

**Comment by ErikEJ** [comment]
Yes, that was my plan.

PR?

**Comment by PeaStew** [comment]
Deleting all the data connection with oracle data sources resolved it also. But yes, sure I can submit a PR, I would tend to do something with the exception though so the user could review which connection is in error ;)

**Comment by ErikEJ** [comment]
Log to the vs output window, yes.

**Comment by ErikEJ** [comment]
Fixed in latest daily build, thanks for reporting

**Comment by PeaStew** [comment]
Sorry, yes I am in the middle of a project and just had time now to submit a PR but I see you have fixed it, thanks!

**Comment by ErikEJ** [comment]
You are welcome, would be great if you could repro and verify the fix?
