### ISSUE TITLE
Add DbContext Diagram fails

### ISSUE THREAD

**Issue by SBortz** [ErikEJ/EFCorePowerTools#782]
Add DbContext Diagram fails.

### Steps to reproduce
Right-click data access project with EF Core 5 context in it -> EF Power Tools -> Add DbContext Diagram.

Outputs:
System.ArgumentException: Falscher Parameter. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.SolutionClass.Item(Object index)
   at EFCorePowerTools.Extensions.EnvDTEExtensions.GetStartupProjectOutputPath(DTE dte) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\EnvDTEExtensions.cs:line 69
   at EFCorePowerTools.Handlers.ProcessLauncher.<GetOutputInternalAsync>d__6.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ProcessLauncher.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.<GenerateAsync>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 68

### Further technical details
EF Core Power Tools version:  2.5.513
Database engine: SQL Server
Visual Studio version:   Visual Studio 2019 16.8.5

**Comment by ErikEJ** [comment]
I will investigate, could you try to switch startup project?

**Comment by SBortz** [comment]
I switched to the data access project as startup project. It had no effect, leads to the same output.

**Comment by ErikEJ** [comment]
Are you able to share a repro? Privately?

**Comment by SBortz** [comment]
Not this one unfortunately :(

**Comment by ErikEJ** [comment]
I attempted a fix in the latest daily build, could you please give that a try?

**Comment by SBortz** [comment]
I installed 2.5.514. Still the same.
I am putting together a repro now that i would share privately.

**Comment by SBortz** [comment]
Where should i send the repro to?

**Comment by SBortz** [comment]
With 2.5.515 i get another output:

System.ArgumentException: Error:
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Version=5.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.EntityFrameworkCore.Design, Version=5.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl)
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 54

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.<GenerateAsync>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 77

**Comment by SBortz** [comment]
I referenced Microsoft.EntityFrameworkCore.Design 5.0.0

**Comment by SBortz** [comment]
After upgrading to EntityFramework 5.0.1, i get another output:

System.ArgumentException: Error:
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'somecontext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at DataAccess.Context.somecontext..ctor() in C:\Projekte\efcorepowertools-issue-782\Sources\Libraries\DataAccess\Context\somecontext.cs:line 16
--- End of stack trace from previous location ---
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 39
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 54

**Comment by ErikEJ** [comment]
Look at the link in the error message.

**Comment by SBortz** [comment]
We´re using .AddDbContext, but for some reason that does not work.
Overriding the DbContext.OnConfiguring does work now. Thanks for your help!

**Comment by ErikEJ** [comment]
You need to set the correct startup project.
