### ISSUE TITLE
Add DbContext Diagram fails

### ISSUE THREAD

**Issue by GaryGWW** [ErikEJ/EFCorePowerTools#783]
Add DbContext Diagram fails.

**Steps to reproduce**
Right-click data access project with EF Core 5 context in it -> EF Power Tools -> Add DbContext Diagram.

**Output**
System.ArgumentException: Error:
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Internal.DebugView`1<Microsoft.EntityFrameworkCore.Metadata.Internal.Model> Microsoft.EntityFrameworkCore.Metadata.Internal.Model.get_DebugView()'.
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl)
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 54

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.<GenerateAsync>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 77

**Further technical details**
EF Core Power Tools version: 2.5.513
Database engine: SQL Server
Visual Studio version: Visual Studio 2019 16.8.5

Thank you for your help.

**Comment by ErikEJ** [comment]
Can you share a repro project?

**Comment by GaryGWW** [comment]
I'll get one together.

**Comment by sharpninja** [comment]
I can verify:

```
Build started...
1>------ Build started: Project: WelcomeSite, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

> Build started at 7:02 AM and took 7.298 seconds
System.ArgumentException: Error:
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Internal.DebugView`1<Microsoft.EntityFrameworkCore.Metadata.Internal.Model> Microsoft.EntityFrameworkCore.Metadata.Internal.Model.get_DebugView()'.
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl)
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 54

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.<GenerateAsync>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 77

```

**Comment by sharpninja** [comment]
It affects all actions of the power tool.

**Comment by ErikEJ** [comment]
@sharpninja Even reverse engineering?
Can you share your project?

**Comment by ErikEJ** [comment]
Are you using EF Core 5.0.0 ??

**Comment by GaryGWW** [comment]
I am using, Core 5.0.0.

I was unable to share the project I was working on, will try to get another over to you a.s.a.p.

**Comment by ErikEJ** [comment]
Try updating to 5.0.1 or 5.0.2!

**Comment by GaryGWW** [comment]
Erroring in 5.0.103.

Reverse Engineer Works, haven't run through entirely as of yet.
Migrations tool (preview) Errors 
Add DBContext Diagram Errors as above
View DBContext DDL SQL Errors as below (E1)
View DBContext As DebugView Errors as above
Add Asdgml() extension Works
Compare DBContext to Database as below (E2)

**E1**
========== Build: 0 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========

System.ArgumentException: Error:
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Internal.DebugView`1<Microsoft.EntityFrameworkCore.Metadata.Internal.Model> Microsoft.EntityFrameworkCore.Metadata.Internal.Model.get_DebugView()'.
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl)
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 24

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.<GenerateAsync>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 77

**E2**

========== Build: 0 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========

System.ArgumentException: Error:
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Internal.DebugView`1<Microsoft.EntityFrameworkCore.Metadata.Internal.Model> Microsoft.EntityFrameworkCore.Metadata.Internal.Model.get_DebugView()'.
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl)
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 54

Parameter name: processResult
   at EFCorePowerTools.Handlers.Compare.CompareHandler.<GetDbContextTypesAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\Compare\CompareHandler.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EFCorePowerTools.Handlers.Compare.CompareHandler.<HandleComparisonAsync>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\Compare\CompareHandler.cs:line 81

**Comment by ErikEJ** [comment]
5.0.103 is not an EF Core version!

Please share a repro, or at least your .csproj file.

**Comment by GaryGWW** [comment]
Apologies, I was working on preview version 6

**Comment by ErikEJ** [comment]
@GaryGWW so you no longer have an issue?

**Comment by GaryGWW** [comment]
No, changed to 5.0.2 and all OK. Thanks for the help.

**Comment by ErikEJ** [comment]
@sharpninja And you?

**Comment by sharpninja** [comment]
I got it working by rolling back the EFCore Sql Server package to the latest stable.

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ErikEJ** [comment]
@sharpninja Which version was the "unstable" one?

**Comment by sharpninja** [comment]
Latest prerelease from Nuget.

**Comment by ErikEJ** [comment]
The tool should actually prevent you from running with pre-release versions, I will investigate why you did not see a warning.

**Comment by ErikEJ** [comment]
I have fixed the bug of not showing the warning!
