### ISSUE TITLE
Reverse Engineering Throws Null Exception

### ISSUE THREAD

**Issue by dmatter98** [ErikEJ/EFCorePowerTools#797]
EF Core Power Tools version: 2.5.513
SQL Server: Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64) 
Visual Studio: Microsoft Visual Studio Community 2019 / Version 16.8.4

Steps:
-- Upgraded to (2.5.513)
1. Right Click Project; select, "EF CORE POWER TOOLS >"
2. Click, "Reverse Engineer"
3. Choose Database Connection Dialog, press, "OK"

Output Error:
--------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCorePowerTools.ViewModels.ObjectTreeViewModel.<>c__DisplayClass20_3.<AddObjects>b__4(ColumnNamer c) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\ViewModels\ObjectTreeViewModel.cs:line 216
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at EFCorePowerTools.ViewModels.ObjectTreeViewModel.AddObjects(IEnumerable`1 objects, IEnumerable`1 customReplacers) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\ViewModels\ObjectTreeViewModel.cs:line 216
   at EFCorePowerTools.ViewModels.PickTablesViewModel.AddObjects(IEnumerable`1 objects, IEnumerable`1 customReplacers) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\ViewModels\PickTablesViewModel.cs:line 118
   at EFCorePowerTools.Dialogs.PickTablesDialog.EFCorePowerTools.Contracts.Views.IPickTablesDialog.AddTables(IEnumerable`1 tables, IEnumerable`1 customReplacers) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Dialogs\PickTablesDialog.xaml.cs:line 56
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<LoadDataBaseObjectsAsync>d__9.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 298
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__5.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 123

**Comment by ErikEJ** [comment]
Try to rename your efpt.config.json file

**Comment by dmatter98** [comment]
renaming, efpt.config.json => efpt.2config.json : worked.

**Comment by ErikEJ** [comment]
Can you share the file, then I will investigate.

**Comment by dmatter98** [comment]
Hi Erik,

Let me know if you need the original file. But ultimately I had references to multiple tables, views, and procedures -which I have removed those references. I have also removed identifying information, leaving the all the configurations in place as they are.

**Original File Name:**
efpt.config.json

**Configuration (with identifying information removed):**
{
   "CodeGenerationMode": 0,
   "ContextClassName": "MyContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": "MyPath",
   "ProjectRootNamespace": "My.Project",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "Name": "[dbo].[MyTable]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[MyProc]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[MyView]",
         "ObjectType": 3
      }
   ],
   "UiHint": "MachineName\\MSSQLSERVER01.My",
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": false,
   "UseHandleBars": false,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseNoConstructor": false,
   "UseNoNavigations": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UseSpatial": false
}

**Comment by ErikEJ** [comment]
In order to debug, I need the original, you could email it to me: ejlskov at hotmail for com

**Comment by dmatter98** [comment]
Done. The subject line is the URL to this issue: https://github.com/ErikEJ/EFCorePowerTools/issues/797

**Comment by ErikEJ** [comment]
Fixed in latest daily build, please let med know if that works for you.

**Comment by dmatter98** [comment]
Daily Build 2.5.531.0 is working as expected with the original file name. Thanks again Erik; Great work!
