### ISSUE TITLE
Check for precense of EfSchemaCompare!

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#809]
System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'EfSchemaCompare, Version=5.1.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'EfSchemaCompare, Version=5.1.2.0, Culture=neutral, PublicKeyToken=null'
   at Modelling.EfCoreCompareBuilder.GetCompareResult(String outputPath, String startupOutputPath, String connectionString, String dbContexts)
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 36

Parameter name: processResult
    at  EFCorePowerTools.Handlers.Compare.CompareHandler+<GetComparisonResultAsync>d__4.MoveNext (CompareHandler.cs:191) (EFCorePowerTools, Version=2.5.536.0, Culture=neutral, PublicKeyToken=d9645e6262c2eca7)
    at  System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
    at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
    at  System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
    at  EFCorePowerTools.Handlers.Compare.CompareHandler+<HandleComparisonAsync>d__2.MoveNext (CompareHandler.cs:111) (EFCorePowerTools, Version=2.5.536.0, Culture=neutral, PublicKeyToken=d9645e6262c2eca7)

**Comment by sinankeskin** [comment]
Hi. I want to translate your add-in to Turkish but I can't test compare screens because of this error.

Since this issue is closed for 19 days should I understand new release is coming?

Thank you.

**Comment by ErikEJ** [comment]
@sinankeskin are you using the latest daily build?

**Comment by sinankeskin** [comment]
No. I'm using latest official release.

![image](https://user-images.githubusercontent.com/2091777/111083820-67b07f80-8520-11eb-99d5-6131c0a77ed6.png)

**Comment by sinankeskin** [comment]
I installed the latest the appveyor artifact but I'm still seeing this error.

![image](https://user-images.githubusercontent.com/2091777/111083964-574cd480-8521-11eb-9ba8-a387ba8f6686.png)

**Comment by sinankeskin** [comment]
Clean & Build fixed this. So sorry for inconvenience.

Thank you @ErikEJ
