### ISSUE TITLE
"Compare DbContext to database" doesn't detect the context

### ISSUE THREAD

**Issue by Dasein732** [ErikEJ/EFCorePowerTools#818]
When using "Compare DbContext to database" from the Power Tools menu, the operation fails with the following error:

```
System.ArgumentException: Error:
System.ArgumentException: You must provide at least one DbContext instance. (Parameter 'dbContexts')
   at EfSchemaCompare.CompareEfSql.CompareEfWithDb(String configOrConnectionString, DbContext[] dbContexts)
   at Modelling.EfCoreCompareBuilder.GetCompareResult(String outputPath, String startupOutputPath, String connectionString, String dbContexts) in C:\Code\EFCorePowerTools\src\GUI\efpt50.core\EFCoreCompareBuilder.cs:line 53
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 36

Parameter name: processResult
   at EFCorePowerTools.Handlers.Compare.CompareHandler.<GetComparisonResultAsync>d__4.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\Compare\CompareHandler.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EFCorePowerTools.Handlers.Compare.CompareHandler.<HandleComparisonAsync>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\Compare\CompareHandler.cs:line 111
```

The initial dialogue detects the context, but the script doesn't. I've confirmed that the connection string is valid, I've tried comparing the context within its project and extracted to a new project, both on .net core 3.1 and 5.0 and I'm getting same result in all of the listed cases.

### Steps to reproduce
EF Core power tools > Compare DbContext to database > select connection string and tick the DbContext then click OK.

### Further technical details
EF Core Power Tools version: 2.5

Database engine: SQL Server 15.0.2080.9

Visual Studio version: 16.8.6

**Comment by ErikEJ** [comment]
Can the "Add DbContext Diagram" feature detect you DcContext?

**Comment by ErikEJ** [comment]
Can you share a repro project?

**Comment by Dasein732** [comment]
"Add DbContext Diagram" detects the context and generates the diagram, it might be relevant that I'm configuring the context via IDesignTimeDbContextFactory and I don't have an OnConfiguring section on this context.

I'll try to cobble a repro project during the day.

**Comment by ErikEJ** [comment]
I pass the DbContext names as a command line parameter, so probably that is broken. Can you share a screenshot of the dialog to select the Context?

**Comment by Dasein732** [comment]
Certainly

![image](https://user-images.githubusercontent.com/25817504/109321364-59d8da00-7851-11eb-9f19-76f836919d2a.png)

Just to confirm the class name is identical to the file name

**Comment by ErikEJ** [comment]
Hmmm... Maybe it is the connection string parsing that fails??

**Comment by Dasein732** [comment]
I don't think so, I can reverse engineer the context from it so it should work.

**Comment by ErikEJ** [comment]
Then I need a repro project.

**Comment by Dasein732** [comment]
When I extracted the project into a separate solution I got an error that EfSchemaCompare was missing instead, installing it into the original project resolved the issue.

**Comment by ErikEJ** [comment]
So you have no errors any more??

**Comment by Dasein732** [comment]
No errors, any chance we could get some sort of a warning if this package is missing?

**Comment by ErikEJ** [comment]
Yes, already in latest daily: https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes
