### ISSUE TITLE
Unable to pass port to connection string

### ISSUE THREAD

**Issue by MrMuMu** [ErikEJ/EFCorePowerTools#824]
With the following connection string `"ConnectionString": "Host=127.0.0.1:5432;Database=db;Username=user;Password=pwd"` I am unable to reverse engineer. If I drop port of the `Host` it works.

Note: using from the cli

Error:

```
System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
```

**Comment by ErikEJ** [comment]
I think it should be 127.0.0.1,5432

**Comment by MrMuMu** [comment]
Tried that aswell does not work same error

**Comment by ErikEJ** [comment]
Ask in the MpgSQL repo, not really releated to EF Core Power Tools

**Comment by MrMuMu** [comment]
`"Host=127.0.0.1:5432;Database=db;Username=user;Password=pwd"` this is the format I'm using on my project currently but it does not work on with the Power Tools

**Comment by ErikEJ** [comment]
I am just passing the connection string as is to NpgSQL ADO.NET provider

**Comment by MrMuMu** [comment]
It works like this dont know why "Host=127.0.0.1;Port=5432;Database=db;Username=user;Password=pwd"
