### ISSUE TITLE
System.ArgumentException: Value cannot be empty or only white spaces. (Parameter 'name')

### ISSUE THREAD

**Issue by srinath-karunakaran** [ErikEJ/EFCorePowerTools#825]
Hi @ErikEJ 

### Steps to reproduce
Step 1:
I click reverse engineer
Step 2:
I choose the database connection and also check the test connection is done, but am facing this below error
![step1](https://user-images.githubusercontent.com/79804015/109427893-4c366800-79a9-11eb-8f88-0d6891919681.PNG)

Step 3:
System.Exception: Table list error: 
System.ArgumentException: Value cannot be empty or only white spaces. (Parameter 'name')
   at RevEng.Shared.TableModel..ctor(String name, String schema, DatabaseType databaseType, ObjectType objectType, IEnumerable`1 columns) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Shared\TableModel.cs:line 85
   at RevEng.Core.TableListBuilder.GetProcedures() in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\TableListBuilder.cs:line 92
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 31

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 46
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 100
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType, SchemaInfo[] schemas) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 77
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<>c__DisplayClass16_0.<GetTablesAsync>b__0() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 545
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<GetTablesAsync>d__16.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 545
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<LoadDataBaseObjectsAsync>d__9.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 296
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__5.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 137

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2019 16.8)

**Comment by ErikEJ** [comment]
Looks like you have a stored procedure with a abnormal name - can you share your schema?

**Comment by srinath-karunakaran** [comment]
Hi @ErikEJ 

Thanks for the quick response feel good.
i share the sample project for your reference
[EmployeeForm (2).zip](https://github.com/ErikEJ/EFCorePowerTools/files/6057800/EmployeeForm.2.zip)

**Comment by ErikEJ** [comment]
@srinath-karunakaran You are sharing your code, I need your database schema!

**Comment by ErikEJ** [comment]
Alternatively, run this against your database, and share the result:

```
SELECT ROUTINE_SCHEMA, ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_TYPE = 'PROCEDURE'
ORDER BY ROUTINE_NAME;

```

**Comment by srinath-karunakaran** [comment]
Hi @ErikEJ 

Thanks for sharing the above query, 
After running this command in the result someone creates a procedure without the name
so I remove the unnamed procedure then run again EF power tool it's working as expected.

thanks a lot.

**Comment by srinath-karunakaran** [comment]
Hi @ErikEJ 

Kindly find the attachment

[Schema.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6057962/Schema.zip)

**Comment by ErikEJ** [comment]
Please let me fix this ,,😀

**Comment by ErikEJ** [comment]
Fixed in latest daily build
