### ISSUE TITLE
EFCore Power tOols Reverse Engineering generates error, but error disappears

### ISSUE THREAD

**Issue by ghisbo** [ErikEJ/EFCorePowerTools#841]
On a certain table ( postgres ) the "Generating Code" is interrupted with an error message. I cannot see what the message is. Is there a way to log the messages ? 

### Further technical details
Version 2.5.537.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: ( Postgres)

Visual Studio version: 2019 16.8.5

**Comment by ErikEJ** [comment]
Check the VS Output window/pane

**Comment by ghisbo** [comment]
That gives no indication of an error. 
It is in the bottom of the OutputPane ( where Generating Code appears) that a  error message is shortly visible. It looks like the process hangs after that ( the basket in the middle keeps running) 


   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 26
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 124
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 55
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GenerateEfRevEng(Project project, ReverseEngineerOptions options, Tuple`2 containsEfCoreReference) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 432
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__5.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 153

**Comment by ghisbo** [comment]
When i uncheck  EF Core5, then the error is not present, but then the pluralize does not work.
When i check EF Core5, the pluralization works bet the error appears

**Comment by ErikEJ** [comment]
![image](https://user-images.githubusercontent.com/4169187/110508688-8d451f80-8101-11eb-96ee-fe172f343b1c.png)

(Should be from "Build" no "Package Manager"

**Comment by ErikEJ** [comment]
Any update?

**Comment by ghisbo** [comment]
Have another probleem. Will get back asap




Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Erik Ejlskov Jensen <notifications@github.com>
Datum: 9/03/2021 19:54 (GMT+01:00)
Aan: ErikEJ/EFCorePowerTools <EFCorePowerTools@noreply.github.com>
Cc: Ghislain Borremans <ghislain@beness.eu>, Author <author@noreply.github.com>
Onderwerp: Re: [ErikEJ/EFCorePowerTools] EFCore Power tOols Reverse Engineering generates error, but error disappears (#841)


Any update?

**Comment by ghisbo** [comment]
Hello, 
I had problems with my PC and reinstalled VS2019 and EF Core Power tools. The error message has disappeared.
So this can be closed. The pluralization however does not work ( and that worked before )  but that is a minor issue.

**Comment by ErikEJ** [comment]
Please create a new issue with details on the pluralization issue, it should be fixed.
