### ISSUE TITLE
Reverse engineering failing with mysql

### ISSUE THREAD

**Issue by ThDoor** [ErikEJ/EFCorePowerTools#845]
Hi EJ,

Just trying the tool reverse engineering a single table from an MySql db and I get this error:

System.Exception: Reverse engineer error: 
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.GetConstraints(DbConnection connection, IReadOnlyList`1 tables)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.GetTables(DbConnection connection, Func`3 filter)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at RevEng.Core.ReverseEngineerRunner.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, ServiceProvider serviceProvider) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 242
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 176
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 57

### Steps to reproduce
Can't give you access to the db ;-), but perhabs you can hint me on what to look for.

I am able to reverse engineer other tables from the db

### Further technical details
EF Core Power Tools version: 2.5.537

Database engine: MySql

Visual Studio version: Visual Studio 2019 16.9.1

**Comment by ErikEJ** [comment]
Are you using EF Core 3.1 or 5?

It looks like a MySQL bug...

**Comment by ThDoor** [comment]
Hi EJ,

I'm using EFCore 5.0.4 and Pomelo 3.2.4.

Is it about reading constraints or indexes or the sort?

br

**Comment by ThDoor** [comment]
Hi EJ,

I was just doing an experiment and the table failing has fk to tables i was not including 😊.
After including referenced tables it's working.

Thx,
Br,
Thomas

**Comment by ErikEJ** [comment]
Still seems like a bug @lauxjpn ?

**Comment by ErikEJ** [comment]
@ThDoor Just FYI: You must use this provider with EF Core 5 (which is also the one used by EF Core Power Tools when selecting EF Core 5 code generation):

`<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="5.0.0-alpha.2" />`

**Comment by ThDoor** [comment]
Thx.
Handled my 'Reference to type 'IConventionRelationshipBuilder' claims it is defined in 'Microsoft.EntityFrameworkCore', but it could not be found' error.

**Comment by ErikEJ** [comment]
Closing as external, maybe log on error on the Pomelo repo?

**Comment by ErikEJ** [comment]
This is fixed in the latest daily build of the Toolbox
