### ISSUE TITLE
Stored procedure with Geography type wont import - System.ArgumentOutOfRangeException: cleanedTypeName

### ISSUE THREAD

**Issue by nathanh2011** [ErikEJ/EFCorePowerTools#852]
Hi Erik,

First of all, great work with this tool, I am migrating a WebForms project to .NET Core and your tool is the best replacement I have found for the EF edmx designer.

I am currently facing an issue where your tool does not seem to import my stored procedure with a geography data type and fails with a `System.ArgumentOutOfRangeException: cleanedTypeName:  (Parameter 'cleanedTypeName') `error (full error log below).

I am using the latest daily build as of today (2020-03-14) and I searched through the history of issues and it seems like it should import spatial types so I am not sure what is happening. I have also included my stroed procedure below (which takes a geography position which is just a lat/lon point and attempts to find the closest matching stored location within 100m from a table). 

I also modified the stored proc and took out any reference to geography data types to narrow down that it was the geography data types which after doing that my DB imports correctly. 

Any help with this issue would be greatly appreciated.

This is the complete output of the error:

```
System.Exception: Reverse engineer error: 
System.ArgumentOutOfRangeException: cleanedTypeName:  (Parameter 'cleanedTypeName')
   at RevEng.Core.SqlServerSqlTypeExtensions.GetSqlDbType(String storeType) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerSqlTypeExtensions.cs:line 60
   at RevEng.Core.SqlServerSqlTypeExtensions.GetClrType(String storeType, Boolean isNullable) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerSqlTypeExtensions.cs:line 65
   at RevEng.Core.SqlServerSqlTypeExtensions.ClrType(ModuleParameter storedProcedureParameter) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerSqlTypeExtensions.cs:line 28
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.<GenerateProcedure>b__10_1(ModuleParameter p) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 188
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.GenerateMethodSignature(Procedure procedure, List`1 outParams, IEnumerable`1 paramStrings, String retValueName, List`1 outParamStrings, String identifier) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 291
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.GenerateProcedure(Procedure procedure, ProcedureModel model) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 204
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.WriteProcedureDbContext(ModuleScaffolderOptions procedureScaffolderOptions, ProcedureModel model) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 174
   at RevEng.Core.Procedures.SqlServerStoredProcedureScaffolder.ScaffoldModel(ProcedureModel model, ModuleScaffolderOptions procedureScaffolderOptions, List`1& errors) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs:line 73
   at RevEng.Core.ReverseEngineerRunner.GenerateStoredProcedures(ReverseEngineerCommandOptions options, List`1& errors, ServiceProvider serviceProvider, String outputContextDir, String modelNamespace, String contextNamespace) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 264
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 87
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 57

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 26
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 129
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 57
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GenerateEfRevEng(Project project, ReverseEngineerOptions options, Tuple`2 containsEfCoreReference) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 443
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__5.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 154
```

This is my stored proc:
```
ALTER PROCEDURE [dbo].[stpGetGeocodedLocation]
	@SearchPoint geography,
	@Distance int = 100 -- default 100m search
AS
BEGIN	
	SET NOCOUNT ON;

    SELECT TOP 1 *, @SearchPoint.STDistance(tblGeocodeLocation.Location) as Distance 
	FROM tblGeocodeLocation 
	WHERE @SearchPoint.STDistance(tblGeocodeLocation.Location) <= @Distance
	ORDER BY Distance
END
```

And this is what I altered it to which imports with no issues:
```

ALTER PROCEDURE [dbo].[stpGetGeocodedLocation]	
	@SearchPoint int,
	@Distance int = 100 -- default 100m search
AS
BEGIN	
	SET NOCOUNT ON;

    SELECT 1
END

```

**Comment by ErikEJ** [comment]
Apparently, this has never worked - see change: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureModelFactory.cs#L105 

Fixed in latest daily build - thanks for reporting!

**Comment by ErikEJ** [comment]
Please let me know if the fix worked for you - TIA

**Comment by nathanh2011** [comment]
Hi Erik, just downloaded the latest build and seemed to import everything fine. Thank you so much for the quick turn around and for your great work!
