### ISSUE TITLE
Daily Build 2021-03-17: System.Resources.MissingManifestResourceException

### ISSUE THREAD

**Issue by nathanh2011** [ErikEJ/EFCorePowerTools#858]
It looks like in the latest daily build with the resource cleanup that some files were deleted that might be needed. After installing the latest daily build (2021-03-17 GMT +11) I have now get the following error when trying to open the power tools. 

```
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "EFCorePowerTools.Resources.en.resources" was correctly embedded or linked into assembly "EFCorePowerTools" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at EFCorePowerTools.Resources.get_NpgsqlProvider() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Resources.Designer.cs:line 77
   at EFCorePowerTools.Helpers.VsDataHelper.GetDataConnections(EFCorePowerToolsPackage package) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Helpers\VsDataHelper.cs:line 20
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ChooseDataBaseConnection(ReverseEngineerOptions options) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 200
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__5.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 126
```

This results in the tool extension not opening at all, when right clicking on a project to reverse engineer a database nothing appears to happen.

**Comment by ErikEJ** [comment]
@nathanh2011 Thanks for reporting this, and thanks for being a user of the daily builds.
