### ISSUE TITLE
Possible bug in VS 2019 new version 16.9.2 ?

### ISSUE THREAD

**Issue by flencinas** [ErikEJ/EFCorePowerTools#859]
I have installed
Microsoft Visual Studio Community 2019
Version 16.9.2

Last night I installed the latest version and from that moment Reverse Engineer stopped working

The first step of the wizzard where it requests the connection with the database does it correctly

And the next step fails

I have tried reinstalling it again and it keeps crashing

I have tried in projects of other solutions with different databases and it follows the same fault

This is a error detail 

System.Exception: Table list error: Unable to launch external process: 

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 49
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 105
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType, SchemaInfo[] schemas) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 82
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<>c__DisplayClass17_0.<GetTablesAsync>b__0() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 572
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<GetTablesAsync>d__17.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 572
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<LoadDataBaseObjectsAsync>d__9.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__5.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 138

### Further technical details
EF Core Power Tools version: 2.5.567

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.9.2

**Comment by ErikEJ** [comment]
You can investigate why this fails by going to the %temp%\efreveng.2.5 folder, and run a command like this:

`efreveng.exe 3 "Data Source=.\SQLEXPRESS;Initial Catalog=Northwind;Integrated Security=True"`

**Comment by ErikEJ** [comment]
@flencinas  Any update?

**Comment by kenneth-developer** [comment]
I have same problem in 16.9.2

**Comment by ErikEJ** [comment]
@kenneth-developer  Could you please try the debugging steps described above, thanks

**Comment by kenneth-developer** [comment]
Error:
  An assembly specified in the application dependencies manifest (efreveng.deps.json) was not found:
    package: 'Bricelam.EntityFrameworkCore.Pluralizer', version: '1.0.0'
    path: 'lib/netstandard2.0/Bricelam.EntityFrameworkCore.Pluralizer.dll'

**Comment by ErikEJ** [comment]
Perfect, which folder and exe file do you run?

**Comment by kenneth-developer** [comment]
PS C:\Users\kennethcarlsson\AppData\Local\Temp\efreveng.2.5.567.0> ./efreveng.exe 3

**Comment by ErikEJ** [comment]
Is the mentioned dll present in the folder?

**Comment by kenneth-developer** [comment]
<img width="732" alt="Skärmavbild 2021-03-18 kl  12 29 03" src="https://user-images.githubusercontent.com/78693890/111619356-c0646e80-87e5-11eb-8735-808f188fc6ed.png">

**Comment by ErikEJ** [comment]
Sorry, I mean: Bricelam.EntityFrameworkCore.Pluralizer

**Comment by kenneth-developer** [comment]
I'm a little unsure where to look in my solution, there is only this with Plural

**Comment by kenneth-developer** [comment]
<img width="274" alt="Bild" src="https://user-images.githubusercontent.com/78693890/111623384-9bbec580-87ea-11eb-9868-86391e457fb0.png">

**Comment by ErikEJ** [comment]
In the temp folder....

**Comment by kenneth-developer** [comment]
there is no EntityFrameworkCore.Pluralizer.dll in any folder in Temp

**Comment by ErikEJ** [comment]
The file name is Bricelam.EntityFrameworkCore.Pluralizer

**Comment by kenneth-developer** [comment]
There is no Bricelam.EntityFrameworkCore.Pluralizer in temp

**Comment by ErikEJ** [comment]
Try to remove the folder...

**Comment by kenneth-developer** [comment]
Now it works and the are alot of files in the temp folder

**Comment by kenneth-developer** [comment]
before it was just the 7 file you se above pic

**Comment by kenneth-developer** [comment]
Thanks for the help

**Comment by ErikEJ** [comment]
@flencinas could you try to remove the folder also?

**Comment by kenneth-developer** [comment]
II deleted the folder in temp and then went in i vs and ran your program and then it worked

**Comment by kenneth-developer** [comment]
a new folder was created with a lot more files than it was before I deleted it

**Comment by ErikEJ** [comment]
@kenneth-developer Thanks for your debugging help, apparently the file extraction got interrupted/blocked, and left only 7 files in the folder.

I will look into making this more robust.

**Comment by ErikEJ** [comment]
@kenneth-developer @flencinas I have attempted to fix this issue in the latest daily build, thanks for your debugging help!

**Comment by flencinas** [comment]
> @flencinas could you try to remove the folder also?

Yes it's working 
Sorry for the delay ....
Thank's Super Erik
