### ISSUE TITLE
Migration-feature support for EF Core 6 Preview 

### ISSUE THREAD

**Issue by joelmandell** [ErikEJ/EFCorePowerTools#862]
Hi and thank you for your awesome work. The feature that really makes things much easier for me is the migration ui.

Is it possible to make it work with EF Core 6 Preview?

**Comment by ErikEJ** [comment]
Are you using net5.0 or net6.0?

**Comment by joelmandell** [comment]
I am using .NET 5 currently. But might jump early on to .NET 6 if required.

Den tors 18 mars 2021 17:29Erik Ejlskov Jensen ***@***.***>
skrev:

**Comment by ErikEJ** [comment]
Added to latest daily, feel free to try it out.

**Comment by joelmandell** [comment]
Thank you. Got this: 

![image](https://user-images.githubusercontent.com/109020/111821855-6d70e100-88e3-11eb-9bd6-417dc91db449.png)

**Comment by ErikEJ** [comment]
Please paste the text instead of a screenshot. 
Even better, share a repro project.

**Comment by joelmandell** [comment]
It is a commercial WIP. So I do not share it here. Could I share it by mail?

```
---------------------------
Microsoft Visual Studio
---------------------------
EF Core Power Tools

Error:

System.InvalidOperationException: Runtime metadata changes are not allowed when the model hasn't been marked as read-only.

   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.EnsureReadOnly()

   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.GetOrCreateRuntimeAnnotations()

   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.AddRuntimeAnnotation(String name, Annotation annotation)

   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.AddRuntimeAnnotation(String name, Object value)

   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.Microsoft.EntityFrameworkCore.Infrastructure.IAnnotatable.AddRuntimeAnnotation(String name, Object value)

   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.AddDefaultMappings(RelationalModel databaseModel, IEntityType entityType)

   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Add(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider)

   at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationalModelConvention.ProcessModelFinalized(IModel model)

   at Modelling.EfCoreMigrationsBuilder.GetMigrationStatus(DbContext context) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreMigrationsBuilder.cs:line 110

   at Modelling.EfCoreMigrationsBuilder.GetMigrationStatus(String outputPath, String startupOutputPath) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreMigrationsBuilder.cs:line 82

   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 41

```

**Comment by ErikEJ** [comment]
I suspect it could be s preview issue, so would be happy if you can share, I will of course burn after reading: mail is Ejlskov at hotmail dot com

**Comment by ErikEJ** [comment]
Attempted a fix in latest daily now

**Comment by joelmandell** [comment]
That did work. Thank you sir!
