### ISSUE TITLE
Exception for excluded foreign key field

### ISSUE THREAD

**Issue by Hefaistos68** [ErikEJ/EFCorePowerTools#872]
Although I have excluded the 'Country' field (type int) from reverse engineering, i get an exception for it:

```
System.Exception: Reverse engineer error: 
System.InvalidOperationException: The property 'Country' cannot be added to the type 'Tblclient' because no property type was specified and there is no corresponding CLR property or field. To add a shadow state property, the property type must be specified.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, String propertyName, MemberInfo memberInfo, Nullable`1 typeConfigurationSource, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, String propertyName, Nullable`1 typeConfigurationSource, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.GetOrCreateProperties(IReadOnlyList`1 propertyNames, Nullable`1 configurationSource, IReadOnlyList`1 referencedProperties, Boolean required, Boolean useDefaultType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasIndex(IReadOnlyList`1 propertyNames, String name, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.HasIndex(String[] propertyNames, String name)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitIndex(EntityTypeBuilder builder, DatabaseIndex index)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitIndexes(EntityTypeBuilder builder, ICollection`1 indexes)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at RevEng.Core.ColumnRemovingScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ColumnRemovingScaffoldingModelFactory.cs:line 55
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at RevEng.Core.ReverseEngineerRunner.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, ServiceProvider serviceProvider) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 314
   at RevEng.Core.ReverseEngineerRunner.GenerateDbContext(ReverseEngineerCommandOptions options, ServiceProvider serviceProvider, IReverseEngineerScaffolder scaffolder, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 170
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 91
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 57

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 26
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 129
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 57
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GenerateEfRevEng(Project project, ReverseEngineerOptions options, Tuple`2 containsEfCoreReference) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 443
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__5.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 154

```
I have already used Reverse Engineer a few times with this database (Mysql) without problems, now I added another table to the list to reverse.

### Steps to reproduce
Guess repro will be difficul without the database,

### Further technical details
EF Core Power Tools version: 
Version 2.5.573.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes
Database engine: (MySql)

Visual Studio version: (Visual Studio 2019 community 16.10.0 preview 1, cant get MySql extensions to work in 16.9.2)

**Comment by ErikEJ** [comment]
I have seen similar issues reported before, assume it is due to some invalid model created from the MySql provider.

One user fixed by including all tables the selected table related to.

**Comment by Hefaistos68** [comment]
I just resolved it by including the field instead of excluding it.  Not the best solution but i can manually remove the field from the generated file.

**Comment by Hefaistos68** [comment]
Weird thing is it happens only with SOME int fields, not all. Here is the SQL create statement for this particular table:

```
CREATE TABLE `tblclients` (
  `userid` int(11) NOT NULL AUTO_INCREMENT,
  `company` varchar(191) DEFAULT NULL,
  `vat` varchar(50) DEFAULT NULL,
  `phonenumber` varchar(30) DEFAULT NULL,
  `country` int(11) NOT NULL DEFAULT '0',
  `city` varchar(100) DEFAULT NULL,
  `zip` varchar(15) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `address` varchar(100) DEFAULT NULL,
  `website` varchar(150) DEFAULT NULL,
  `datecreated` datetime NOT NULL,
  `active` int(11) NOT NULL DEFAULT '1',
  `leadid` int(11) DEFAULT NULL,
  `billing_street` varchar(200) DEFAULT NULL,
  `billing_city` varchar(100) DEFAULT NULL,
  `billing_state` varchar(100) DEFAULT NULL,
  `billing_zip` varchar(100) DEFAULT NULL,
  `billing_country` int(11) DEFAULT '0',
  `shipping_street` varchar(200) DEFAULT NULL,
  `shipping_city` varchar(100) DEFAULT NULL,
  `shipping_state` varchar(100) DEFAULT NULL,
  `shipping_zip` varchar(100) DEFAULT NULL,
  `shipping_country` int(11) DEFAULT '0',
  `longitude` varchar(191) DEFAULT NULL,
  `latitude` varchar(191) DEFAULT NULL,
  `default_language` varchar(40) DEFAULT NULL,
  `default_currency` int(11) NOT NULL DEFAULT '0',
  `show_primary_contact` int(11) NOT NULL DEFAULT '0',
  `stripe_id` varchar(40) DEFAULT NULL,
  `registration_confirmed` int(11) NOT NULL DEFAULT '1',
  `addedfrom` int(11) NOT NULL DEFAULT '0',
  `userid2` int(11) DEFAULT NULL,
  PRIMARY KEY (`userid`),
  KEY `country` (`country`),
  KEY `leadid` (`leadid`),
  KEY `company` (`company`)
) ENGINE=InnoDB AUTO_INCREMENT=160 DEFAULT CHARSET=utf8;

```
Only the "country" and "leadid" fields cause this error when excluding, any other can be excluded at will.

**Comment by ErikEJ** [comment]
Because they are foreign keys?

**Comment by Hefaistos68** [comment]
Possibly. Maybe it should not be possible to exclude foreign key fields from creation? Or create them automatically as "shadow state property" if excluded? Or readonly?

**Comment by ErikEJ** [comment]
Maybe it should not be possible, you may have a point!
@sm15455 Thoughts?

**Comment by Hefaistos68** [comment]
After all, primary keys cant be excluded either

**Comment by ErikEJ** [comment]
I know! That's why I think you may have a point!

**Comment by sm15455** [comment]
I think it should be possible to exclude any field but those that compose the PK. The field-exclusion feature is not about removing a field from default EF Core mapping, it's about enabling developer to map the field manually in a different way. I also had a case in the past where I needed to exclude a foreign key from mapping and it was OK since it was nullable.
The fact that MySql provider generates an error when foreign keys are excluded is another kind of problem. @ErikEJ  maybe we could adapt experience of the object selection page based on database type?

**Comment by ErikEJ** [comment]
@sm15455 So your impression is that this works fine with SQL Server?

**Comment by sm15455** [comment]
Worked for me, but I didn't map the foreign key, nor the table the foreign key was pointing to. I have to check all cases

**Comment by sm15455** [comment]
Please forgive me, I was wrong. In the project I was mentioning, I **_manually_** mapped the whole entity. I tried generating the code now excluding the FK and it doesn't work in SQL Server too. I tried against the northwind database and that fails too. 
It makes sense to disable exclusion for foreign key columns too.

**Comment by ErikEJ** [comment]
@sm15455 Thank you very much for the quick fix, I have updated the tools zip files with the fix in the latest daily build.

@Hefaistos68  FYI!
