### ISSUE TITLE
Exception when Add DbContext Diagram from Shared Project

### ISSUE THREAD

**Issue by paulyiu** [ErikEJ/EFCorePowerTools#892]
When Add DbContext Diagram on Shared Project, VS will force quit and reopen, it look like cannot GetOutPutAssemblyPath.
![image](https://user-images.githubusercontent.com/48709072/113010381-5d8eb200-91ab-11eb-89ae-982d920c9c97.png)
![image](https://user-images.githubusercontent.com/48709072/113010781-b3635a00-91ab-11eb-89b1-c5ef284cba96.png)

### Steps to reproduce
create Shared Project then Add DbContext Diagram (any menu item beside Reverse Engineer or About will throw exception)
![image](https://user-images.githubusercontent.com/48709072/113005638-3cc45d80-91a7-11eb-880a-a1943668d0e5.png)
![image](https://user-images.githubusercontent.com/48709072/113005203-db03f380-91a6-11eb-9dc2-ddc6e423a6d1.png)

### Further technical details
EF Core Power Tools version: 
Version 2.5.587.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: Oracle
Visual Studio version: VS2019

repo:
https://github.com/paulyiu/EfCorePowerToolsTest

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.IO.Path.Combine(System.String, System.String)
   at EFCorePowerTools.Extensions.ProjectExtensions.GetOutPutAssemblyPath(EnvDTE.Project)
   at EFCorePowerTools.EFCorePowerToolsPackage+<LocateProjectAssemblyPathAsync>d__19.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at EFCorePowerTools.EFCorePowerToolsPackage+<OnProjectContextMenuInvokeHandlerAsync>d__18.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at EFCorePowerTools.EFCorePowerToolsPackage+<<InitializeAsync>b__11_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

```

**Comment by ErikEJ** [comment]
Which project do you launch from?

Can you share a repro solution?

**Comment by paulyiu** [comment]
Startup project is WebApplication1
I launch Add DbContext Diagram from SharedProject1, 
beside Reverse Engineer and About, other menu item will throw GetOutPutAssemblyPath issue as well.
but I can generate entity from SharedProject1.

repo: 
https://github.com/paulyiu/EfCorePowerToolsTest

![image](https://user-images.githubusercontent.com/5702534/113072043-a28d0580-91f8-11eb-9ce2-2708e8c19aed.png)

**Comment by paulyiu** [comment]
oh, no issue when launch from WebApplication1, thanks @ErikEJ
