### ISSUE TITLE
Reverse Engineer Fails with SQL Server 2008

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#9]
_From @matthewDDennis on May 7, 2018 19:44_

System.Data.SqlClient.SqlException (0x80131904): 'CONCAT' is not a recognized built-in function name.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.SqlServerDatabaseModelFactory.GetTables(DbConnection connection, Func`3 tableFilter, IReadOnlyDictionary`2 typeAliases)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String outputDbContextDir, String contextName, Boolean useDataAnnotations, Boolean useDatabaseNames)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 157
ClientConnectionId:26b0c024-00ad-446e-8746-fd229c61a88c
Error Number:195,State:10,Class:15

_Copied from original issue: ErikEJ/SqlCeToolbox#706_

**Comment by ErikEJ** [comment]
What SQL Server version?

**Comment by ErikEJ** [comment]
I am guessing 2008 - I have logged https://github.com/aspnet/EntityFrameworkCore/issues/11932

**Comment by ErikEJ** [comment]
_From @shadowfoxish on May 9, 2018 19:44_

I was seeing this as well, Microsoft SQL Server 2008 (SP4) - 10.0.6241.0

**Comment by ErikEJ** [comment]
This will be fixed in EF Core 2.1.1

**Comment by RefX32** [comment]
I am still running into this issue. Version: 10.50.4042.0

**Comment by ErikEJ** [comment]
@RefX32  Correct, still using EF Core 2.1.0 in Power Tools

**Comment by shadowfoxish** [comment]
I moved off SQL 2008 for my development stuff, and that solved it.

**Comment by bhaider7** [comment]
I am still getting the same error with SQL 2008 and unfortunately, I can not upgrade.

Environment:
Dot Net Core 2.1
EF Core 2.1.4 
Power Tools stable version 

Even I tried with the EF Core 2.2.0.preview2-35157 and the latest daily build (1.0.654.0) of Power Tools

**Comment by ErikEJ** [comment]
The Power Tools use the 2.1, not 2.1.1 bits. I will wait for 2.2 to be released before I update the Power Tools dependencies

**Comment by ErikEJ** [comment]
Fixed in latest daily build
