### ISSUE TITLE
EF Core Power Tool Issue with VS 2019

### ISSUE THREAD

**Issue by mirshahnewaz** [ErikEJ/EFCorePowerTools#908]
Hi Erik,
Thanks for offering to help via PluralSight. Any help/direction would be great.
I am using VS 2019 (16.9.2), ASP.NET Core Web Api, and SQL Servver. I was unsuccessfully trying to add DBContext Diagram via EF Core Power Tools. My EF Core Power Tools version is 2.5.606. My db context project file contents are:
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>

And I get the following error in my Output window. 

System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.get_Signature()
   at System.Reflection.RuntimeMethodInfo.get_ReturnType()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.IsFactory[TReturn](MethodInfo factory)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveFactory[T](Assembly assembly, String name)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveHostBuilderFactory[THostBuilder](Assembly assembly)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.ResolveServiceProviderFactory(Assembly assembly)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.Create(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at Modelling.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 82
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 33
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 57

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.<GenerateAsync>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 78

![EFCorePowerToolError](https://user-images.githubusercontent.com/41802891/113780811-a4d6ee80-9727-11eb-851a-10e37898a0e5.PNG)

**Comment by ErikEJ** [comment]
Make sure you have the correct Startup project set in Visual Studio.

**Comment by ErikEJ** [comment]
Additional tips and advice here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model

**Comment by ErikEJ** [comment]
Any news?

**Comment by ErikEJ** [comment]
Closing, assume this was resolved, feel free to re-open if not the case.
