### ISSUE TITLE
Compare DbContext to Database

### ISSUE THREAD

**Issue by FerdinandoCavaliere** [ErikEJ/EFCorePowerTools#909]
I try to compare DbContext to Database but in the Output windows of visual studio 2019 there is this error:

Parameter name: processResult
   at EFCorePowerTools.Handlers.Compare.CompareHandler.<GetComparisonResultAsync>d__5.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\Compare\CompareHandler.cs:line 200
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EFCorePowerTools.Handlers.Compare.CompareHandler.<HandleComparisonAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\Compare\CompareHandler.cs:line 120

### Steps to reproduce
I imported the schema from a Sql Server Project because the extension import objects from Sql Server versione >= 2012

### Further technical details
EF Core Power Tools version: 2.5.612

Sql Server 2008 R2 (The customer likes archeology 😁)

EF Power Tools Version 16.9.3

**Comment by ErikEJ** [comment]
In the temp folder there should be a file called: efptparams.txt

from a command prompt, run the contents of this file with `dotnet ` in front

**Comment by FerdinandoCavaliere** [comment]
Thanks for reply. I get the error in pic


Il giorno gio 8 apr 2021 alle ore 11:55 Erik Ejlskov Jensen <
***@***.***> ha scritto:

**Comment by ErikEJ** [comment]
You have to upload to GitHub, or better paste text, not images, please.

**Comment by FerdinandoCavaliere** [comment]
Directory di D:\VisualStudioProjects\DataBase\DataBase_Solution\ConsoleAppTest\Models

08/04/2021  11:16    <DIR>          .
08/04/2021  11:16    <DIR>          ..
08/04/2021  11:16             4.008 DbContextExtensions.cs
08/04/2021  11:16             1.404 FogliDiViaggio.cs
08/04/2021  11:16             3.022 SigadnetContext.cs
08/04/2021  11:16             5.764 SigadnetContextProcedures.cs
08/04/2021  11:16               322 uspCreaTitoloDaFogliDiViaggioResult.cs
               5 File         14.520 byte
               2 Directory  69.253.009.408 byte disponibili

D:\VisualStudioProjects\DataBase\DataBase_Solution\ConsoleAppTest\Models>dotnet exec --depsfile "D:\VisualStudioProjects\DataBase\DataBase_Solution\ConsoleAppTest\bin\Debug\netcoreapp3.1\ConsoleAppTest.deps.json" --additionalprobingpath "C:\Users\fcavaliere.P-FCAVALIERE\.nuget\packages" --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig "D:\VisualStudioProjects\DataBase\DataBase_Solution\ConsoleAppTest\bin\Debug\netcoreapp3.1\ConsoleAppTest.runtimeconfig.json" "C:\Users\fcavaliere.P-FCAVALIERE\AppData\Local\Temp\efpt\efpt.dll"  schemacompare "D:\VisualStudioProjects\DataBase\DataBase_Solution\ConsoleAppTest\bin\Debug\netcoreapp3.1\ConsoleAppTest.dll" "D:\VisualStudioProjects\DataBase\DataBase_Solution\ConsoleAppTest\bin\Debug\netcoreapp3.1\ConsoleAppTest.dll" "Data Source=cgsql02rsigdnet;Initial Catalog=SigdNet2;User ID=cavalieref;Password=hermes2012&" SigadnetContext
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Modelling.EfCoreCompareBuilder.GetCompareResult(String outputPath, String startupOutputPath, String connectionString, String dbContexts) in C:\Code\EFCorePowerTools\src\GUI\efpt50.core\EFCoreCompareBuilder.cs:line 43
Error:
System.ArgumentException: You must provide at least one DbContext instance. (Parameter 'dbContexts')
   at EfSchemaCompare.CompareEfSql.CompareEfWithDb(String configOrConnectionString, DbContext[] dbContexts)
   at Modelling.EfCoreCompareBuilder.GetCompareResult(String outputPath, String startupOutputPath, String connectionString, String dbContexts) in C:\Code\EFCorePowerTools\src\GUI\efpt50.core\EFCoreCompareBuilder.cs:line 53
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 36

D:\VisualStudioProjects\DataBase\DataBase_Solution\ConsoleAppTest\Models>

**Comment by FerdinandoCavaliere** [comment]
done ... sorry :)

Il giorno gio 8 apr 2021 alle ore 12:10 Erik Ejlskov Jensen <
***@***.***> ha scritto:

**Comment by ErikEJ** [comment]
Look at the error message:

No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions object in its constructor and passes it to the base constructor for DbContext.

Wiki tips here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model#challenges

**Comment by FerdinandoCavaliere** [comment]
Ok but since I only selected the context menu item I expect that the plugin already knows the connection string and the DBContext should already have been created when I did the reverse engineering. I love this addon but I believe there are still things to check. I'll do some trying. Thanks

**Comment by FerdinandoCavaliere** [comment]
Solved: I have provided the connection string OnConfiguring override method. Thanks a lot, Erik. Good good good work

**Comment by ErikEJ** [comment]
If the dbcontext is configured in another project, make sure to set that as the startup project.

**Comment by JERIONINTELLIWAN** [comment]
@ErikEJ Hi there,  could you help me please,   I'm no got error but nothing is showing,   when I involve the compare dbcontext to database.

I am using Mysql with .net Core 9

**Comment by ErikEJ** [comment]
@JERIONINTELLIWAN I you want free help, you must create a new issue with a simple runnable repro
