### ISSUE TITLE
Error in Stored Procedure with SQL Prep clause

### ISSUE THREAD

**Issue by mdecima** [ErikEJ/EFCorePowerTools#910]
I'm loogink for code genertion based on Sql database project or dacpac that support Stored Procedures. which is why I was excited when I heard about this project

The Issue Scenario is Reverse ingenering from DacPac file 
The error is generated by this stored procedure 

CREATE PROC [dbo].[paSorteos_BuscarRegistrosHabilitados] @idEspecialidad int = NULL, @idSubespecialidad int = NULL,
														@idLocalidad int = NULL, @filtrarMovimientos bit = NULL, @filtrarSorteados bit = NULL

AS 
DECLARE	@Select1 varchar(3000)

SET DATEFORMAT  DMY

SELECT @Select1 = " SELECT r.IdRegistro				
					FROM dbo.Registros r				
					INNER JOIN dbo.Especialidades es WITH (NOLOCK) ON es.IdTipoRegistro = r.IdTipoRegistro "		
.
.
//Simplified
.
.
EXECUTE (@Select1)		

**Error**

System.Exception: Table list error: 
Microsoft.SqlServer.Dac.Model.DacModelException: Add or update objects failed due to the following errors: 
Error SQL46095: The Identifier that starts with ' SELECT r.IdRegistro				
					FROM dbo.Registros r				
					INNER JOIN dbo.Especialidades es WITH (NOLOCK) ON es.IdTipoRegistr' is too long.  Maximum length is 128.

   at void Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.ThrowIfModelErrorsExist(string errorMessage)
   at void Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.DoAddOrUpdateObjects(string inputScript, string sourceName, TSqlObjectOptions options) x 2
   at void Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.AddOrUpdateObjects(TSqlScript inputScriptAst, string sourceName, TSqlObjectOptions options)
   at void GOEddie.Dacpac.References.DacpacMerger.Merge() in C:/Code/EFCorePowerTools/src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/DacpacConsolidate/DacpacMerger.cs:line 45
   at string GOEddie.Dacpac.References.DacpacConsolidator.Consolidate(string dacpacPath) in C:/Code/EFCorePowerTools/src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/DacpacConsolidate/DacpacConsolidator.cs:line 25
   at DatabaseModel ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerDacpacDatabaseModelFactory.Create(string dacpacPath, DatabaseModelFactoryOptions options) in C:/Code/EFCorePowerTools/src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacDatabaseModelFactory.cs:line 59
   at List<DatabaseTable> RevEng.Core.TableListBuilder.GetTableDefinitions() in C:/Code/EFCorePowerTools/src/GUI/RevEng.Core/TableListBuilder.cs:line 66
   at List<TableModel> RevEng.Core.TableListBuilder.GetTableModels() in C:/Code/EFCorePowerTools/src/GUI/RevEng.Core/TableListBuilder.cs:line 40
   at int efreveng.Program.Main(string[] args) in C:/Code/EFCorePowerTools/src/GUI/efreveng/Program.cs:line 30

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 46
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 105
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType, SchemaInfo[] schemas) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 82
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<>c__DisplayClass16_0.<GetDacpacTablesAsync>b__0() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 595
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<GetDacpacTablesAsync>d__16.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 595
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<LoadDataBaseObjectsAsync>d__10.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__6.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 146

**Comment by ErikEJ** [comment]
Have you tried publishing to a temporary live database, and reverse engineering from that?

**Comment by mdecima** [comment]
I got the error too in a published SQL Database

**Comment by ErikEJ** [comment]
Which error, I cannot be the same?

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closing as the requested information was not supplied - feel free to reopen when available
