### ISSUE TITLE
"Table list error" when trying to reverse engineer sql server database

### ISSUE THREAD

**Issue by mustafaelshobaky** [ErikEJ/EFCorePowerTools#928]
Describe what is not working as expected.

### Steps to reproduce
I'm trying to reverse engineer an existing database.
I has been working for me for a long time until it suddenly stopped now
I have tried to remove the efpt.config.json but this did not solve it 

### Further technical details
EF Core Power Tools version: 2.5.612

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.9.4

StackTrace and error in output:

System.Exception: Table list error: 
System.ArgumentException: Value cannot be empty or only white spaces. (Parameter 'name')
   at new RevEng.Shared.ColumnModel(string name, bool isPrimaryKey, bool isForeignKey) in C:/Code/EFCorePowerTools/src/GUI/RevEng.Shared/ColumnModel.cs:line 45
   at List<TableModel> RevEng.Core.TableListBuilder.GetTableModels() in C:/Code/EFCorePowerTools/src/GUI/RevEng.Core/TableListBuilder.cs:line 53
   at int efreveng.Program.Main(string[] args) in C:/Code/EFCorePowerTools/src/GUI/efreveng/Program.cs:line 30

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 46
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 105
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType, SchemaInfo[] schemas) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 82
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<>c__DisplayClass17_0.<GetTablesAsync>b__0() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 607
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<GetTablesAsync>d__17.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 607
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<LoadDataBaseObjectsAsync>d__10.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__6.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 146

System.Exception: Table list error: 
System.ArgumentException: Value cannot be empty or only white spaces. (Parameter 'name')
   at new RevEng.Shared.ColumnModel(string name, bool isPrimaryKey, bool isForeignKey) in C:/Code/EFCorePowerTools/src/GUI/RevEng.Shared/ColumnModel.cs:line 45
   at List<TableModel> RevEng.Core.TableListBuilder.GetTableModels() in C:/Code/EFCorePowerTools/src/GUI/RevEng.Core/TableListBuilder.cs:line 53
   at int efreveng.Program.Main(string[] args) in C:/Code/EFCorePowerTools/src/GUI/efreveng/Program.cs:line 30

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 46
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 105
   at EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType, SchemaInfo[] schemas) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 82
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<>c__DisplayClass17_0.<GetTablesAsync>b__0() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 607
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<GetTablesAsync>d__17.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 607
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<LoadDataBaseObjectsAsync>d__10.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__6.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ReverseEngineerHandler.cs:line 146

**Comment by mustafaelshobaky** [comment]
I was able to figure out the cause sfter looking to your code.
I have a column with no name in my database in a table that i don't use and don't intend to use.
I Don't if you can ignore these tables and just make thrm unselectable ???
Anyway,  i will just give the column a name. I'll leave this issue for you to decide if you want to properly handle this case.

**Comment by ErikEJ** [comment]
Not planned, fixed in EF Core 6, I think.
