### ISSUE TITLE
Add DbContext Model Diagram FileNotFoundException: The configuration file project.api\appsettings.json was not found and is not optional 

### ISSUE THREAD

**Issue by ankush4ds** [ErikEJ/EFCorePowerTools#964]
I have .net core 5.0 project where the solution has three projects 
a) pinsight.api  - holds the controllers and view models
b) pinsight.data - holds the dbcontext, repositories and migrations
c) pinsight.domain - holds the domain entities

### Steps to reproduce
Build the project - it build fine
Right click on the pinsight.api, goto ef core power tools and select AddDbContext Diagram

### Further technical details
EF Core Power Tools version: 2.5.636.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.9.3

Exception Details: [Note: appsettings.json file is set to copy always in Properties.Copy to Output Directory_]
System.ArgumentException: Error:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: The configuration file 'PINSIGHT.API\appsettings.json' was not found and is not optional. The physical path is 'C:\Users\ankus\source\repos\PINSIGHT365\PINSIGHT.API\bin\Debug\PINSIGHT.API\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at PINSIGHT.Data.DesignTimeDbContextFactory.CreateDbContext(String[] args) in C:\Users\ankus\source\repos\PINSIGHT365\PINSIGHT.Data\DesignTimeDbContextFactory.cs:line 12
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass16_0.<FindContextFactory>b__1()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 39
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 57

Parameter name: processResult
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType) in C:/projects/efcorepowertools/src/GUI/EFCorePowerTools/Handlers/ModelAnalyzerHandler.cs:line 78

**Comment by ErikEJ** [comment]
Make sure to set the correct startup project

**Comment by ankush4ds** [comment]
Thanks for prompt reply, My API project is the startup project when i get this error. I tried setting my data project (where my dbcontext is) as startup but same issue.

**Comment by ErikEJ** [comment]
I need a repro project in order to help you further.

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closing as requested info not supplied - this path looks very strange: C:\Users\ankus\source\repos\PINSIGHT365\PINSIGHT.API\bin\Debug\PINSIGHT.API\appsettings.json

Feel free to re-open if you can provide additional information.
